//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ASMCardScreenViewController, ASMIdentityDiscViewController, ASMLoadingViewController, ASMResourceKey, ASMViewBlueprint, UIViewController;
@protocol ASMBottomNavigationContent, ASMNavigationHierarchyController;

@protocol ASMViewControllerFactory <NSObject>
- (ASMIdentityDiscViewController *)createIdentityViewControllerWithWelcomeHeaderKey:(ASMResourceKey *)arg1 behavior:(long long)arg2;
- (ASMLoadingViewController *)createLoadingScreenViewControllerWithScreenKey:(ASMResourceKey *)arg1;
- (ASMCardScreenViewController *)createCardScreenViewControllerWithScreenKey:(ASMResourceKey *)arg1;
- (UIViewController<ASMBottomNavigationContent> *)createBottomNavigationContentControllerForBlueprint:(ASMViewBlueprint *)arg1;
- (UIViewController<ASMNavigationHierarchyController> *)createViewControllerForBlueprint:(ASMViewBlueprint *)arg1;
@end

