//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppAndExtensionsFramework/GPBMessage.h>

@class BTLTags, NSString;

@interface BTLConversation : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int avatarTapActionType; // @dynamic avatarTapActionType;
@property(nonatomic) int density; // @dynamic density;
@property(nonatomic) _Bool hasAvatarTapActionType; // @dynamic hasAvatarTapActionType;
@property(nonatomic) _Bool hasDensity; // @dynamic hasDensity;
@property(nonatomic) _Bool hasHasPopularLink; // @dynamic hasHasPopularLink;
@property(nonatomic) _Bool hasIsLocal; // @dynamic hasIsLocal;
@property(nonatomic) _Bool hasPopularLink; // @dynamic hasPopularLink;
@property(nonatomic) _Bool hasPromoOfferId; // @dynamic hasPromoOfferId;
@property(nonatomic) _Bool hasRationaleType; // @dynamic hasRationaleType;
@property(nonatomic) _Bool hasRowTapActionType; // @dynamic hasRowTapActionType;
@property(nonatomic) _Bool hasSnippetHash; // @dynamic hasSnippetHash;
@property(nonatomic) _Bool hasSwipeActionType; // @dynamic hasSwipeActionType;
@property(nonatomic) _Bool hasTags; // @dynamic hasTags;
@property(nonatomic) _Bool hasThreadId; // @dynamic hasThreadId;
@property(nonatomic) _Bool hasUnreadMessages; // @dynamic hasUnreadMessages;
@property(nonatomic) _Bool hasWasUnseen; // @dynamic hasWasUnseen;
@property(nonatomic) _Bool isLocal; // @dynamic isLocal;
@property(copy, nonatomic) NSString *promoOfferId; // @dynamic promoOfferId;
@property(nonatomic) int rationaleType; // @dynamic rationaleType;
@property(nonatomic) int rowTapActionType; // @dynamic rowTapActionType;
@property(nonatomic) int snippetHash; // @dynamic snippetHash;
@property(nonatomic) int swipeActionType; // @dynamic swipeActionType;
@property(retain, nonatomic) BTLTags *tags; // @dynamic tags;
@property(copy, nonatomic) NSString *threadId; // @dynamic threadId;
@property(nonatomic) _Bool unreadMessages; // @dynamic unreadMessages;
@property(nonatomic) _Bool wasUnseen; // @dynamic wasUnseen;

@end

