//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JavaUtilConcurrentAbstractExecutorService.h"

#import "ComGoogleCommonUtilConcurrentListeningExecutorService-Protocol.h"

@class ComGoogleCommonUtilConcurrentRateLimiter, NSString;
@protocol ComGoogleCommonUtilConcurrentListeningScheduledExecutorService;

@interface ComGoogleCommonUtilConcurrentRateLimitingExecutorService : JavaUtilConcurrentAbstractExecutorService <ComGoogleCommonUtilConcurrentListeningExecutorService>
{
    id <ComGoogleCommonUtilConcurrentListeningScheduledExecutorService> delegate_;
    ComGoogleCommonUtilConcurrentRateLimiter *rateLimiter_;
    int permitsPerTask_;
}

- (void)dealloc;
- (_Bool)awaitTerminationWithLong:(long long)arg1 withJavaUtilConcurrentTimeUnit:(id)arg2;
- (id)shutdownNow;
- (void)shutdown;
- (_Bool)isTerminated;
- (_Bool)isShutdown;
- (void)executeWithJavaLangRunnable:(id)arg1;
- (id)submitWithJavaLangRunnable:(id)arg1;
- (id)submitWithJavaUtilConcurrentCallable:(id)arg1;
- (id)submitWithJavaLangRunnable:(id)arg1 withId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

