//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ComGoogleProtobufGeneratedMessage_ExtendableMessageOrBuilder-Protocol.h"

@class ComGoogleProtobufDescriptorProtos_FieldOptions_CType, ComGoogleProtobufDescriptorProtos_FieldOptions_JSType, ComGoogleProtobufDescriptorProtos_FieldOptions_UpgradedOption, ComGoogleProtobufDescriptorProtos_UninterpretedOption;
@protocol JavaUtilList;

@protocol ComGoogleProtobufDescriptorProtos_FieldOptionsOrBuilder <ComGoogleProtobufGeneratedMessage_ExtendableMessageOrBuilder>
- (ComGoogleProtobufDescriptorProtos_UninterpretedOption *)getUninterpretedOptionWithInt:(int)arg1;
- (id <JavaUtilList>)getUninterpretedOptionList;
- (int)getUninterpretedOptionCount;
- (_Bool)getCcOpenEnum;
- (_Bool)hasCcOpenEnum;
- (_Bool)getEnforceUtf8;
- (_Bool)hasEnforceUtf8;
- (_Bool)getDeprecatedRawMessage;
- (_Bool)hasDeprecatedRawMessage;
- (ComGoogleProtobufDescriptorProtos_FieldOptions_UpgradedOption *)getUpgradedOptionWithInt:(int)arg1;
- (id <JavaUtilList>)getUpgradedOptionList;
- (int)getUpgradedOptionCount;
- (_Bool)getWeak;
- (_Bool)hasWeak;
- (_Bool)getDeprecated;
- (_Bool)hasDeprecated;
- (_Bool)getLazy;
- (_Bool)hasLazy;
- (ComGoogleProtobufDescriptorProtos_FieldOptions_JSType *)getJstype;
- (_Bool)hasJstype;
- (_Bool)getPacked;
- (_Bool)hasPacked;
- (ComGoogleProtobufDescriptorProtos_FieldOptions_CType *)getCtype;
- (_Bool)hasCtype;
@end

