//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ComGoogleCommonCollectMaps_Values.h"

@protocol ComGoogleCommonBasePredicate, JavaUtilMap;

@interface ComGoogleCommonCollectMaps_FilteredMapValues : ComGoogleCommonCollectMaps_Values
{
    id <JavaUtilMap> unfiltered_;
    id <ComGoogleCommonBasePredicate> predicate_;
}

- (void)dealloc;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_58648341 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)toArray;
- (_Bool)retainAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeWithId:(id)arg1;

@end

