//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DYNDMSupplementalRenderDelegate-Protocol.h"
#import "DYNStreamBehavior-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;
@protocol DYNSharedLayerService, DYNStream;

@interface DYNCMLEventBehavior : NSObject <DYNDMSupplementalRenderDelegate, DYNStreamBehavior>
{
    NSMutableArray *_cmlCardTimerMessageIDs;
    NSMutableArray *_cmlCardTimerMessageLastUpdatedTimes;
    NSMutableArray *_cmlCardTimerFireTimes;
    NSMutableDictionary *_messageIDToLastUpdatedTime;
    NSMutableDictionary *_messageIDToLocalVersion;
    id <DYNSharedLayerService> _sharedLayerService;
    id <DYNStream> _stream;
}

- (void).cxx_destruct;
- (void)incrementLocalVersion:(id)arg1;
- (void)messageSizeUpdatedNotification:(id)arg1;
- (_Bool)shouldUpdateObjectToErrorState:(id)arg1 withMessageID:(id)arg2 lastUpdatedTime:(long long)arg3;
- (_Bool)updateMessageWithAttachmentToErrorStateWithMessageID:(id)arg1 lastUpdatedTime:(long long)arg2 withModel:(id)arg3;
- (void)cmlCardTimerFireWithStream:(id)arg1 withState:(id)arg2;
- (void)processObjectStateWithObject:(id)arg1 messageID:(id)arg2 lastUpdatedTime:(long long)arg3;
- (void)processMessageWithAttachment:(id)arg1;
- (void)processObject:(id)arg1;
- (id)modelAfterRemovingObjectsFromModel:(id)arg1 withState:(id)arg2;
- (id)modelAfterProcessingObjectsInModel:(id)arg1 withState:(id)arg2;
- (id)modelAfterInsertingObjectsIntoModel:(id)arg1 withState:(id)arg2;
- (void)messageContentViewTappedButtonInCMLCardForMessage:(id)arg1 formAction:(id)arg2 inStream:(id)arg3;
- (void)handleEventsInStream:(id)arg1 withState:(id)arg2 oldState:(id)arg3;
- (void)finalizeWithStreamState:(id)arg1;
- (void)initializeWithStream:(id)arg1 state:(id)arg2;
- (id)initWithAccountID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

