//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DYNMessageContentView.h"

#import "DYNGsuiteIntegrationCardRendererDelegate-Protocol.h"

@class GMDCTypographyScheme, GOOIndeterminateProgressBar, NSString, UIView;
@protocol DYNCMLComponent, DYNExperimentsService, DYNGsuiteIntegrationCardRenderer, DYNMessageWithGsuiteAnnotationContentViewDelegate, GILInteractionService;

@interface DYNMessageWithGsuiteAnnotationContentView : DYNMessageContentView <DYNGsuiteIntegrationCardRendererDelegate>
{
    id <DYNCMLComponent> _cmlComponent;
    UIView *_spacingView;
    GOOIndeterminateProgressBar *_progressBar;
    id <DYNGsuiteIntegrationCardRenderer> _cardRenderer;
    id <GILInteractionService> _interactionLogger;
    id <DYNExperimentsService> _experimentsService;
    GMDCTypographyScheme *_typographyScheme;
    id <DYNMessageWithGsuiteAnnotationContentViewDelegate> _gsuiteIntegrationDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <DYNMessageWithGsuiteAnnotationContentViewDelegate> gsuiteIntegrationDelegate; // @synthesize gsuiteIntegrationDelegate=_gsuiteIntegrationDelegate;
- (void)performAccessibilityTapCMLComponent;
- (id)accessibilityCustomAction;
- (void)removeCMLComponent;
- (void)addCMLComponent;
- (void)createCMLComponentWithObject:(id)arg1;
- (void)setLoadingIndicatorVisible:(_Bool)arg1;
- (id)castedObject;
- (id)subclassAccessibilityCustomActions;
- (_Bool)subclassAccessibilityCustomActionsShouldBeListedFirst;
- (id)subclassAccessibilityHint;
- (id)subclassAccessibilitySpokenMessageText;
- (void)updateViewWithObject:(id)arg1;
- (void)fallbackCardDidTapUpdateButton;
- (void)calendarEventCardDidTapWithCalendarEventID:(id)arg1;
- (_Bool)calendarEventCardAllowTaps;
- (_Bool)calendarEventCardAllowRendering;
- (void)tasksCardDidTapWithTaskID:(id)arg1;
- (_Bool)tasksCardAllowTaps;
@property(readonly, nonatomic) long long hostFontSize;
@property(readonly, nonatomic) int hostTheme;
@property(readonly, nonatomic) int hostName;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

