//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppAndExtensionsFramework/GPBMessage.h>

@class DYNOVEGroup_InteractionMetadata;

@interface DYNOVEGroup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasInteractionMetadata; // @dynamic hasInteractionMetadata;
@property(retain, nonatomic) DYNOVEGroup_InteractionMetadata *interactionMetadata; // @dynamic interactionMetadata;

@end

