//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class DYNTimerObject, DYNUploader, NSArray, NSString, NSURL, UIImage;
@protocol DYNAnnotationProtocol, DYNSharedLayerService, GIPAccountID;

@interface DYNPostboxContent : NSObject <NSCopying>
{
    id <GIPAccountID> _accountID;
    id <DYNSharedLayerService> _sharedLayerService;
    NSString *_text;
    id <DYNAnnotationProtocol> _chipAnnotation;
    NSURL *_videoURL;
    UIImage *_thumbnailImage;
    DYNUploader *_uploader;
    NSArray *_previewAnnotations;
    NSString *_autocompleteQuery;
    DYNTimerObject *_timerObject;
    long long _driveFilesCount;
}

- (void).cxx_destruct;
@property(nonatomic) long long driveFilesCount; // @synthesize driveFilesCount=_driveFilesCount;
@property(retain, nonatomic) DYNTimerObject *timerObject; // @synthesize timerObject=_timerObject;
@property(retain, nonatomic) NSString *autocompleteQuery; // @synthesize autocompleteQuery=_autocompleteQuery;
@property(retain, nonatomic) NSArray *previewAnnotations; // @synthesize previewAnnotations=_previewAnnotations;
@property(retain, nonatomic) DYNUploader *uploader; // @synthesize uploader=_uploader;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(retain, nonatomic) id <DYNAnnotationProtocol> chipAnnotation; // @synthesize chipAnnotation=_chipAnnotation;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (id)annotationsAdjustedForTrimmedMessage:(_Bool)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)textContainsVoiceProcessingSpinner;
- (_Bool)isEmptyIncludingVerifiedAnnotations:(id)arg1;
- (_Bool)isEmpty;
- (id)trimmedText;
- (id)annotationForChip;
- (id)nonMentionAnnotations;
- (id)mentionAnnotations;
- (id)finalAnnotationsForTrimmedMessage;
- (id)annotations;
- (id)initWithAccountID:(id)arg1 message:(id)arg2;
- (id)initWithAccountID:(id)arg1 text:(id)arg2 chipAnnotation:(id)arg3 previewAnnotations:(id)arg4;

@end

