//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GBTAdsBodyHandlerDelegate-Protocol.h"
#import "GBTWebViewDelegate-Protocol.h"
#import "GBTWebViewScrollableDelegate-Protocol.h"
#import "ItemDetailViewInterface-Protocol.h"

@class GBTWKWebView, NSString, UIScrollView, WebViewScrollableAdaptor;
@protocol GBTAdBodySizingDelegate, GBTAdsBodyDetailViewDelegate, GBTClient, GBTLeadgenAdInterfaceDelegate, GBTSmartMailInteractionSupport, GBTWebViewScrollable, ItemDetailViewDataSource, ItemDetailViewDelegate, JBTAd;

@interface GBTAdsBodyDetailView : UIView <GBTWebViewDelegate, GBTWebViewScrollableDelegate, GBTAdsBodyHandlerDelegate, ItemDetailViewInterface>
{
    id <GBTClient> _client;
    GBTWKWebView *_adBody;
    id <GBTWebViewScrollable> _webViewScrollable;
    _Bool _isOneClickAd;
    id <GBTAdBodySizingDelegate> _adBodySizingDelegate;
    id <GBTAdsBodyDetailViewDelegate> _adsBodyDetailViewDelegate;
    id <GBTLeadgenAdInterfaceDelegate> _leadgenAdInterfaceDelegate;
    id <GBTSmartMailInteractionSupport> _smartMailDelegate;
    WebViewScrollableAdaptor *_webViewAdapter;
    id <JBTAd> _ad;
    id <ItemDetailViewDataSource> _detailViewDataSource;
    id <ItemDetailViewDelegate> _detailViewDelegate;
}

+ (_Bool)isClickToCall:(id)arg1;
+ (_Bool)hasDataParam:(id)arg1;
+ (id)adBodyHtmlWithStylesheetBuilder:(id)arg1 restrictorClass:(id)arg2;
+ (id)urlForTmpCopyOfFile:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak id <ItemDetailViewDelegate> detailViewDelegate; // @synthesize detailViewDelegate=_detailViewDelegate;
@property(nonatomic) __weak id <ItemDetailViewDataSource> detailViewDataSource; // @synthesize detailViewDataSource=_detailViewDataSource;
@property(retain, nonatomic) id <JBTAd> ad; // @synthesize ad=_ad;
@property(readonly, nonatomic) WebViewScrollableAdaptor *webViewAdapter; // @synthesize webViewAdapter=_webViewAdapter;
@property(nonatomic) __weak id <GBTSmartMailInteractionSupport> smartMailDelegate; // @synthesize smartMailDelegate=_smartMailDelegate;
@property(nonatomic) __weak id <GBTLeadgenAdInterfaceDelegate> leadgenAdInterfaceDelegate; // @synthesize leadgenAdInterfaceDelegate=_leadgenAdInterfaceDelegate;
@property(nonatomic) __weak id <GBTAdsBodyDetailViewDelegate> adsBodyDetailViewDelegate; // @synthesize adsBodyDetailViewDelegate=_adsBodyDetailViewDelegate;
@property(nonatomic) __weak id <GBTAdBodySizingDelegate> adBodySizingDelegate; // @synthesize adBodySizingDelegate=_adBodySizingDelegate;
@property(readonly, nonatomic) _Bool isOneClickAd; // @synthesize isOneClickAd=_isOneClickAd;
- (id)leadgenUIInit;
- (void)handleClickToCallAlertWithURL:(id)arg1;
- (void)showClickToCallAlertWithURL:(id)arg1;
- (void)adjustAdContentToFitScreenWidth;
- (double)viewportWidth;
- (void)injectAdScripts:(id)arg1;
- (id)scrollableForSubview:(id)arg1;
- (void)detailViewToolbarEndsAtOffset:(double)arg1;
@property(readonly, nonatomic) long long keyboardDismissMode;
@property(readonly, nonatomic) _Bool hasFixedHeader;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)webViewScrollableDidChangeHeight:(id)arg1 zooming:(_Bool)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)openAdClickURLWithoutAddingParameters:(id)arg1;
- (void)openAdClickURL:(id)arg1;
- (void)loadWebViewWithTwoClickAd:(id)arg1;
- (void)failToLoadWebViewWithOneClickAd:(id)arg1;
- (void)loadWebViewWithOneClickAd:(id)arg1 url:(id)arg2;
- (void)loadWebViewWithOneClickAd:(id)arg1;
- (id)leadgenJS;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)constrainSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 client:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

