//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTLRObject.h"

@class NSNumber, NSString;

@interface GTLRGmail_FilterCriteria : GTLRObject
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *excludeChats; // @dynamic excludeChats;
@property(copy, nonatomic) NSString *from; // @dynamic from;
@property(retain, nonatomic) NSNumber *hasAttachment; // @dynamic hasAttachment;
@property(copy, nonatomic) NSString *negatedQuery; // @dynamic negatedQuery;
@property(copy, nonatomic) NSString *query; // @dynamic query;
@property(retain, nonatomic) NSNumber *size; // @dynamic size;
@property(copy, nonatomic) NSString *sizeComparison; // @dynamic sizeComparison;
@property(copy, nonatomic) NSString *subject; // @dynamic subject;
@property(copy, nonatomic) NSString *to; // @dynamic to;
@end

