//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GILClientVisualElement, NSString;
@protocol GILVisualElementParams;

@protocol HUBSearchVisualElementLoggerService <NSObject>
- (void)logTapOnClientVisualElement:(GILClientVisualElement *)arg1 tabType:(int)arg2;
- (void)logClientVisualElement:(GILClientVisualElement *)arg1 withSearchQuery:(NSString *)arg2 tabType:(int)arg3;
- (id <GILVisualElementParams>)visualElementParamsWithVEID:(int)arg1 cellID:(unsigned long long)arg2 tabType:(int)arg3;
@end

