//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JavaUtilConcurrentCountDownLatch_Sync;

@interface JavaUtilConcurrentCountDownLatch : NSObject
{
    JavaUtilConcurrentCountDownLatch_Sync *sync_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)description;
- (long long)getCount;
- (void)countDown;
- (_Bool)awaitWithLong:(long long)arg1 withJavaUtilConcurrentTimeUnit:(id)arg2;
- (void)await;
- (id)initWithInt:(int)arg1;

@end

