//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JavaObject-Protocol.h"

@protocol JavaUtilFunctionIntPredicate;

@protocol JavaUtilFunctionIntPredicate <JavaObject>
- (id <JavaUtilFunctionIntPredicate>)or__WithJavaUtilFunctionIntPredicate:(id <JavaUtilFunctionIntPredicate>)arg1;
- (id <JavaUtilFunctionIntPredicate>)negate;
- (id <JavaUtilFunctionIntPredicate>)and__WithJavaUtilFunctionIntPredicate:(id <JavaUtilFunctionIntPredicate>)arg1;
- (_Bool)testWithInt:(int)arg1;
@end

