//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JavaUtilConcurrentLinkedTransferQueue_Node : NSObject
{
    _Bool isData_;
    unsigned long long item_;
    unsigned long long next_;
    unsigned long long waiter_;
}

+ (void)initialize;
+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (void)__javaClone:(id)arg1;
- (_Bool)tryMatchData;
- (_Bool)cannotPrecedeWithBoolean:(_Bool)arg1;
- (_Bool)isUnmatchedRequest;
- (_Bool)isMatched;
- (void)forgetContents;
- (void)forgetNext;
- (id)initWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (_Bool)casItemWithId:(id)arg1 withId:(id)arg2;
- (_Bool)casNextWithJavaUtilConcurrentLinkedTransferQueue_Node:(id)arg1 withJavaUtilConcurrentLinkedTransferQueue_Node:(id)arg2;

@end

