//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "JBTBarcodeAction-Protocol.h"

@class ComGoogleCommonCollectImmutableList, JBTBarcodeAction_BarcodeType, JBTIActionsHelper, JBTISmartMailComponentContextImpl, JCSAssignedId, NSString;
@protocol JBTRichText;

@interface JBTIBarcodeActionImpl : NSObject <JBTBarcodeAction>
{
    id <JBTRichText> title_;
    id <JBTRichText> expandedTitle_;
    id <JBTRichText> caption_;
    NSString *barcodeText_;
    JBTBarcodeAction_BarcodeType *barcodeType_;
    JBTISmartMailComponentContextImpl *smartMailContext_;
    JCSAssignedId *assignedId_;
    ComGoogleCommonCollectImmutableList *barcodes_;
    JBTIActionsHelper *actionsHelper_;
}

+ (void)initialize;
- (void)dealloc;
- (void)recordClick;
- (id)getBarcodes;
- (id)getExpandedTitle;
- (id)getTitle;
- (id)getCaption;
- (id)getBarcodeType;
- (id)getBarcodeText;
- (id)getLoggingId;
- (id)getActionType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

