//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SunSecurityX509X509AttributeName : NSObject
{
    NSString *prefix_;
    NSString *suffix_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)getSuffix;
- (id)getPrefix;
- (id)initWithNSString:(id)arg1;

@end

