//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CacheableHeightForNugget-Protocol.h"
#import "ContactHandler-Protocol.h"
#import "GBTBadgeSupport-Protocol.h"
#import "GBTHighlightedSupport-Protocol.h"
#import "GBTSelectSupport-Protocol.h"
#import "GBTSmartMailInteractionSupport-Protocol.h"
#import "GBTThreadSummaryAttachmentsViewDelegate-Protocol.h"
#import "GBTThreadSummaryViewLayoutDelegate-Protocol.h"
#import "GBTThumbnailSupport-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UpdateableWithNugget-Protocol.h"

@class CardCarouselView, GBTBadgeView, GBTCellToggleButton, GBTNetworkImageView, GBTNugget, GBTSmartMailInteractionForwarder, GBTSmartMailSimpleSnippetView, GBTSpinnerAvatarView, GBTStarButton, GBTThreadSummaryAttachmentsView, NSArray, NSMutableArray, NSMutableDictionary, NSString, ThreadSummaryViewLayout, UIImageView, UILabel;
@protocol GBTSmartMailInteractionSupport, HUBColorScheme, JBTConversation, ThreadSummaryViewDelegate;

@interface ThreadSummaryView : UIView <GBTThreadSummaryAttachmentsViewDelegate, GBTThreadSummaryViewLayoutDelegate, UIGestureRecognizerDelegate, GBTSmartMailInteractionSupport, GBTBadgeSupport, CacheableHeightForNugget, ContactHandler, GBTHighlightedSupport, GBTSelectSupport, GBTThumbnailSupport, UpdateableWithNugget>
{
    NSString *_accessibilityLabel;
    NSArray *_accessibilityCustomActions;
    UIImageView *_attachmentIndicator;
    GBTSpinnerAvatarView *_avatarView;
    GBTCellToggleButton *_cellToggle;
    UILabel *_countLabel;
    UILabel *_dateLabel;
    _Bool _focused;
    GBTSmartMailInteractionForwarder *_forwarder;
    _Bool _forceHideSnooze;
    _Bool _highlighted;
    UILabel *_hyphenLabel;
    UIImageView *_importanceIndicator;
    _Bool _isDraft;
    NSMutableArray *_labelViews;
    GBTBadgeView *_promoCouponBadge;
    UILabel *_promoCouponLabel;
    GBTBadgeView *_promoDiscountBadge;
    GBTNetworkImageView *_promoMerchantImage;
    UIImageView *_scheduledIndicator;
    _Bool _selected;
    UILabel *_contactsLabel;
    UILabel *_snippetLabel;
    UIImageView *_snooze;
    UILabel *_snoozeReturnSnippet;
    GBTStarButton *_starButton;
    UILabel *_subjectLabel;
    NSMutableDictionary *_subviewsForLayout;
    GBTSmartMailSimpleSnippetView *_taskView;
    UIImageView *_trash;
    UIImageView *_responseIndicator;
    GBTThreadSummaryAttachmentsView *_threadSummaryAttachmentsView;
    id <HUBColorScheme> _colorScheme;
    _Bool _showsDate;
    _Bool _showsToggleButton;
    _Bool _showsStarButton;
    _Bool _showsScheduledDate;
    _Bool _showsRecipients;
    CardCarouselView *_cardCarouselView;
    id <ThreadSummaryViewDelegate> _delegate;
    GBTNugget *_nugget;
}

+ (_Bool)requiresCacheForDifferentWidthsWithNugget:(id)arg1;
+ (_Bool)hasCacheableHeightForNugget:(id)arg1;
+ (id)nearestMailViewControllerContainingView:(id)arg1;
+ (long long)maxSnippetLength;
+ (double)heightWithNugget:(id)arg1 width:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GBTNugget *nugget; // @synthesize nugget=_nugget;
@property(nonatomic) _Bool showsRecipients; // @synthesize showsRecipients=_showsRecipients;
@property(nonatomic) _Bool showsScheduledDate; // @synthesize showsScheduledDate=_showsScheduledDate;
@property(nonatomic, getter=isStarButtonShown) _Bool showsStarButton; // @synthesize showsStarButton=_showsStarButton;
@property(nonatomic, getter=isToggleButtonShown) _Bool showsToggleButton; // @synthesize showsToggleButton=_showsToggleButton;
@property(nonatomic, getter=isDateShown) _Bool showsDate; // @synthesize showsDate=_showsDate;
@property(nonatomic) __weak id <ThreadSummaryViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) CardCarouselView *cardCarouselView; // @synthesize cardCarouselView=_cardCarouselView;
- (void)updateAvatar;
- (void)view:(id)arg1 didSelectSuggestedSnoozeConfig:(id)arg2 forItem:(id)arg3;
- (int)avatarTapActionType;
- (struct CGRect)selectFrame;
- (void)setMultiselectEnabled:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setFocused:(_Bool)arg1;
- (void)toggleCell;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)forceHideSnoozeBadge:(_Bool)arg1;
- (void)didUpdateAvatarContactForThreadSummaryViewLayout:(id)arg1;
- (void)attachmentsView:(id)arg1 didSelectChipView:(id)arg2 atIndex:(long long)arg3;
- (void)updateBackgroundColorAnimated:(_Bool)arg1;
- (void)starTapped;
- (id)hiddenImageViewForIcon:(id)arg1 imageColor:(id)arg2;
- (void)maybeAddSnoozeViews;
- (void)createGmailSubviews;
- (void)createSubviews;
- (id)createDefaultLabelWithColor:(id)arg1;
- (id)accessibilityCustomActions;
- (id)accessibilityLabel;
- (id)accessibilityIdentifier;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)updateWithNugget:(id)arg1 parentVisualElement:(id)arg2;
@property(readonly, nonatomic) ThreadSummaryViewLayout *threadSummaryViewLayout;
@property(nonatomic) __weak id <GBTSmartMailInteractionSupport> smartMailDelegate;
@property(readonly, nonatomic) id <JBTConversation> conversation;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

