//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DetailViewContext.h"

#import "SwipeableDetailViewContext-Protocol.h"

@class NSString, UINavigationController;
@protocol DetailSwipeControllerDelegate, JBTClientInteractionContext, JBTConversationMessageList, SwipeableDetailViewControllerListener;

@interface ThreadDetailViewContext : DetailViewContext <SwipeableDetailViewContext>
{
    _Bool _preview;
    id <DetailSwipeControllerDelegate> detailSwipeControllerDelegate;
    id <JBTConversationMessageList> _messageList;
    long long _mainSmartmailIndex;
    NSString *_actionIdentifier;
    id <JBTClientInteractionContext> _interactionContext;
    CDUnknownBlockType _closeHandler;
    id <SwipeableDetailViewControllerListener> _listener;
    UINavigationController *_navController;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool preview; // @synthesize preview=_preview;
@property(retain, nonatomic) UINavigationController *navController; // @synthesize navController=_navController;
@property(retain, nonatomic) id <SwipeableDetailViewControllerListener> listener; // @synthesize listener=_listener;
@property(copy, nonatomic) CDUnknownBlockType closeHandler; // @synthesize closeHandler=_closeHandler;
@property(retain, nonatomic) id <JBTClientInteractionContext> interactionContext; // @synthesize interactionContext=_interactionContext;
@property(copy, nonatomic) NSString *actionIdentifier; // @synthesize actionIdentifier=_actionIdentifier;
@property(nonatomic) long long mainSmartmailIndex; // @synthesize mainSmartmailIndex=_mainSmartmailIndex;
@property(readonly, nonatomic) id <JBTConversationMessageList> messageList; // @synthesize messageList=_messageList;
@property(nonatomic) __weak id <DetailSwipeControllerDelegate> detailSwipeControllerDelegate; // @synthesize detailSwipeControllerDelegate;
- (id)initWithMessageList:(id)arg1;
- (id)initWithDetailViewType:(unsigned long long)arg1;

@end

