//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppAndExtensionsFramework/GPBMessage.h>

@class GPBEnumArray, NSString;

@interface VADPBAddressDataWithErrors_DependentLocalityWithErrors : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *dependentLocality; // @dynamic dependentLocality;
@property(retain, nonatomic) GPBEnumArray *dependentLocalityErrorsArray; // @dynamic dependentLocalityErrorsArray;
@property(readonly, nonatomic) unsigned long long dependentLocalityErrorsArray_Count; // @dynamic dependentLocalityErrorsArray_Count;
@property(nonatomic) _Bool hasDependentLocality; // @dynamic hasDependentLocality;

@end

