//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol ELMInteractionLogger <NSObject>
-     // Error parsing type: v28@0:8^{LoggingNode=^^?{InternalMetadataWithArenaLite=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>=Ai}}^{LoggingProperties}ii}16i24, name: logGestureForNode:gestureType:
- (void)updateVisibilityType:(int)arg1 forNodes:(Span_b02e7da6)arg2;
- (void)didAttachNodes:(Span_b02e7da6)arg1;
@end

