//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol JavaUtilMap;

@interface ComGoogleApiClientUtilArrayValueMap : NSObject
{
    id <JavaUtilMap> keyMap_;
    id <JavaUtilMap> fieldMap_;
    id destination_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (void)putWithNSString:(id)arg1 withIOSClass:(id)arg2 withId:(id)arg3;
- (void)putWithJavaLangReflectField:(id)arg1 withIOSClass:(id)arg2 withId:(id)arg3;
- (void)setValues;
- (id)initWithId:(id)arg1;

@end

