//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ComGoogleCommonCollectAndroidAccessToCompactDataStructures : NSObject
{
}

+ (id)newCompactLinkedHashSetWithInt:(int)arg1;
+ (id)newCompactLinkedHashSetWithNSObjectArray:(id)arg1;
+ (id)newCompactLinkedHashSetWithJavaUtilCollection:(id)arg1;
+ (id)newCompactLinkedHashSet;
+ (id)newCompactLinkedHashMapWithInt:(int)arg1;
+ (id)newCompactLinkedHashMap;
+ (id)newCompactHashSetWithInt:(int)arg1;
+ (id)newCompactHashSetWithNSObjectArray:(id)arg1;
+ (id)newCompactHashSetWithJavaUtilCollection:(id)arg1;
+ (id)newCompactHashSet;
+ (id)newCompactHashMapWithInt:(int)arg1;
+ (id)newCompactHashMap;

@end

