//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JavaUtilAbstractList.h"

@protocol JavaLangCharSequence;

@interface ComGoogleCommonCollectLists_CharSequenceAsList : JavaUtilAbstractList
{
    id <JavaLangCharSequence> sequence_;
}

- (void)dealloc;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_58648341 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (int)size;
- (id)getWithInt:(int)arg1;

@end

