//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ComGoogleCommonCacheCacheLoader.h"

@class ComGoogleCommonCacheAsyncCacheLoader, ComGoogleCommonCacheShimAsyncCache_CacheHolder, JavaLangThreadLocal;
@protocol ComGoogleCommonCacheAbstractCache_StatsCounter, ComGoogleCommonCacheShimAsyncCache_StatsFixer;

@interface ComGoogleCommonCacheShimAsyncCache_5 : ComGoogleCommonCacheCacheLoader
{
    ComGoogleCommonCacheShimAsyncCache_CacheHolder *val$holder_;
    ComGoogleCommonCacheAsyncCacheLoader *val$loader_;
    JavaLangThreadLocal *val$batch_;
    id <ComGoogleCommonCacheAbstractCache_StatsCounter> val$statsCounter_;
    id <ComGoogleCommonCacheShimAsyncCache_StatsFixer> val$statsFixer_;
}

- (void)dealloc;
- (id)reloadWithId:(id)arg1 withId:(id)arg2;
- (id)load__WithId:(id)arg1;

@end

