//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ComGoogleApiClientJsonGenericJson.h"

@class GASMimedcontentJson, GASPost_DiscussionsObject_Replies, NSString;

@interface GASPost_DiscussionsObject : ComGoogleApiClientJsonGenericJson
{
    GASMimedcontentJson *content_;
    NSString *objectType_;
    GASMimedcontentJson *originalContent_;
    GASPost_DiscussionsObject_Replies *replies_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)java_clone;
- (id)setWithNSString:(id)arg1 withId:(id)arg2;
- (id)setRepliesWithGASPost_DiscussionsObject_Replies:(id)arg1;
- (id)getReplies;
- (id)setOriginalContentWithGASMimedcontentJson:(id)arg1;
- (id)getOriginalContent;
- (id)setObjectTypeWithNSString:(id)arg1;
- (id)getObjectType;
- (id)setContentWithGASMimedcontentJson:(id)arg1;
- (id)getContent;
- (id)init;

@end

