//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class GDKAvatarView, UILabel;

@interface GDANotificationsHeadingView : UIView
{
    GDKAvatarView *_avatarImageView;
    UILabel *_actionText;
    UILabel *_headingLabel;
    UILabel *_timeLabel;
}

+ (double)heightForViewWithHeading:(id)arg1 timestamp:(id)arg2 width:(double)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *headingLabel; // @synthesize headingLabel=_headingLabel;
@property(retain, nonatomic) UILabel *actionText; // @synthesize actionText=_actionText;
@property(retain, nonatomic) GDKAvatarView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void)prepareForReuse;
- (void)updateViewWithName:(id)arg1 localID:(id)arg2 image:(id)arg3 heading:(id)arg4 actionText:(id)arg5 timestamp:(id)arg6;
- (void)updateAvatarWithName:(id)arg1 localID:(id)arg2 image:(id)arg3 fadeInImage:(_Bool)arg4;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

