//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDKAutoSizable-Protocol.h"
#import "GDKMenuThemableCVO-Protocol.h"
#import "GDKMenuViewObject-Protocol.h"

@class GDKTheme, NSString;
@protocol GDKAutoSizablePresenter;

@interface GDKMenuNavigationViewControllerCVO : NSObject <GDKMenuThemableCVO, GDKMenuViewObject, GDKAutoSizable>
{
    GDKTheme *_theme;
    id <GDKAutoSizablePresenter> _autoSizablePresenter;
    NSString *_title;
    CDUnknownBlockType _navigationBlock;
}

+ (id)objectWithTitle:(id)arg1 theme:(id)arg2 navigationBlock:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CDUnknownBlockType navigationBlock; // @synthesize navigationBlock=_navigationBlock;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) __weak id <GDKAutoSizablePresenter> autoSizablePresenter; // @synthesize autoSizablePresenter=_autoSizablePresenter;
@property(readonly, nonatomic) GDKTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) unsigned long long heightCacheHash;
@property(readonly, nonatomic) NSString *heightCacheKey;
- (id)nonBindingContentView;
- (Class)contentViewClass;
- (void)presentViewControllerFromNavigationVC:(id)arg1;
- (id)initWithTitle:(id)arg1 theme:(id)arg2 navigationBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) unsigned long long elementKind;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

