//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <drive_extension_framework/GPBMessage.h>

@class GUNSRAndroidRenderInfo, GUNSREmailRenderInfo, GUNSRGmsCoreRenderInfo, GUNSRIosRenderInfo, GUNSRSmsRenderInfo;

@interface GUNSRDeliveryMethodSpecificData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GUNSRAndroidRenderInfo *androidRenderInfo; // @dynamic androidRenderInfo;
@property(retain, nonatomic) GUNSREmailRenderInfo *emailRenderInfo; // @dynamic emailRenderInfo;
@property(retain, nonatomic) GUNSRGmsCoreRenderInfo *gmsCoreRenderInfo; // @dynamic gmsCoreRenderInfo;
@property(nonatomic) _Bool hasAndroidRenderInfo; // @dynamic hasAndroidRenderInfo;
@property(nonatomic) _Bool hasEmailRenderInfo; // @dynamic hasEmailRenderInfo;
@property(nonatomic) _Bool hasGmsCoreRenderInfo; // @dynamic hasGmsCoreRenderInfo;
@property(nonatomic) _Bool hasIosRenderInfo; // @dynamic hasIosRenderInfo;
@property(nonatomic) _Bool hasSmsRenderInfo; // @dynamic hasSmsRenderInfo;
@property(retain, nonatomic) GUNSRIosRenderInfo *iosRenderInfo; // @dynamic iosRenderInfo;
@property(retain, nonatomic) GUNSRSmsRenderInfo *smsRenderInfo; // @dynamic smsRenderInfo;

@end

