//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <drive_extension_framework/GPBMessage.h>

@class DlpContentRegion, NSString;

@interface MatchingDetectorDetail : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasMatchingDetectorId; // @dynamic hasMatchingDetectorId;
@property(nonatomic) _Bool hasMatchingDlpContentRegion; // @dynamic hasMatchingDlpContentRegion;
@property(copy, nonatomic) NSString *matchingDetectorId; // @dynamic matchingDetectorId;
@property(retain, nonatomic) DlpContentRegion *matchingDlpContentRegion; // @dynamic matchingDlpContentRegion;

@end

