//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <drive_extension_framework/GPBMessage.h>

@class GPBEnumArray, NSString, PHPCCropRectangle;

@interface PHPCPhotoData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PHPCCropRectangle *cropRectangle; // @dynamic cropRectangle;
@property(nonatomic) int cropSource; // @dynamic cropSource;
@property(nonatomic) int editPreference; // @dynamic editPreference;
@property(nonatomic) _Bool eligibleForAutoenhance; // @dynamic eligibleForAutoenhance;
@property(nonatomic) _Bool hasCropRectangle; // @dynamic hasCropRectangle;
@property(nonatomic) _Bool hasCropSource; // @dynamic hasCropSource;
@property(nonatomic) _Bool hasEditPreference; // @dynamic hasEditPreference;
@property(nonatomic) _Bool hasEligibleForAutoenhance; // @dynamic hasEligibleForAutoenhance;
@property(nonatomic) _Bool hasImageURL; // @dynamic hasImageURL;
@property(nonatomic) _Bool hasImageURLAspectRatio; // @dynamic hasImageURLAspectRatio;
@property(nonatomic) _Bool hasLocalDedupKey; // @dynamic hasLocalDedupKey;
@property(nonatomic) _Bool hasMediaKey; // @dynamic hasMediaKey;
@property(nonatomic) _Bool hasSalientRegion; // @dynamic hasSalientRegion;
@property(nonatomic) _Bool hasShared; // @dynamic hasShared;
@property(nonatomic) _Bool hasTimestampSeconds; // @dynamic hasTimestampSeconds;
@property(nonatomic) _Bool hasUnscaledHeight; // @dynamic hasUnscaledHeight;
@property(nonatomic) _Bool hasUnscaledWidth; // @dynamic hasUnscaledWidth;
@property(nonatomic) _Bool hasVersion; // @dynamic hasVersion;
@property(copy, nonatomic) NSString *imageURL; // @dynamic imageURL;
@property(nonatomic) float imageURLAspectRatio; // @dynamic imageURLAspectRatio;
@property(copy, nonatomic) NSString *localDedupKey; // @dynamic localDedupKey;
@property(copy, nonatomic) NSString *mediaKey; // @dynamic mediaKey;
@property(retain, nonatomic) GPBEnumArray *photoProblemArray; // @dynamic photoProblemArray;
@property(readonly, nonatomic) unsigned long long photoProblemArray_Count; // @dynamic photoProblemArray_Count;
@property(retain, nonatomic) PHPCCropRectangle *salientRegion; // @dynamic salientRegion;
@property(nonatomic) _Bool shared; // @dynamic shared;
@property(nonatomic) long long timestampSeconds; // @dynamic timestampSeconds;
@property(nonatomic) long long unscaledHeight; // @dynamic unscaledHeight;
@property(nonatomic) long long unscaledWidth; // @dynamic unscaledWidth;
@property(nonatomic) long long version; // @dynamic version;

@end

