//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <drive_extension_framework/GPBMessage.h>

@class PHPCClientUnsupported, PHPCPhotoBookLayout;

@interface SFPDPhotosGenerateGuidedCreationsResponse_BookPreviewOutput : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PHPCClientUnsupported *clientUnsupported; // @dynamic clientUnsupported;
@property(nonatomic) _Bool hasClientUnsupported; // @dynamic hasClientUnsupported;
@property(nonatomic) _Bool hasPhotoBookLayout; // @dynamic hasPhotoBookLayout;
@property(retain, nonatomic) PHPCPhotoBookLayout *photoBookLayout; // @dynamic photoBookLayout;

@end

