//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ACCPanelViewProtocol-Protocol.h"

@class AWEScrollBarChartView, NSString, UIButton, UILabel;

@interface AWEAudioClipView : UIView <ACCPanelViewProtocol>
{
    UIButton *_clipMusicDoneBtn;
    UIButton *_audioStartTimeIndicatorBtn;
    AWEScrollBarChartView *_audioBarView;
    UILabel *_tipLabel;
    long long _style;
}

- (void).cxx_destruct;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) AWEScrollBarChartView *audioBarView; // @synthesize audioBarView=_audioBarView;
@property(retain, nonatomic) UIButton *audioStartTimeIndicatorBtn; // @synthesize audioStartTimeIndicatorBtn=_audioStartTimeIndicatorBtn;
@property(retain, nonatomic) UIButton *clipMusicDoneBtn; // @synthesize clipMusicDoneBtn=_clipMusicDoneBtn;
- (void *)identifier;
- (double)panelViewHeight;
- (void)shouldUseBarView:(_Bool)arg1;
- (void)buildSubviews;
- (id)init;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

