//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AWECoverTextPackageView, AWECoverTextPlainTextView, AWECoverTextStoryTextView;
@protocol AWECoverTextStickerProtocol;

@interface AWECoverTextStickerView : UIView
{
    double _currentScale;
    UIView<AWECoverTextStickerProtocol> *_currentView;
    double _fontScale;
    AWECoverTextStoryTextView *_storyView;
    AWECoverTextPackageView *_packageView;
    AWECoverTextPlainTextView *_plainTextView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AWECoverTextPlainTextView *plainTextView; // @synthesize plainTextView=_plainTextView;
@property(retain, nonatomic) AWECoverTextPackageView *packageView; // @synthesize packageView=_packageView;
@property(retain, nonatomic) AWECoverTextStoryTextView *storyView; // @synthesize storyView=_storyView;
@property(nonatomic) double fontScale; // @synthesize fontScale=_fontScale;
@property(retain, nonatomic) UIView<AWECoverTextStickerProtocol> *currentView; // @synthesize currentView=_currentView;
@property(nonatomic) double currentScale; // @synthesize currentScale=_currentScale;
- (id)viewWithModel:(id)arg1;
@property(readonly, nonatomic) AWECoverTextStoryTextView *storyTextView;
- (void)startEditModeWithModel:(id)arg1;
- (void)updateEditInfo:(id)arg1;
- (void)showPlaceHolder;
- (void)hiddenPlaceHolder;
- (void)setTransform:(struct CGAffineTransform)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 fontScale:(double)arg2;

@end

