//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface AWENewPublishMultiAnchorViewModel : NSObject
{
    _Bool _isCancelable;
    NSString *_title;
    NSArray *_iconImageURLList;
    NSString *_iconName;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isCancelable; // @synthesize isCancelable=_isCancelable;
@property(readonly, copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(readonly, copy, nonatomic) NSArray *iconImageURLList; // @synthesize iconImageURLList=_iconImageURLList;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)initWithTitle:(id)arg1 iconImageURLList:(id)arg2 alternativeIconName:(id)arg3 isCancelable:(_Bool)arg4;

@end

