//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AWERealNameVerifyManagerProtocol-Protocol.h"

@class NSString;

@interface AWERealNameVerifyManager : NSObject <AWERealNameVerifyManagerProtocol>
{
}

+ (id)_realNameVerifyUrlWithType:(long long)arg1;
+ (id)updateVerifyStatusURLString;
+ (void)_showRealNameDetailPage;
+ (void)setRealNameVerifyStatus:(unsigned long long)arg1;
+ (unsigned long long)realNameVerifyStatus;
+ (void)updateVerifyStatus:(CDUnknownBlockType)arg1;
+ (id)realNameVerifyUrlWithType:(long long)arg1;
+ (void)bindPhone;
+ (_Bool)checkIsPhoneBinded;
+ (void)showRealNameVerifyWithType:(long long)arg1 verifyDidSucceedBlock:(CDUnknownBlockType)arg2;
+ (void)showRealNameVerifyForECommerceWithVerifyDidSucceedBlock:(CDUnknownBlockType)arg1;
+ (void)showRealNameVerifyForECommerce;
+ (void)showRealNameVerifyNavForLive;
+ (void)showRealNameVerify;
+ (void)showRealNameDetailPage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

