//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AWEIMLCSManagerMessage-Protocol.h"

@class NSString;

@interface AWETimorConnectionManager : NSObject <AWEIMLCSManagerMessage>
{
}

+ (id)sharedManager;
- (void)aweim_onPushManagerConnectionStateChanged:(unsigned long long)arg1 url:(id)arg2;
- (void)handleDidEnterBackgroundNotification:(id)arg1;
- (void)handleWillEnterForegroundNotification:(id)arg1;
- (void)handleOnReceiveAWEPushServiceMsg:(id)arg1;
- (void)sendConnectionConnected;
- (void)handleUserStatusMsgWithServiceID:(int)arg1 methodID:(int)arg2 content:(id)arg3;
- (void)endUserStatusConnection;
- (void)startUserStatusConnection;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

