//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LynxUI.h"

@class NSMutableDictionary, NSString;

@interface BDXLynxSvgView : LynxUI
{
    _Bool _isLayoutDidFinish;
    NSString *_src;
    NSString *_content;
    NSMutableDictionary *_bdImageHolder;
}

+ (id)__lynx_prop_config__391;
+ (id)__lynx_prop_config__350;
+ (void)load;
- (void).cxx_destruct;
@property _Bool isLayoutDidFinish; // @synthesize isLayoutDidFinish=_isLayoutDidFinish;
@property(retain) NSMutableDictionary *bdImageHolder; // @synthesize bdImageHolder=_bdImageHolder;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *src; // @synthesize src=_src;
- (void)propsDidUpdate;
- (void)layoutDidFinished;
- (void)setContent:(id)arg1 requestReset:(_Bool)arg2;
- (void)setSrc:(id)arg1 requestReset:(_Bool)arg2;
- (id)createView;

@end

