//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HTSEventContext, IESLiveComponentContext, NSNumber;
@protocol IESLiveMTDiggReaction;

@protocol IESLiveMTDiggStoreAffairProtocol <NSObject>
@property(readonly, nonatomic) long long currentContinueCount;
@property(readonly, nonatomic) _Bool isDigging;
@property(retain, nonatomic) NSNumber *firstIndex;
@property(retain, nonatomic) HTSEventContext *eventContext;
@property(retain, nonatomic) IESLiveComponentContext *componentContext;
@property(nonatomic) __weak id <IESLiveMTDiggReaction> reaction;
- (void)diggClicked:(_Bool)arg1 touchPoint:(struct CGPoint)arg2 gapTime:(double)arg3;
- (_Bool)enableRoomDigg;
- (void)realUploadDiggMessageWithIndex:(NSNumber *)arg1 duration:(long long)arg2 diggcount:(long long)arg3;
@end

