//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface TTASendCodeRequestModel : NSObject
{
    _Bool _unbindExist;
    _Bool _isNeedMix;
    _Bool _checkRegister;
    NSString *_captcha;
    NSString *_mobile;
    long long _smsCodeType;
    NSString *_oldMbile;
    NSString *_ticket;
    NSString *_authToken;
    NSString *_unUseableMobileTickt;
    NSString *_verifyTicket;
    NSDictionary *_extraInfo;
}

@property(copy, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(copy, nonatomic) NSString *verifyTicket; // @synthesize verifyTicket=_verifyTicket;
@property(nonatomic) _Bool checkRegister; // @synthesize checkRegister=_checkRegister;
@property(copy, nonatomic) NSString *unUseableMobileTickt; // @synthesize unUseableMobileTickt=_unUseableMobileTickt;
@property(copy, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
@property(copy, nonatomic) NSString *ticket; // @synthesize ticket=_ticket;
@property(nonatomic) _Bool isNeedMix; // @synthesize isNeedMix=_isNeedMix;
@property(copy, nonatomic) NSString *oldMbile; // @synthesize oldMbile=_oldMbile;
@property(nonatomic) _Bool unbindExist; // @synthesize unbindExist=_unbindExist;
@property(nonatomic) long long smsCodeType; // @synthesize smsCodeType=_smsCodeType;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *captcha; // @synthesize captcha=_captcha;
- (void).cxx_destruct;
- (id)init;

@end

