//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, TTVideoEngineURLInfo;

@protocol TTVideoEngineDataSource <NSObject>

@optional
- (NSDictionary *)appInfo;
- (NSString *)cacheFilePathUsingMediaDataLoader:(NSString *)arg1 infoModel:(TTVideoEngineURLInfo *)arg2;
- (unsigned long long)networkType;
- (NSString *)apiForFetcher:(unsigned long long)arg1;
- (NSString *)apiForFetcher;
@end

