//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VKObject.h"

@class NSString, NSURL;

@interface VKShareLink : VKObject
{
    NSString *_title;
    NSURL *_link;
}

@property(copy, nonatomic) NSURL *link; // @synthesize link=_link;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 link:(id)arg2;

@end

