//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC5Authy25DeviceArchitectureBuilder : _TtCs12_SwiftObject
{
    // Error parsing type: , name: operatingSystem
    // Error parsing type: , name: osVersion
    // Error parsing type: , name: modelName
    // Error parsing type: , name: deviceType
    // Error parsing type: , name: deviceManufacturer
}

@end

