//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface Base32Decoder : NSObject
{
    NSData *charMapData_;
    char *charMap_;
    int reverseCharMap_[128];
    int shift_;
    int mask_;
    _Bool doPad_;
    BOOL paddingChar_;
    int padLen_;
}

- (void)ignoreCharacters:(id)arg1;
- (void)addDecodeSynonyms:(id)arg1;
- (id)decode:(id)arg1;
- (unsigned long long)getDecodedDataLengthFromEncoding:(id)arg1;
- (id)oldDecode:(id)arg1;
- (int)lcm:(int)arg1 b:(int)arg2;
- (id)init;

@end

