//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC53googlemac_iPhone_Home_Shared_Flux_Framework_Framework11WaitUITokenP33_8B5985DCBA9B96515308AC19428E196414ResourceHolder : _TtCs12_SwiftObject
{
    // Error parsing type: , name: renderer
    // Error parsing type: , name: queue
}

@end

