//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GIMLogsExternalApiEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *callingPackageName; // @dynamic callingPackageName;
@property(nonatomic) int eventType; // @dynamic eventType;
@property(nonatomic) _Bool isAuthorized; // @dynamic isAuthorized;
@property(copy, nonatomic) NSString *originalPackageName; // @dynamic originalPackageName;
@property(copy, nonatomic) NSString *sourceReferrer; // @dynamic sourceReferrer;

@end

