//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GIMLogsId;

@interface GIMLogsContactsAffinityAndReachability_ContactAffinityInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int affinityRank; // @dynamic affinityRank;
@property(nonatomic) double affinityScore; // @dynamic affinityScore;
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(retain, nonatomic) GIMLogsId *id_p; // @dynamic id_p;
@property(nonatomic) int modelVersion; // @dynamic modelVersion;
@property(nonatomic) _Bool prepopulatedAfterInvite; // @dynamic prepopulatedAfterInvite;
@property(nonatomic) _Bool prepopulatedAtRegistration; // @dynamic prepopulatedAtRegistration;
@property(nonatomic) int registrationState; // @dynamic registrationState;

@end

