//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GMSNetworkFetcherRequest-Protocol.h"

@class GMSDASHProtobufferRequest, NSString;
@protocol GMSDASHConnection;

@interface GMSDASHRequestWrapper : NSObject <GMSNetworkFetcherRequest>
{
    id <GMSDASHConnection> _dashConnection;
    GMSDASHProtobufferRequest *_dashRequest;
}

- (void).cxx_destruct;
- (void)gms_setAuthorization:(id)arg1;
- (void)gms_addLocationDescriptorOverride:(id)arg1;
- (void)setResponseDispatchQueue:(id)arg1;
- (void)start;
- (id)initWithDASHConnection:(id)arg1 request:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

