//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface HMEDynamicAnimationViewAssetsBundle : NSObject
{
    _Bool _mainAnimationShouldLoop;
    int _width;
    int _height;
    NSString *_introURL;
    NSString *_mainURL;
    NSString *_successURL;
    NSString *_failureURL;
    NSMutableDictionary *_cache;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
@property(nonatomic) _Bool mainAnimationShouldLoop; // @synthesize mainAnimationShouldLoop=_mainAnimationShouldLoop;
@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *failureURL; // @synthesize failureURL=_failureURL;
@property(copy, nonatomic) NSString *successURL; // @synthesize successURL=_successURL;
@property(copy, nonatomic) NSString *mainURL; // @synthesize mainURL=_mainURL;
@property(copy, nonatomic) NSString *introURL; // @synthesize introURL=_introURL;
- (id)initWithIntroURL:(id)arg1 mainURL:(id)arg2 successURL:(id)arg3 failureURL:(id)arg4 width:(int)arg5 height:(int)arg6 mainAnimationShouldLoop:(_Bool)arg7;
- (id)initWithLottieAnimation:(id)arg1;

@end

