//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GHCCameraDetails, NSError, NSURL, UIViewController;
@protocol HMEFeedAction;

@protocol HMEFeedActionDelegate <NSObject>
- (void)feedHideEventActionDidEnd:(id <HMEFeedAction>)arg1 error:(NSError *)arg2;
- (_Bool)feedHideEventActionShouldStart:(id <HMEFeedAction>)arg1;
- (void)feedAction:(id <HMEFeedAction>)arg1 openAssistantHandoffURL:(NSURL *)arg2;
- (void)feedAction:(id <HMEFeedAction>)arg1 openAssistantSettingsURL:(NSURL *)arg2;
- (void)feedAction:(id <HMEFeedAction>)arg1 openCameraForData:(GHCCameraDetails *)arg2 autoplay:(_Bool)arg3 presentingViewController:(UIViewController *)arg4;
@end

