//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MDCRaisedButton, UIDatePicker, UIStackView;
@protocol HMETimePickerPopupViewControllerDelegate;

@interface HMETimePickerPopupViewController : UIViewController
{
    id <HMETimePickerPopupViewControllerDelegate> _delegate;
    UIStackView *_stackView;
    UIDatePicker *_datePicker;
    MDCRaisedButton *_setButtonForDatePicker;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) MDCRaisedButton *setButtonForDatePicker; // @synthesize setButtonForDatePicker=_setButtonForDatePicker;
@property(readonly, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(readonly, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) __weak id <HMETimePickerPopupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setButtonDidTap:(id)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)loadView;
- (id)initWithTimeDate:(id)arg1;

@end

