//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class MAJActionPrompts, MAJArgument, MAJListSelection, MAJUserIntent, NSMutableArray;

@interface MAJModularAction : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MAJUserIntent *ambiguousUserIntent; // @dynamic ambiguousUserIntent;
@property(retain, nonatomic) NSMutableArray *argumentArray; // @dynamic argumentArray;
@property(readonly, nonatomic) unsigned long long argumentArray_Count; // @dynamic argumentArray_Count;
@property(nonatomic) _Bool hasAmbiguousUserIntent; // @dynamic hasAmbiguousUserIntent;
@property(nonatomic) _Bool hasPrompts; // @dynamic hasPrompts;
@property(nonatomic) _Bool hasProviderArgument; // @dynamic hasProviderArgument;
@property(nonatomic) _Bool hasUserIntentSelection; // @dynamic hasUserIntentSelection;
@property(nonatomic) _Bool hasVeUiType; // @dynamic hasVeUiType;
@property(retain, nonatomic) MAJActionPrompts *prompts; // @dynamic prompts;
@property(retain, nonatomic) MAJArgument *providerArgument; // @dynamic providerArgument;
@property(retain, nonatomic) NSMutableArray *requirementArray; // @dynamic requirementArray;
@property(readonly, nonatomic) unsigned long long requirementArray_Count; // @dynamic requirementArray_Count;
@property(retain, nonatomic) NSMutableArray *userIntentArray; // @dynamic userIntentArray;
@property(readonly, nonatomic) unsigned long long userIntentArray_Count; // @dynamic userIntentArray_Count;
@property(retain, nonatomic) MAJListSelection *userIntentSelection; // @dynamic userIntentSelection;
@property(nonatomic) int veUiType; // @dynamic veUiType;

@end

