//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface ReportStateValidation : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *agentId; // @dynamic agentId;
@property(nonatomic) _Bool hasAgentId; // @dynamic hasAgentId;
@property(nonatomic) _Bool hasHomeAutomationDeviceType; // @dynamic hasHomeAutomationDeviceType;
@property(nonatomic) _Bool hasHomeCoreQueryLatencyMs; // @dynamic hasHomeCoreQueryLatencyMs;
@property(nonatomic) _Bool hasOnlineMatchStatus; // @dynamic hasOnlineMatchStatus;
@property(nonatomic) _Bool hasStateMatches; // @dynamic hasStateMatches;
@property(copy, nonatomic) NSString *homeAutomationDeviceType; // @dynamic homeAutomationDeviceType;
@property(retain, nonatomic) NSMutableArray *homeAutomationTraitNameArray; // @dynamic homeAutomationTraitNameArray;
@property(readonly, nonatomic) unsigned long long homeAutomationTraitNameArray_Count; // @dynamic homeAutomationTraitNameArray_Count;
@property(nonatomic) long long homeCoreQueryLatencyMs; // @dynamic homeCoreQueryLatencyMs;
@property(nonatomic) int onlineMatchStatus; // @dynamic onlineMatchStatus;
@property(nonatomic) _Bool stateMatches; // @dynamic stateMatches;

@end

