//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface SGWPPShareState : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasOwnership; // @dynamic hasOwnership;
@property(nonatomic) int ownership; // @dynamic ownership;
@property(retain, nonatomic) NSMutableArray *sharedWithArray; // @dynamic sharedWithArray;
@property(readonly, nonatomic) unsigned long long sharedWithArray_Count; // @dynamic sharedWithArray_Count;

@end

