//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface UserPreferenceSettingsContentInfo_PreferenceState : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool booleanState; // @dynamic booleanState;
@property(nonatomic) int integerState; // @dynamic integerState;
@property(readonly, nonatomic) int stateOneOfCase; // @dynamic stateOneOfCase;

@end

