//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ACCFilterSwitchComponentMessageProtocol-Protocol.h"
#import "ACCRecordButtonComponentMessageProtocol-Protocol.h"
#import "ACCRecordConfigPublishComponentMessageProtocol-Protocol.h"
#import "ACCRecordCountdownComponentProtocol-Protocol.h"
#import "ACCRecordToolBarComponentMessage-Protocol.h"
#import "AWEAudioWaveformSliderViewDelegate-Protocol.h"

@class AVPlayer, AWEDelayRecordView, NSString, NSTimer, UIViewController;
@protocol ACCComponentBusProtocol, ACCComponentProtocol, ACCRecordProgressBarComponentProtocol, ACCRecordRootComponentProtocol, ACCRecordToolBarComponentProtocol;

@interface ACCRecordCountdownComponent : NSObject <AWEAudioWaveformSliderViewDelegate, ACCRecordCountdownComponentProtocol, ACCRecordConfigPublishComponentMessageProtocol, ACCRecordToolBarComponentMessage, ACCFilterSwitchComponentMessageProtocol, ACCRecordButtonComponentMessageProtocol>
{
    _Bool _isShowingDelayRecordView;
    id <ACCComponentBusProtocol> _componentBus;
    long long _delayRecordMode;
    id <ACCRecordRootComponentProtocol> _recordRootComponent;
    id <ACCRecordProgressBarComponentProtocol> _progressBarComponent;
    id <ACCRecordToolBarComponentProtocol> _toolbarComponent;
    AWEDelayRecordView *_delayRecordView;
    AVPlayer *_player;
    NSTimer *_audioWaveformPlayTimer;
}

@property(retain, nonatomic) NSTimer *audioWaveformPlayTimer; // @synthesize audioWaveformPlayTimer=_audioWaveformPlayTimer;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) _Bool isShowingDelayRecordView; // @synthesize isShowingDelayRecordView=_isShowingDelayRecordView;
@property(retain, nonatomic) AWEDelayRecordView *delayRecordView; // @synthesize delayRecordView=_delayRecordView;
@property(readonly, nonatomic) __weak id <ACCRecordToolBarComponentProtocol> toolbarComponent; // @synthesize toolbarComponent=_toolbarComponent;
@property(readonly, nonatomic) __weak id <ACCRecordProgressBarComponentProtocol> progressBarComponent; // @synthesize progressBarComponent=_progressBarComponent;
@property(readonly, nonatomic) __weak id <ACCRecordRootComponentProtocol> recordRootComponent; // @synthesize recordRootComponent=_recordRootComponent;
@property(nonatomic) long long delayRecordMode; // @synthesize delayRecordMode=_delayRecordMode;
@property(nonatomic) __weak id <ACCComponentBusProtocol> componentBus; // @synthesize componentBus=_componentBus;
- (void).cxx_destruct;
- (void)configDelayRecordMode;
- (void)msg_shouldSwitchFilterGestureBegin:(CDUnknownBlockType)arg1;
- (void)msg_didClickDelayStartRecordButton;
- (void)msg_shouldCaptureAnimationBegin:(CDUnknownBlockType)arg1;
- (void)msg_didFinishConfigAudio:(id)arg1;
@property(readonly, nonatomic) __weak UIViewController *containerVC;
- (void)audioWaveformSliderView:(id)arg1 touchEnd:(double)arg2;
- (void)switchDelayModebuttonClicked:(id)arg1;
- (void)clickDelayRecord;
- (void)dismissDelayRecordViewWithCompletion:(CDUnknownBlockType)arg1;
- (void)clickDelayRecordView;
- (void)audioWaveformPlayTimerAction;
- (void)audioWaveformRemoveTimer;
- (void)audioWaveformAddTimerIfNeeded;
- (double)toBePlayedLocation;
- (void)configPlayerWithAudioURL:(id)arg1;
- (void)showRecordCountdownViewWithCompletion:(CDUnknownBlockType)arg1;
- (void)containerViewControllerDidLoad;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (id)autoInjectComponentDictionaryOftoolbarComponent;
- (id)autoInjectComponentDictionaryOfprogressBarComponent;
- (id)autoInjectComponentDictionaryOfrecordRootComponent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak id <ACCComponentProtocol> superComponent;
@property(readonly) Class superclass;

@end

