//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWebView.h>

@class NSArray;

@interface ALBBWebView : UIWebView
{
    NSArray *_scriptPrefixWhiteList;
}

@property(copy, nonatomic) NSArray *scriptPrefixWhiteList; // @synthesize scriptPrefixWhiteList=_scriptPrefixWhiteList;
- (void).cxx_destruct;
- (id)stringByEvaluatingJavaScriptFromString:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

