//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class AWECircularProgressView, UIImageView;

@interface AWEBaseStickerCollectionViewCell : UICollectionViewCell
{
    unsigned long long _downloadStatus;
    UIImageView *_imageView;
    UIImageView *_downloadImgView;
    AWECircularProgressView *_downloadProgressView;
}

+ (id)identifier;
@property(retain, nonatomic) AWECircularProgressView *downloadProgressView; // @synthesize downloadProgressView=_downloadProgressView;
@property(retain, nonatomic) UIImageView *downloadImgView; // @synthesize downloadImgView=_downloadImgView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) unsigned long long downloadStatus; // @synthesize downloadStatus=_downloadStatus;
- (void).cxx_destruct;
- (void)didMoveToWindow;
- (void)downloadProgressViewScaleDisappear;
- (void)stopDownloadAnimation;
- (void)startDownloadAnimation;
- (id)createRotationAnimation;
- (void)updateDownloadProgress:(double)arg1;
- (void)configCellWithImage:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;

@end

