//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSAttributedString, NSString, UIColor, UIImage;

@interface AWEDuetPlayTagView : UIView
{
    NSAttributedString *_title;
    UIColor *_fillColor;
    double _maxWidth;
    double _cornerRadius;
    double _imageLeftOffset;
    UIImage *_shapeImage;
    NSString *_text;
    struct UIEdgeInsets _textInsets;
}

+ (id)defaultDuetTagViewWithTitle:(id)arg1 maxWidth:(double)arg2 inLightStyle:(_Bool)arg3;
+ (_Bool)replaceOperationAvailableForRange:(struct _NSRange)arg1 inText:(id)arg2;
+ (id)attributedStringByTruncatingString:(id)arg1 toWidth:(double)arg2;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImage *shapeImage; // @synthesize shapeImage=_shapeImage;
@property(nonatomic) double imageLeftOffset; // @synthesize imageLeftOffset=_imageLeftOffset;
@property(nonatomic) struct UIEdgeInsets textInsets; // @synthesize textInsets=_textInsets;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(retain, nonatomic) NSAttributedString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

