//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol TIMConversationCoreInfoModelProtocol <NSObject>
@property(retain, nonatomic) NSDictionary *extDictionary;
@property(retain, nonatomic) NSString *ext;
@property(nonatomic) long long ownerID;
@property(retain, nonatomic) NSString *notice;
@property(retain, nonatomic) NSString *icon;
@property(retain, nonatomic) NSString *desc;
@property(retain, nonatomic) NSString *name;
@property(nonatomic) long long infoVersion;
@property(retain, nonatomic) NSString *belongingConversationIdentifier;
@end

