//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8Chipotle23ForgotPasswordViewModel : _TtCs12_SwiftObject
{
    // Error parsing type: , name: enteredEmailId
    // Error parsing type: , name: isLoading
    // Error parsing type: , name: dismissForgotPassword
    // Error parsing type: , name: showForgotPassword
    // Error parsing type: , name: showConfirmPassword
    // Error parsing type: , name: showError
    // Error parsing type: , name: forgotPasswordTitle
    // Error parsing type: , name: forgotPasswordBody
    // Error parsing type: , name: emailIdTextFieldHint
    // Error parsing type: , name: emailTextFieldValidationError
    // Error parsing type: , name: emailTextFieldEmptyError
    // Error parsing type: , name: confirmedPasswordTitle
    // Error parsing type: , name: emailCopyLabel
    // Error parsing type: , name: confirmButtonTitle
    // Error parsing type: , name: resendButtonTitle
    // Error parsing type: , name: continueButtonTitle
    // Error parsing type: , name: footerText
}

@end

