//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface ADEumServerSideConfig : NSObject
{
    _Bool _enableScreenshot;
    _Bool _screenshotUseCellular;
    _Bool _autoScreenshot;
    _Bool _enableJsAgent;
    _Bool _enableJsAgentAjax;
    _Bool _enableJsAgentSPA;
    _Bool _enableAnrDetection;
    _Bool _enableAnrStackTrace;
    _Bool _enableCrashReporting;
    _Bool _isDirty;
    int _flushInterval;
    long long _timestamp;
    NSArray *_enableFeatures;
    long long _anrThreshold;
}

+ (id)knownKeys;
+ (id)configWithOldConfig:(id)arg1 andNewConfigDict:(id)arg2;
@property(nonatomic) int flushInterval; // @synthesize flushInterval=_flushInterval;
@property(readonly, nonatomic) long long anrThreshold; // @synthesize anrThreshold=_anrThreshold;
@property(readonly, nonatomic) NSArray *enableFeatures; // @synthesize enableFeatures=_enableFeatures;
@property(readonly, nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) _Bool isDirty; // @synthesize isDirty=_isDirty;
@property(readonly, nonatomic) _Bool enableCrashReporting; // @synthesize enableCrashReporting=_enableCrashReporting;
@property(readonly, nonatomic) _Bool enableAnrStackTrace; // @synthesize enableAnrStackTrace=_enableAnrStackTrace;
@property(readonly, nonatomic) _Bool enableAnrDetection; // @synthesize enableAnrDetection=_enableAnrDetection;
@property(readonly, nonatomic) _Bool enableJsAgentSPA; // @synthesize enableJsAgentSPA=_enableJsAgentSPA;
@property(readonly, nonatomic) _Bool enableJsAgentAjax; // @synthesize enableJsAgentAjax=_enableJsAgentAjax;
@property(readonly, nonatomic) _Bool enableJsAgent; // @synthesize enableJsAgent=_enableJsAgent;
@property(readonly, nonatomic) _Bool autoScreenshot; // @synthesize autoScreenshot=_autoScreenshot;
@property(readonly, nonatomic) _Bool screenshotUseCellular; // @synthesize screenshotUseCellular=_screenshotUseCellular;
@property(readonly, nonatomic) _Bool enableScreenshot; // @synthesize enableScreenshot=_enableScreenshot;
- (void).cxx_destruct;
- (void)updateAnrWarningThreshold;
- (void)updateBeaconFilterWithConfigDict;
- (void)updatePersistentStore;
- (_Bool)loadFromPersistentStore;
- (id)pathForPersistentStore;
- (id)init;
- (id)initWithConfigDictionary:(id)arg1 timestamp:(long long)arg2;
- (id)initWithEnableScreenshot:(_Bool)arg1 withAutoScreenshot:(_Bool)arg2 withScreenshotUseCelluar:(_Bool)arg3 withTimestamp:(long long)arg4 withEnableJsAgent:(_Bool)arg5 withEnableJsAgentAjax:(_Bool)arg6 withEnableJsAgentSPA:(_Bool)arg7 withEnableAnrDetection:(_Bool)arg8 withEnableAnrStackTrace:(_Bool)arg9 withEnableCrashReporting:(_Bool)arg10 withEnableFeatures:(id)arg11 withFlushIntervalSeconds:(int)arg12 withAnrThreshold:(long long)arg13;

@end

