//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIButton, UIImageView, UILabel, UIView, UIVisualEffectView;

@interface UARateAppPromptViewController : UIViewController
{
    CDUnknownBlockType _completionHandler;
    UIView *_containerView;
    UIView *_shadowView;
    UIView *_promptContainerView;
    UIView *_promptBackgroundView;
    UIVisualEffectView *_blurView;
    UIImageView *_iconImageView;
    UILabel *_headerLabel;
    UILabel *_descriptionLabel;
    UIButton *_rateButton;
    UIButton *_dismissButton;
    UIView *_iconBottonSpaceView;
    NSString *_promptDescription;
    NSString *_promptHeader;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *promptHeader; // @synthesize promptHeader=_promptHeader;
@property(retain, nonatomic) NSString *promptDescription; // @synthesize promptDescription=_promptDescription;
@property(nonatomic) __weak UIView *iconBottonSpaceView; // @synthesize iconBottonSpaceView=_iconBottonSpaceView;
@property(nonatomic) __weak UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(nonatomic) __weak UIButton *rateButton; // @synthesize rateButton=_rateButton;
@property(nonatomic) __weak UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) __weak UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UIVisualEffectView *blurView; // @synthesize blurView=_blurView;
@property(nonatomic) __weak UIView *promptBackgroundView; // @synthesize promptBackgroundView=_promptBackgroundView;
@property(nonatomic) __weak UIView *promptContainerView; // @synthesize promptContainerView=_promptContainerView;
@property(nonatomic) __weak UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void)viewDidLoad;
- (void)rateButtonTapped:(id)arg1;
- (void)dismissButtonTapped:(id)arg1;
- (void)animateOut:(CDUnknownBlockType)arg1;
- (void)animateIn;
- (void)viewWillAppear:(_Bool)arg1;
- (void)displayWithHeader:(id)arg1 description:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

