//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Localytics/LLBaseMarketingManager.h>

@class LLCreativesManager, LLMarketingSilo, NSHashTable, NSObject;
@protocol OS_dispatch_queue;

@interface LLInboxManager : LLBaseMarketingManager
{
    double _lastRefreshTime;
    CDUnknownBlockType _refreshVisibleCompletionBlock;
    CDUnknownBlockType _refreshAllCompletionBlock;
    LLMarketingSilo *_silo;
    NSObject<OS_dispatch_queue> *_queue;
    LLCreativesManager *_creativesManager;
    long long _throttleSeconds;
    NSHashTable *_displayingDetailViewControllers;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSHashTable *displayingDetailViewControllers; // @synthesize displayingDetailViewControllers=_displayingDetailViewControllers;
@property(nonatomic) long long throttleSeconds; // @synthesize throttleSeconds=_throttleSeconds;
@property(retain, nonatomic) LLCreativesManager *creativesManager; // @synthesize creativesManager=_creativesManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak LLMarketingSilo *silo; // @synthesize silo=_silo;
@property(copy, nonatomic) CDUnknownBlockType refreshAllCompletionBlock; // @synthesize refreshAllCompletionBlock=_refreshAllCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType refreshVisibleCompletionBlock; // @synthesize refreshVisibleCompletionBlock=_refreshVisibleCompletionBlock;
@property(nonatomic) double lastRefreshTime; // @synthesize lastRefreshTime=_lastRefreshTime;
- (void)priorityDownloadInboxCreative:(id)arg1 onDownloadedCompletionBlock:(CDUnknownBlockType)arg2;
- (id)inboxDetailViewControllerForCampaign:(id)arg1;
- (void)tagDismissForInboxDetailViewControllers;
- (void)setInboxDetailViewController:(id)arg1 asDisplaying:(_Bool)arg2;
- (long long)inboxCampaignsUnreadCount;
- (void)deleteInboxCampaign:(id)arg1;
- (_Bool)setInboxCampaign:(id)arg1 asRead:(_Bool)arg2;
- (id)allInboxCampaigns;
- (id)visibleInboxCampaigns;
- (void)removeAllCampaigns;
- (void)clearPushToInboxCampaigns;
- (void)deletePushToInboxCampaigns:(id)arg1;
- (void)saveAsPushToInboxCampaign:(id)arg1;
- (void)processInboxJsonObject:(id)arg1;
- (id)extractInboxRelevantKeys:(id)arg1;
- (void)downloadDidCompleteWithJson:(id)arg1 success:(_Bool)arg2;
- (_Bool)isInboxManifestProcessingAllowed;
- (_Bool)canRefresh;
- (id)initWithSilo:(id)arg1 delegate:(id)arg2 queue:(id)arg3 logger:(id)arg4;

@end

