//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SearchResult.h"

@class NSArray;

@interface ProductResult : SearchResult
{
    NSArray *productListArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *productListArray; // @synthesize productListArray;
- (_Bool)isBreadcrumbsFilterValid:(id)arg1;
- (id)initWithFullSearchResult:(id)arg1 andAppSettings:(id)arg2 isInitialRefinementRequest:(_Bool)arg3;
- (id)initWithFullSearchResult:(id)arg1 andAppSettings:(id)arg2;
- (id)initWithResponseDict:(id)arg1;

@end

