//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseQVCItem.h"

@class NSMutableArray, NSString;

@interface ProgramGuideDay : BaseQVCItem
{
    NSString *dayKey;
    NSMutableArray *dayShowList;
    _Bool hasAllDayEvent;
    NSString *allDayEventName;
    NSString *displayDate;
    long long pageIndex;
}

- (void).cxx_destruct;
@property long long pageIndex; // @synthesize pageIndex;
@property(readonly) NSString *displayDate; // @synthesize displayDate;
@property(retain, nonatomic) NSString *allDayEventName; // @synthesize allDayEventName;
@property _Bool hasAllDayEvent; // @synthesize hasAllDayEvent;
@property(retain, nonatomic) NSMutableArray *dayShowList; // @synthesize dayShowList;
@property(readonly) NSString *dayKey; // @synthesize dayKey;
- (_Bool)isToday;
- (id)initWithDayKey:(id)arg1;

@end

