//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC18OnboardingSharedUI18PDPFooterViewStyle : _TtCs12_SwiftObject
{
    // Error parsing type: , name: adaptiveMargins
    // Error parsing type: , name: isExpandable
    // Error parsing type: , name: unexpandedBackgroundColor
    // Error parsing type: , name: unexpandedTitleTextStyle
    // Error parsing type: , name: unexpandedChevronImage
    // Error parsing type: , name: unexpandedChevronColor
    // Error parsing type: , name: expandedBackgroundColor
    // Error parsing type: , name: expandedTitleTextStyle
    // Error parsing type: , name: expandedChevronImage
    // Error parsing type: , name: expandedChevronColor
    // Error parsing type: , name: imageViewSize
    // Error parsing type: , name: imageViewColor
    // Error parsing type: , name: descriptionTextStyle
    // Error parsing type: , name: interItemHorizontalPadding
    // Error parsing type: , name: interItemVerticalPadding
}

@end

