//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12ImagesCoreUI25ScrollViewImagePrefetcher : _TtCs12_SwiftObject
{
    // Error parsing type: , name: useNewImageFetcher
    // Error parsing type: , name: didFinishPrefetching
    // Error parsing type: , name: prefetchBufferLength
    // Error parsing type: , name: prefetcher
    // Error parsing type: , name: newImageFetcher
    // Error parsing type: , name: subscription
}

@end

