//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC22LegacyDeprecatedCoreUI15PillButtonStyle : _TtCs12_SwiftObject
{
    // Error parsing type: , name: isFullWidth
    // Error parsing type: , name: verticalPadding
    // Error parsing type: , name: backgroundColorNormal
    // Error parsing type: , name: backgroundColorHighlighted
    // Error parsing type: , name: backgroundColorDisabled
    // Error parsing type: , name: textStyle
    // Error parsing type: , name: textLineBreakMode
    // Error parsing type: , name: textColorNormal
    // Error parsing type: , name: textColorHighlighted
    // Error parsing type: , name: textColorDisabled
    // Error parsing type: , name: loaderStyle
    // Error parsing type: , name: leadingEdgeInset
    // Error parsing type: , name: trailingEdgeInset
    // Error parsing type: , name: borderColor
    // Error parsing type: , name: borderWidth
    // Error parsing type: , name: cornerRadius
}

@end

