//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12NiobeService17DenormalizedCache : _TtCs12_SwiftObject
{
    // Error parsing type: , name: lock
    // Error parsing type: , name: localeService
    // Error parsing type: , name: db
    // Error parsing type: , name: records
    // Error parsing type: , name: key
    // Error parsing type: , name: value
    // Error parsing type: , name: firstModifiedAt
    // Error parsing type: , name: lastModifiedAt
    // Error parsing type: , name: lastAccessedAt
    // Error parsing type: , name: size
}

@end

