//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC23ExperiencesMYXPrivateUI25PricingGroupRatesRowStyle : _TtCs12_SwiftObject
{
    // Error parsing type: , name: adaptiveMargins
    // Error parsing type: , name: titleLabelFont
    // Error parsing type: , name: guestNumberLabelFont
    // Error parsing type: , name: discountLabelFont
    // Error parsing type: , name: dashLabelFont
    // Error parsing type: , name: errorMessageLabelFont
    // Error parsing type: , name: verticalStackViewSpacing
    // Error parsing type: , name: minMaxCountInputHorizontalStackViewSpacing
    // Error parsing type: , name: guestNumberMinMaxCountVerticalStackViewSpacing
    // Error parsing type: , name: discountInputVerticalStackViewSpacing
}

@end

