//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCV15LegacyHomesCore14BeehiveListing23__BeehiveListingStorage : _TtCs12_SwiftObject
{
    // Error parsing type: , name: typename
    // Error parsing type: , name: id
    // Error parsing type: , name: unscrubbedName
    // Error parsing type: , name: nameOrPlaceholderName
    // Error parsing type: , name: nickname
    // Error parsing type: , name: thumbnailUrl
    // Error parsing type: , name: collectionTags
    // Error parsing type: , name: status
    // Error parsing type: , name: readyForSelectStatus
    // Error parsing type: , name: listYourSpaceLastFinishedStepId
    // Error parsing type: , name: canPublish
    // Error parsing type: , name: permissionMeta
}

@end

