//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC27ConstellationElementsCoreUI14BaseMarginView.h"

@interface _TtC24HostPerformancePrivateUI17AverageRatingView : _TtC27ConstellationElementsCoreUI14BaseMarginView
{
    // Error parsing type: , name: didSelect
    // Error parsing type: , name: horizontalContainer
    // Error parsing type: , name: innerVerticalContainer
    // Error parsing type: , name: circleView
    // Error parsing type: , name: ratingView
    // Error parsing type: , name: marquee
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: verticalStackFillerView
    // Error parsing type: , name: disclosureView
    // Error parsing type: , name: disclosureViewWrapper
    // Error parsing type: , name: linkActionButton
    // Error parsing type: , name: style
}

- (void).cxx_destruct;
- (id)init;

@end

