//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC20AirbnbBusinessTravel39BusinessTravelLandingPageViewController : UIViewController
{
    // Error parsing type: , name: $__lazy_storage_$_navigationBarInstaller
    // Error parsing type: , name: navScrollingDelegate
    // Error parsing type: , name: delegate
    // Error parsing type: , name: retainDelegate
    // Error parsing type: , name: retainedDelegate
    // Error parsing type: , name: scrollingStackView
    // Error parsing type: , name: content
    // Error parsing type: , name: hidesBackButton
    // Error parsing type: , name: marqueeView
    // Error parsing type: , name: actionButtonView
    // Error parsing type: , name: legalDisclaimerComponent
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

