//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GMSTileRequest-Protocol.h"

@class GMSCCachedTile, GMSTileCoords, GMSx_GPBInt32Array, NSDictionary, NSString;
@protocol GMSTile;

@interface GMSTileRequest : NSObject <GMSTileRequest>
{
    GMSTileCoords *_coords;
    NSDictionary *_extraRequestParams;
    int _fetchType;
    int _aggregateFetchType;
    int _dataVersion;
    id _target;
    SEL _selector;
    id _savedTarget;
    SEL _savedSelector;
    id <GMSTile> _cachedTile;
    GMSCCachedTile *_cachedTileProto;
    _Bool _calledToSayMakingServerRequest;
    _Bool _calledToComplete;
    GMSTileRequest *_nextRequest;
    _Bool _forcedToFail;
    int _mode;
    GMSx_GPBInt32Array *_paintExperiments;
    NSString *_legalCountry;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *legalCountry; // @synthesize legalCountry=_legalCountry;
@property(copy, nonatomic) GMSx_GPBInt32Array *paintExperiments; // @synthesize paintExperiments=_paintExperiments;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(retain, nonatomic) GMSCCachedTile *cachedTileProto; // @synthesize cachedTileProto=_cachedTileProto;
@property(retain, nonatomic) id <GMSTile> cachedTile; // @synthesize cachedTile=_cachedTile;
@property(nonatomic) _Bool forcedToFail; // @synthesize forcedToFail=_forcedToFail;
@property(readonly, copy) NSString *description;
- (void)invokeCallbackWithTileService:(id)arg1 status:(int)arg2 tile:(id)arg3 useSavedCallback:(_Bool)arg4;
- (void)invokeCallbackWithTileService:(id)arg1 status:(int)arg2 tile:(id)arg3;
- (void)invokeSavedCallbackWithTileService:(id)arg1 status:(int)arg2 tile:(id)arg3;
- (void)saveAndClearCallback;
- (void)clearCallback;
@property(readonly, copy, nonatomic) NSDictionary *extraRequestParams;
- (id)target;
@property(nonatomic) int dataVersion;
@property(readonly, nonatomic) int aggregateFetchType;
- (int)fetchType;
@property(readonly, nonatomic) GMSTileCoords *tileCoords;
- (id)nextDuplicate;
- (void)addDuplicate:(id)arg1;
- (id)initWithTileCoords:(id)arg1 extraRequestParams:(id)arg2 paintExperiments:(id)arg3 legalCountry:(id)arg4 fetchType:(int)arg5 target:(id)arg6 selector:(SEL)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

