//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCTViewManager.h"

@interface DCDEmojiPickerManager : RCTViewManager
{
}

+ (const struct RCTMethodInfo *)__rct_export__592;
+ (const struct RCTMethodInfo *)__rct_export__441;
+ (const struct RCTMethodInfo *)__rct_export__320;
+ (id)propConfig_dark;
+ (id)propConfig_onSelectEmoji;
+ (id)propConfig_onFocusSection;
+ (void)load;
+ (id)moduleName;
- (void)updateData:(id)arg1 data:(id)arg2 animated:(_Bool)arg3;
- (void)scrollToSection:(id)arg1 section:(id)arg2;
- (void)scrollTo:(id)arg1 x:(id)arg2 y:(id)arg3 animated:(_Bool)arg4;
- (id)view;

@end

