//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC11PusherSwift12OCPusherHost : NSObject
{
    // Error parsing type: , name: type
    // Error parsing type: , name: host
    // Error parsing type: , name: cluster
}

- (void).cxx_destruct;
- (id)initWithCluster:(id)arg1;
- (id)initWithHost:(id)arg1;
- (id)init;
@property(nonatomic, copy) NSString *cluster;
@property(nonatomic, copy) NSString *host;
@property(nonatomic) long long type; // @synthesize type;

@end

