//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Grocery25GroceryBaseViewController.h"

@class NSLayoutConstraint, TTTAttributedLabel, UIButton, UIImageView, UILabel, UIScrollView, UIView, _TtC10CoreStyles13CoreTextField, _TtC10CoreStyles18CoreTertiaryButton, _TtC7Grocery11SimpleToast;

@interface _TtC7Grocery25PaymentEditViewController : _TtC7Grocery25GroceryBaseViewController
{
    // Error parsing type: , name: textFieldLastEntry
    // Error parsing type: , name: customerAPI
    // Error parsing type: , name: customerProvider
    // Error parsing type: , name: configuration
    // Error parsing type: , name: userManager
    // Error parsing type: , name: encryptionManager
    // Error parsing type: , name: simpleToast
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: firstNameFieldWrapper
    // Error parsing type: , name: firstNameField
    // Error parsing type: , name: lastNameFieldWrapper
    // Error parsing type: , name: lastNameField
    // Error parsing type: , name: cardNumberFieldWrapper
    // Error parsing type: , name: cardNumberField
    // Error parsing type: , name: cardImage
    // Error parsing type: , name: expirationDateFieldWrapper
    // Error parsing type: , name: expirationDateField
    // Error parsing type: , name: securityCodeFieldWrapper
    // Error parsing type: , name: securityCodeField
    // Error parsing type: , name: securityInfoButton
    // Error parsing type: , name: billingAddressLabelWrapper
    // Error parsing type: , name: billingAddressLabel
    // Error parsing type: , name: addBillingAddressButtonWrapper
    // Error parsing type: , name: changeButton
    // Error parsing type: , name: addBillingAddressButton
    // Error parsing type: , name: paymentMethodsLabel
    // Error parsing type: , name: ebtLabel
    // Error parsing type: , name: buttonBar
    // Error parsing type: , name: saveButton
    // Error parsing type: , name: buttonBarBottomMargin
    // Error parsing type: , name: defaultCardImage
    // Error parsing type: , name: paymentMethod
    // Error parsing type: , name: billingAddress
    // Error parsing type: , name: cardAssociation
    // Error parsing type: , name: buttonBarKeyboardManager
    // Error parsing type: , name: formController
    // Error parsing type: , name: paymentType
    // Error parsing type: , name: isEditingContract
    // Error parsing type: , name: isCapitalOneFrontBookEnabled
    // Error parsing type: , name: isCapitalOneBackBookEnabled
    // Error parsing type: , name: isCapitalOnePlusEnabled
    // Error parsing type: , name: isSlotAbuseFlow
    // Error parsing type: , name: didReceivedCaptchaError
    // Error parsing type: , name: paymentMethodsUrl
    // Error parsing type: , name: lastEntry
    // Error parsing type: , name: analyticsPackage
    // Error parsing type: , name: dependencies
    // Error parsing type: , name: paymentMethodSaved
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)focusPreviousField;
- (void)focusNextField;
- (void)save;
- (void)securityCodeInfoTapped:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NSLayoutConstraint *buttonBarBottomMargin; // @synthesize buttonBarBottomMargin;
@property(nonatomic) __weak UIButton *saveButton; // @synthesize saveButton;
@property(nonatomic) __weak UIView *buttonBar; // @synthesize buttonBar;
@property(nonatomic) __weak UILabel *ebtLabel; // @synthesize ebtLabel;
@property(nonatomic) __weak TTTAttributedLabel *paymentMethodsLabel; // @synthesize paymentMethodsLabel;
@property(nonatomic) __weak _TtC10CoreStyles18CoreTertiaryButton *addBillingAddressButton; // @synthesize addBillingAddressButton;
@property(nonatomic) __weak _TtC10CoreStyles18CoreTertiaryButton *changeButton; // @synthesize changeButton;
@property(nonatomic) __weak UIView *addBillingAddressButtonWrapper; // @synthesize addBillingAddressButtonWrapper;
@property(nonatomic) __weak UILabel *billingAddressLabel; // @synthesize billingAddressLabel;
@property(nonatomic) __weak UIView *billingAddressLabelWrapper; // @synthesize billingAddressLabelWrapper;
@property(nonatomic) __weak UIButton *securityInfoButton; // @synthesize securityInfoButton;
@property(nonatomic) __weak _TtC10CoreStyles13CoreTextField *securityCodeField; // @synthesize securityCodeField;
@property(nonatomic) __weak UIView *securityCodeFieldWrapper; // @synthesize securityCodeFieldWrapper;
@property(nonatomic) __weak _TtC10CoreStyles13CoreTextField *expirationDateField; // @synthesize expirationDateField;
@property(nonatomic) __weak UIView *expirationDateFieldWrapper; // @synthesize expirationDateFieldWrapper;
@property(nonatomic) __weak UIImageView *cardImage; // @synthesize cardImage;
@property(nonatomic) __weak _TtC10CoreStyles13CoreTextField *cardNumberField; // @synthesize cardNumberField;
@property(nonatomic) __weak UIView *cardNumberFieldWrapper; // @synthesize cardNumberFieldWrapper;
@property(nonatomic) __weak _TtC10CoreStyles13CoreTextField *lastNameField; // @synthesize lastNameField;
@property(nonatomic) __weak UIView *lastNameFieldWrapper; // @synthesize lastNameFieldWrapper;
@property(nonatomic) __weak _TtC10CoreStyles13CoreTextField *firstNameField; // @synthesize firstNameField;
@property(nonatomic) __weak UIView *firstNameFieldWrapper; // @synthesize firstNameFieldWrapper;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView;
@property(nonatomic) __weak _TtC7Grocery11SimpleToast *simpleToast; // @synthesize simpleToast;

@end

