//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC7Fitment16PickerController : UIViewController
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: didSelectOptionHandler
    // Error parsing type: , name: didDismissPicker
    // Error parsing type: , name: toolBarView
    // Error parsing type: , name: $__lazy_storage_$_pickerView
    // Error parsing type: , name: $__lazy_storage_$_backgroundView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dismissView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

@end

