//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AtriusLocation/ATRIHeadingFilterStrategy-Protocol.h>

@interface ATRLockoutHeadingFilterStrategy : NSObject <ATRIHeadingFilterStrategy>
{
    double _fallbackMS;
    double _lastGoodVlcTimestamp;
    double _msSinceLastVlcFix;
    double _msSinceLastAngleFix;
}

@property double msSinceLastAngleFix; // @synthesize msSinceLastAngleFix=_msSinceLastAngleFix;
@property double msSinceLastVlcFix; // @synthesize msSinceLastVlcFix=_msSinceLastVlcFix;
@property double lastGoodVlcTimestamp; // @synthesize lastGoodVlcTimestamp=_lastGoodVlcTimestamp;
@property double fallbackMS; // @synthesize fallbackMS=_fallbackMS;
- (_Bool)shouldFilter:(id)arg1;
- (id)init:(double)arg1;

@end

