//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EditNoteBaseViewController.h"

#import "AVAudioPlayerDelegate-Protocol.h"
#import "AVAudioRecorderDelegate-Protocol.h"
#import "RecorderViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AVAudioPlayer, AVAudioRecorder, AttachmentDownloadSession, NSIndexPath, NSMutableArray, NSString, NSTimer, UIButton, UIImage, UILabel, UIProgressView, UITableView, UIView;

@interface EditRecordingViewController : EditNoteBaseViewController <UITableViewDataSource, UITableViewDelegate, UINavigationControllerDelegate, AVAudioRecorderDelegate, AVAudioPlayerDelegate, RecorderViewControllerDelegate>
{
    AVAudioRecorder *recorder;
    AVAudioPlayer *player;
    NSMutableArray *attachments;
    _Bool _inLongPress;
    UITableView *_tableView;
    UIView *_toolbar;
    UIProgressView *_progressView;
    UIButton *_recordButton;
    UIButton *_playButton;
    UILabel *_timeLabel;
    UILabel *_durationLabel;
    NSIndexPath *_lastSelectedIndexPath;
    NSTimer *_timer;
    UIImage *_play;
    UIImage *_pause;
    UIImage *_recordon;
    UIImage *_recordoff;
    UIImage *_recordinglist;
    UIImage *_recordinglistoff;
    AttachmentDownloadSession *_attachmentDownloadSession;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AttachmentDownloadSession *attachmentDownloadSession; // @synthesize attachmentDownloadSession=_attachmentDownloadSession;
@property(retain, nonatomic) UIImage *recordinglistoff; // @synthesize recordinglistoff=_recordinglistoff;
@property(retain, nonatomic) UIImage *recordinglist; // @synthesize recordinglist=_recordinglist;
@property(retain, nonatomic) UIImage *recordoff; // @synthesize recordoff=_recordoff;
@property(retain, nonatomic) UIImage *recordon; // @synthesize recordon=_recordon;
@property(retain, nonatomic) UIImage *pause; // @synthesize pause=_pause;
@property(retain, nonatomic) UIImage *play; // @synthesize play=_play;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSIndexPath *lastSelectedIndexPath; // @synthesize lastSelectedIndexPath=_lastSelectedIndexPath;
@property(nonatomic, getter=isInLongPress) _Bool inLongPress; // @synthesize inLongPress=_inLongPress;
@property(nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(nonatomic) UIButton *recordButton; // @synthesize recordButton=_recordButton;
@property(nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) UIView *toolbar; // @synthesize toolbar=_toolbar;
@property(nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)cancelPendingActivity;
- (void)setSecureNote:(id)arg1;
- (void)timerFired:(id)arg1;
- (void)setAudioControlButtonState;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)endPlaying;
- (void)pausePlaying;
- (void)beginPlaying;
- (_Bool)canBeginPlaying;
- (_Bool)isPlaying;
- (void)audioRecorderEncodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(_Bool)arg2;
- (void)endRecording;
- (void)recorderSaved:(id)arg1;
- (void)addRecording:(id)arg1;
- (void)pauseRecording;
- (void)beginRecording;
- (_Bool)canBeginRecording;
- (_Bool)isRecording;
- (_Bool)isPaused;
- (void)play_Clicked:(id)arg1;
- (void)record_Clicked:(id)arg1;
- (void)deleteAttachmentAtIndexPath:(id)arg1;
- (void)deleteAttachment;
- (void)playAttachment;
- (void)selectAttachmentAtIndexPath:(id)arg1;
- (void)enableDownloadCancelButton;
- (void)dismissDownloadMessage;
- (void)presentDownloadMessage;
- (void)downloadAndSelectAttachment:(id)arg1;
- (void)longPress:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

