//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDKPermission, NSArray, UIColor, UIImage;
@protocol GDKLinkSharingCVOProtocol, GDKShareUserCVOProtocol;

@interface GDKRoleSelectorParams : NSObject
{
    _Bool _blocosEnabled_13;
    _Bool _allowAccessRemoval_18;
    _Bool _temakiEnabled_13;
    _Bool _isFolder_8;
    _Bool _isTeamDriveItem_15;
    _Bool _isSiteFileType_14;
    long long _role_4;
    GDKPermission *_permission_10;
    UIImage *_avatar_6;
    NSArray *_selectableRoles_15;
    UIColor *_themeColor_10;
    id <GDKShareUserCVOProtocol> _userCVO_7;
    id <GDKLinkSharingCVOProtocol> _linkSharingCVO_14;
}

@property(readonly, nonatomic) _Bool isSiteFileType; // @synthesize isSiteFileType=_isSiteFileType_14;
@property(readonly, nonatomic) id <GDKLinkSharingCVOProtocol> linkSharingCVO; // @synthesize linkSharingCVO=_linkSharingCVO_14;
@property(readonly, nonatomic) id <GDKShareUserCVOProtocol> userCVO; // @synthesize userCVO=_userCVO_7;
@property(readonly, nonatomic) _Bool isTeamDriveItem; // @synthesize isTeamDriveItem=_isTeamDriveItem_15;
@property(readonly, copy, nonatomic) UIColor *themeColor; // @synthesize themeColor=_themeColor_10;
@property(readonly, nonatomic) _Bool isFolder; // @synthesize isFolder=_isFolder_8;
@property(readonly, copy, nonatomic) NSArray *selectableRoles; // @synthesize selectableRoles=_selectableRoles_15;
@property(readonly, copy, nonatomic) UIImage *avatar; // @synthesize avatar=_avatar_6;
@property(readonly, nonatomic) _Bool temakiEnabled; // @synthesize temakiEnabled=_temakiEnabled_13;
@property(readonly, nonatomic) _Bool allowAccessRemoval; // @synthesize allowAccessRemoval=_allowAccessRemoval_18;
@property(readonly, nonatomic) _Bool blocosEnabled; // @synthesize blocosEnabled=_blocosEnabled_13;
@property(readonly, nonatomic) GDKPermission *permission; // @synthesize permission=_permission_10;
@property(readonly, nonatomic) long long role; // @synthesize role=_role_4;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)initWithRole:(long long)arg1 permission:(id)arg2 blocosEnabled:(_Bool)arg3 allowAccessRemoval:(_Bool)arg4 temakiEnabled:(_Bool)arg5 avatar:(id)arg6 selectableRoles:(id)arg7 isFolder:(_Bool)arg8 themeColor:(id)arg9 isTeamDriveItem:(_Bool)arg10 userCVO:(id)arg11 linkSharingCVO:(id)arg12 isSiteFileType:(_Bool)arg13;

@end

