//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <drive_extension_framework/GOOBaseContentViewObject.h>

@class UIImage;

@interface GDKSubscriptionHeaderCVO : GOOBaseContentViewObject
{
    UIImage *_headerImage;
}

@property(readonly, nonatomic) UIImage *headerImage; // @synthesize headerImage=_headerImage;
- (void).cxx_destruct;
- (unsigned long long)elementKind;
- (Class)contentViewClass;
- (id)initWithHeaderImage:(id)arg1;

@end

