//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JavaSecurityKeyStore_Builder : NSObject
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)newInstanceWithNSString:(id)arg1 withJavaSecurityProvider:(id)arg2 withJavaSecurityKeyStore_ProtectionParameter:(id)arg3;
+ (id)newInstanceWithNSString:(id)arg1 withJavaSecurityProvider:(id)arg2 withJavaIoFile:(id)arg3 withJavaSecurityKeyStore_ProtectionParameter:(id)arg4;
+ (id)newInstanceWithJavaSecurityKeyStore:(id)arg1 withJavaSecurityKeyStore_ProtectionParameter:(id)arg2;
- (id)getProtectionParameterWithNSString:(id)arg1;
- (id)getKeyStore;
- (id)init;

@end

