//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol WACallControlDelegate <NSObject>
- (void)didTapAddParticipant:(id)arg1;
- (void)didEndCall:(id)arg1;
- (void)didSwitchCamera:(id)arg1;
- (void)didToggleMute:(id)arg1 shouldMute:(_Bool)arg2;
- (void)didToggleVoiceAndVideo:(id)arg1 withCompletion:(void (^)(_Bool))arg2;
- (void)didToggleSpeaker:(id)arg1 shouldUseSpeaker:(_Bool)arg2 withCompletion:(void (^)(_Bool))arg3;
- (void)didIgnoreCall:(id)arg1;
- (void)didAnswerCall:(id)arg1;
@end

