//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import <Payments/WALinkLabelDelegate-Protocol.h>

@class NSArray, NSMutableSet, NSString, WAPaymentBaseTransaction;
@protocol WAPaymentTransactionDetailsDelegate;

@interface WAPaymentTransactionDetailsTableViewController : UITableViewController <WALinkLabelDelegate>
{
    _Bool _loadingParticipant;
    _Bool _loadingTransactionStatus;
    _Bool _loadingAccountDetails;
    _Bool _noteExpanded;
    WAPaymentBaseTransaction *_transaction;
    id <WAPaymentTransactionDetailsDelegate> _delegate;
    NSArray *_layout;
    NSMutableSet *_loadingCells;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *loadingCells; // @synthesize loadingCells=_loadingCells;
@property(nonatomic) _Bool noteExpanded; // @synthesize noteExpanded=_noteExpanded;
@property(copy, nonatomic) NSArray *layout; // @synthesize layout=_layout;
@property(nonatomic) _Bool loadingAccountDetails; // @synthesize loadingAccountDetails=_loadingAccountDetails;
@property(nonatomic) _Bool loadingTransactionStatus; // @synthesize loadingTransactionStatus=_loadingTransactionStatus;
@property(nonatomic) _Bool loadingParticipant; // @synthesize loadingParticipant=_loadingParticipant;
@property(nonatomic) __weak id <WAPaymentTransactionDetailsDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAPaymentBaseTransaction *transaction; // @synthesize transaction=_transaction;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (_Bool)isHeaderSection:(long long)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setLoading:(_Bool)arg1 forCellClass:(Class)arg2;
- (void)reloadCell:(Class)arg1 animation:(long long)arg2;
- (id)detailCellAtIndexPath:(id)arg1;
- (void)registerCells;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)expandNote;
- (void)updateTransaction:(id)arg1 layout:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

