//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, WAStreamingMediaLoaderMessageInfo;

@interface WAStreamingMediaLoaderPendingDownloadInfo : NSObject
{
    // Error parsing type: AI, name: _modes
    WAStreamingMediaLoaderMessageInfo *_messageInfo;
    NSDate *_queuedDate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSDate *queuedDate; // @synthesize queuedDate=_queuedDate;
@property(readonly, nonatomic) WAStreamingMediaLoaderMessageInfo *messageInfo; // @synthesize messageInfo=_messageInfo;
- (void)clearModes:(unsigned long long)arg1;
- (void)setModes:(unsigned long long)arg1;
@property(readonly) unsigned long long modes;
@property(readonly, nonatomic) unsigned long long priority;
- (id)initWithMessageInfo:(id)arg1;

@end

