//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Core/NSCopying-Protocol.h>

@class NSString;

@interface WAXValue : NSObject <NSCopying>
{
    _Bool _sanitized;
    CDUnknownBlockType _validate;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType validate; // @synthesize validate=_validate;
@property(nonatomic) _Bool sanitized; // @synthesize sanitized=_sanitized;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)wax_unredactedDescription;
@property(readonly, nonatomic) NSString *unredactedDescription;
@property(readonly, nonatomic) NSString *redactedDescription;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) unsigned long long role;
@property(retain, nonatomic) id objectValue;
@property(readonly, nonatomic) NSString *stringValue;
- (id)initPrivate;

@end

