//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Module_Framework/YTBaseCoreDataStore.h>

@class GIMMe;

@interface YTDeferredAtrDataStore : YTBaseCoreDataStore
{
    GIMMe *_gimme;
}

@property(nonatomic) __weak GIMMe *gimme; // @synthesize gimme=_gimme;
- (void).cxx_destruct;
- (id)fetchRequestForEntityWithCPN:(id)arg1 context:(id)arg2;
- (void)fetchDeferredAtrDataWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)deleteDeferredAtrData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)incrementRetryCountForDeferredAtrData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)storeDeferredAtrData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

