//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCE12CheckDepositCSo8NSBundleP33_08EE189FC0D62405FEF9246976873E3F20CheckDepositSentinel : _TtCs12_SwiftObject
{
}

@end

