//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapsUIComponents/_TtC16MapsUIComponents30MissionMapImagesViewController.h>

#import <MapsUIComponents/_TtP17AspenUIComponents40TransformableImageViewControllerDelegate_-Protocol.h>

@interface _TtC16MapsUIComponents30MissionMapImagesViewController (MapsUIComponents1) <_TtP17AspenUIComponents40TransformableImageViewControllerDelegate_>
- (void)wifiHeatMapButtonPressed;
- (void)tranformableImageViewController:(id)arg1 didChangeImageTransform:(struct CGAffineTransform)arg2;
@end

