//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AWSCore/AWSModel.h>

@class AWSIoTPolicyVersionIdentifier, NSString;

@interface AWSIoTResourceIdentifier : AWSModel
{
    NSString *_account;
    NSString *_caCertificateId;
    NSString *_clientId;
    NSString *_cognitoIdentityPoolId;
    NSString *_deviceCertificateId;
    NSString *_iamRoleArn;
    AWSIoTPolicyVersionIdentifier *_policyVersionIdentifier;
    NSString *_roleAliasArn;
}

+ (id)policyVersionIdentifierJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *roleAliasArn; // @synthesize roleAliasArn=_roleAliasArn;
@property(retain, nonatomic) AWSIoTPolicyVersionIdentifier *policyVersionIdentifier; // @synthesize policyVersionIdentifier=_policyVersionIdentifier;
@property(retain, nonatomic) NSString *iamRoleArn; // @synthesize iamRoleArn=_iamRoleArn;
@property(retain, nonatomic) NSString *deviceCertificateId; // @synthesize deviceCertificateId=_deviceCertificateId;
@property(retain, nonatomic) NSString *cognitoIdentityPoolId; // @synthesize cognitoIdentityPoolId=_cognitoIdentityPoolId;
@property(retain, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
@property(retain, nonatomic) NSString *caCertificateId; // @synthesize caCertificateId=_caCertificateId;
@property(retain, nonatomic) NSString *account; // @synthesize account=_account;
- (void).cxx_destruct;

@end

