//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSProgress, OTAWorkflow;

@protocol OTAWorkflowDelegate <NSObject>

@optional
- (void)OTAWorkflow:(OTAWorkflow *)arg1 didFailWithError:(unsigned long long)arg2;
- (void)OTAWorkflowProgress:(NSProgress *)arg1;
- (void)OTAWorkflowCanceled:(OTAWorkflow *)arg1;
- (void)OTAWorkflowCompletedOTADL:(OTAWorkflow *)arg1;
- (void)OTAWorkflowStartedOTADL:(OTAWorkflow *)arg1;
- (void)OTAWorkflowCompletedGetOTACTL:(OTAWorkflow *)arg1;
- (void)OTAWorkflowStartedGetOTACTL:(OTAWorkflow *)arg1;
- (void)OTAWorkflowCompletedPostOTACTL:(OTAWorkflow *)arg1;
- (void)OTAWorkflowStartedPostOTACTL:(OTAWorkflow *)arg1;
- (void)OTAWorkflowRetry:(OTAWorkflow *)arg1;
@end

