//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class STPAPIClient, STPEphemeralKey, STPEphemeralKeyManager;

@interface STPPushProvisioningContext : NSObject
{
    STPAPIClient *_apiClient;
    STPEphemeralKeyManager *_keyManager;
    STPEphemeralKey *_ephemeralKey;
}

+ (id)requestConfigurationWithName:(id)arg1 description:(id)arg2 last4:(id)arg3 brand:(long long)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) STPEphemeralKey *ephemeralKey; // @synthesize ephemeralKey=_ephemeralKey;
@property(retain, nonatomic) STPEphemeralKeyManager *keyManager; // @synthesize keyManager=_keyManager;
@property(retain, nonatomic) STPAPIClient *apiClient; // @synthesize apiClient=_apiClient;
- (void)addPaymentPassViewController:(id)arg1 generateRequestWithCertificateChain:(id)arg2 nonce:(id)arg3 nonceSignature:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)initWithKeyProvider:(id)arg1;

@end

