//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Stripe/STPAPIResponseDecodable-Protocol.h>

@class NSDictionary, NSString, NSURL;

@interface STPSourceSEPADebitDetails : NSObject <STPAPIResponseDecodable>
{
    NSString *_last4;
    NSString *_bankCode;
    NSString *_country;
    NSString *_fingerprint;
    NSString *_mandateReference;
    NSURL *_mandateURL;
    NSDictionary *_allResponseFields;
}

+ (id)decodedObjectFromAPIResponse:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *allResponseFields; // @synthesize allResponseFields=_allResponseFields;
@property(readonly, nonatomic) NSURL *mandateURL; // @synthesize mandateURL=_mandateURL;
@property(readonly, nonatomic) NSString *mandateReference; // @synthesize mandateReference=_mandateReference;
@property(readonly, nonatomic) NSString *fingerprint; // @synthesize fingerprint=_fingerprint;
@property(readonly, nonatomic) NSString *country; // @synthesize country=_country;
@property(readonly, nonatomic) NSString *bankCode; // @synthesize bankCode=_bankCode;
@property(readonly, nonatomic) NSString *last4; // @synthesize last4=_last4;
- (id)initWithDictionary:(id)arg1;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

