//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@interface UjetJSQMessagesCellTextView : UITextView
{
}

- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (struct _NSRange)selectedRange;
- (void)setSelectedRange:(struct _NSRange)arg1;
- (void)awakeFromNib;

@end

