//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TelegramUI/NSObject-Protocol.h>

@protocol PSKeyValueReader <NSObject>
- (void)enumerateKeysAndValuesBetweenLowerBoundKey:(CDStruct_b9c9288f *)arg1 upperBoundKey:(CDStruct_b9c9288f *)arg2 options:(long long)arg3 withBlock:(void (^)(struct *, struct *, _Bool *))arg4;
- (_Bool)readValueBetweenLowerBoundKey:(CDStruct_b9c9288f *)arg1 upperBoundKey:(CDStruct_b9c9288f *)arg2 selectKey:(int)arg3 selectedKey:(CDStruct_b9c9288f *)arg4 selectedValue:(CDStruct_b9c9288f *)arg5;
- (_Bool)readValueForRawKey:(CDStruct_b9c9288f *)arg1 value:(CDStruct_b9c9288f *)arg2;
@end

