//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class T1PlayerSessionProducer;

@interface _TtC9T1TwitterP33_DD3A5730EA010439419ABF2903D9B01935FleetEntryPlayerFactoryIdentifiable : NSObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: sessionSource
    // Error parsing type: , name: $__lazy_storage_$_playerSessionProducer
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) T1PlayerSessionProducer *playerSessionProducer;

@end

