//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC9T1Twitter33T1DirectMessageFleetLayoutMetrics : NSObject
{
    // Error parsing type: , name: fleetTextSize
    // Error parsing type: , name: fleetViewSize
    // Error parsing type: , name: contentInset
}

+ (id)zero;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) struct CGSize fleetViewSize; // @synthesize fleetViewSize;

@end

