//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PeriscopeSDK/PTVBroadcastThumbnailManagerObserver-Protocol.h>

@class NSString, PTVBroadcastController, PTVWeakSet;

@interface PTVBroadcastEditViewModel : NSObject <PTVBroadcastThumbnailManagerObserver>
{
    PTVWeakSet *_observers;
    _Bool _hasLoadedThumbnails;
    double _thumbnailTimeCode;
    double _startTimeCode;
    NSString *_title;
    PTVBroadcastController *_broadcastController;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasLoadedThumbnails; // @synthesize hasLoadedThumbnails=_hasLoadedThumbnails;
@property(readonly, nonatomic) PTVBroadcastController *broadcastController; // @synthesize broadcastController=_broadcastController;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) double startTimeCode; // @synthesize startTimeCode=_startTimeCode;
@property(readonly, nonatomic) double thumbnailTimeCode; // @synthesize thumbnailTimeCode=_thumbnailTimeCode;
- (void)didCompleteEditBroadcastWithBroadcastProperties:(id)arg1 error:(id)arg2;
- (void)saveChangesWithTitle:(id)arg1 replayStartTime:(double)arg2 replayThumbnailTimeCode:(double)arg3 completion:(CDUnknownBlockType)arg4;
- (void)load;
- (void)notifyWithBlock:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (long long)thumbnailIndexForTimeCode:(double)arg1;
- (id)thumbnailAtIndex:(long long)arg1;
- (long long)numberOfThumbnails;
- (void)getPreLoadedAndBestThumbnailURLForVideoPosition:(double)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) double minimumThumbnailTimeCode;
@property(readonly, nonatomic) double maximumThumbnailTimeCode;
@property(readonly, nonatomic) double minimumStartTimeCode;
@property(readonly, nonatomic) double maximumStartTimeCode;
@property(readonly, nonatomic) _Bool isTitleEditable;
- (void)broadcastThumbnailManagerDidFailToLoadThumbnails:(id)arg1;
- (void)broadcastThumbnailManagerDidLoadThumbnails:(id)arg1;
- (id)initWithBroadcastController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

