//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1StatusViewEventHandler-Protocol.h>

@class NSSet, NSString, T1StatusMediaHandler, T1StatusTableSlideshowManager, TFNDataViewController;
@protocol T1StatusViewEventScribeHandler, TFNTwitterCardScribeContextProvider;

@interface T1StatusRowAdapterViewEventHandler : NSObject <T1StatusViewEventHandler>
{
    id <T1StatusViewEventScribeHandler> _scribeHandler;
    T1StatusMediaHandler *_mediaHandler;
    T1StatusTableSlideshowManager *_slideshowManager;
    id <TFNTwitterCardScribeContextProvider> _cardScribeContextProvider;
    TFNDataViewController *_controller;
    NSSet *_usernamelessAllowList;
}

+ (id)cellForEvent:(id)arg1;
+ (id)autoplayContainerCellForEvent:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSSet *usernamelessAllowList; // @synthesize usernamelessAllowList=_usernamelessAllowList;
@property(nonatomic) __weak TFNDataViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) id <TFNTwitterCardScribeContextProvider> cardScribeContextProvider; // @synthesize cardScribeContextProvider=_cardScribeContextProvider;
@property(retain, nonatomic) T1StatusTableSlideshowManager *slideshowManager; // @synthesize slideshowManager=_slideshowManager;
@property(retain, nonatomic) T1StatusMediaHandler *mediaHandler; // @synthesize mediaHandler=_mediaHandler;
@property(nonatomic) __weak id <T1StatusViewEventScribeHandler> scribeHandler; // @synthesize scribeHandler=_scribeHandler;
- (id)scribeContextForObject:(id)arg1 controller:(id)arg2;
- (id)scribeContextForStatusViewEvent:(id)arg1 controller:(id)arg2;
- (id)handleStatusViewEvent:(id)arg1;
- (id)initWithController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

