//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TFSTwitterCore/TFSModel-Protocol.h>

@interface TFSTwitterLiveAuthorizedStreamRestriction : NSObject <TFSModel>
{
    long long _restrictionType;
}

@property(readonly, nonatomic) long long restrictionType; // @synthesize restrictionType=_restrictionType;
- (_Bool)isEqual:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithRestrictionType:(long long)arg1;
- (id)init;

@end

