//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMediaPickerLibraryViewController.h"

@protocol WAMediaPickerAlbumPickerDelegate;

@interface WAMediaPickerAlbumPickerViewController : WAMediaPickerLibraryViewController
{
    _Bool _preparingToPresentAlbum;
    _Bool _libraryAvailable;
    id <WAMediaPickerAlbumPickerDelegate> delegate;
}

+ (id)controller;
@property(nonatomic) __weak id <WAMediaPickerAlbumPickerDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)presentNewAlbumViewController:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;

@end

