//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/GPBMessage.h>

@class NSData, NSString;

@interface WAPBSyncdIndex : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *blob; // @dynamic blob;
@property(nonatomic) _Bool hasBlob; // @dynamic hasBlob;
@property(nonatomic) _Bool hasLegacyStringIndex; // @dynamic hasLegacyStringIndex;
@property(copy, nonatomic) NSString *legacyStringIndex; // @dynamic legacyStringIndex;

@end

