//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>

@class FBMediaFileStreamListenerAnnouncerWrapper, NSURL;

@interface FBMediaUploadFileStream : NSObject <NSCoding>
{
    FBMediaFileStreamListenerAnnouncerWrapper *_fileStreamAnnouncer;
    NSURL *_fileURL;
    struct CGSize _videoSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(readonly, copy, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(readonly, nonatomic) FBMediaFileStreamListenerAnnouncerWrapper *fileStreamAnnouncer; // @synthesize fileStreamAnnouncer=_fileStreamAnnouncer;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFileStreamAnnouncer:(id)arg1 fileURL:(id)arg2;

@end

