//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBTransientAnalysisUtils : NSObject
{
}

+ (_Bool)isConnectionLevelTracingEnabled;
+ (void)disableConnectionLevelTracing;
+ (void)enableConnectionLevelTracing;
+ (long long)getTraceDataPollPeriodMsConfig;
+ (long long)getMaxTraceDurationMsConfig;
+ (void)cacheTraceDataPollPeriodMsConfig:(long long)arg1;
+ (void)cacheMaxTraceDurationMsConfig:(long long)arg1;
+ (unsigned long long)getCurrentSystemTimeMs;
+ (unsigned long long)getMonotonicTimeNowMs;

@end

