//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface IGAPIRequest : NSObject
{
    unsigned long long _method;
    CDUnknownFunctionPointerType _parser;
    NSString *_path;
    NSArray *_queryItems;
}

- (void).cxx_destruct;
- (id)untypedURLRequest;
- (id)startWithNetworker:(id)arg1 policy:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_initWithMethod:(unsigned long long)arg1 parser:(CDUnknownFunctionPointerType)arg2 path:(id)arg3 queryItems:(id)arg4;

@end

