//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IGBloksRichTextComponentLispyLocation : NSObject
{
    long long _URLType;
    long long _index;
}

+ (id)newWithURLType:(long long)arg1 index:(long long)arg2;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) long long URLType; // @synthesize URLType=_URLType;

@end

