//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/IGListBindingSingleSectionController.h>

#import <InstagramAppCoreFramework/IGDirectTypingIndicatorCellDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGListDisplayDelegate-Protocol.h>

@class IGDirectTypingIndicatorViewModel, NSString;
@protocol IGDirectInteropFeatureGating;

@interface IGDirectTypingStatusSectionController : IGListBindingSingleSectionController <IGListDisplayDelegate, IGDirectTypingIndicatorCellDelegate>
{
    id <IGDirectInteropFeatureGating> _featureGating;
    IGDirectTypingIndicatorViewModel *_viewModel;
    _Bool _shouldOptimizeMessageHeaderHeightCalculation;
}

- (void).cxx_destruct;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2;
- (void)typingIndicatorCellDidTapThreadPresenceButton:(id)arg1;
- (void)typingIndicatorCellDidTapAvatar:(id)arg1;
- (struct UIEdgeInsets)inset;
- (void)didUpdateToObject:(id)arg1;
- (struct CGSize)sizeForViewModel:(id)arg1;
- (void)configureCell:(id)arg1 withViewModel:(id)arg2;
- (Class)cellClass;
- (id)initWithFeatureGating:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

