//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/IGValueObject.h>

#import <InstagramAppCoreFramework/IGListDiffable-Protocol.h>
#import <InstagramAppCoreFramework/NSCoding-Protocol.h>
#import <InstagramAppCoreFramework/NSCopying-Protocol.h>

@interface IGDirectInstantReplyMessageViewModel : IGValueObject <IGListDiffable, NSCopying, NSCoding>
{
}

+ (void)initialize;
+ (id)initWithText:(id)arg1 instantReplyTrackingString:(id)arg2 threadTheme:(id)arg3 maximumBubbleCellWidth:(double)arg4 contentStringStylesProvider:(id)arg5 isVertical:(_Bool)arg6 index:(unsigned long long)arg7;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;

@end

