//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCopying-Protocol.h>
#import <FBSharedFramework/NSFastEnumeration-Protocol.h>

@class NSArray, NSDictionary;
@protocol IGDirectUIMessage;

@interface IGDirectUIMessageSet : NSObject <NSFastEnumeration, NSCopying>
{
    NSArray *_sortedMessages;
    NSDictionary *_messagesByServerId;
    NSDictionary *_messagesByClientContext;
    id <IGDirectUIMessage> _newestPublishedMessage;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (_Bool)isEqual:(id)arg1;
- (id)reverseEnumerator;
- (unsigned long long)count;
- (id)messageWithClientContext:(id)arg1;
- (id)messageWithServerId:(id)arg1;
- (id)oldestMessage;
- (id)newestPublishedMessage;
- (id)newestMessage;
- (id)initWithSortedMessages:(id)arg1 messagesByServerId:(id)arg2 messagesByClientContext:(id)arg3 newestPublishedMessage:(id)arg4;

@end

