//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGListDiffable-Protocol.h>
#import <FBSharedFramework/IGSearchableItem-Protocol.h>
#import <FBSharedFramework/IGTagLoggable-Protocol.h>
#import <FBSharedFramework/IGTaggableObject-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class NSString;

@interface IGFBUser : NSObject <NSCopying, IGListDiffable, IGSearchableItem, IGTagLoggable, IGTaggableObject>
{
    _Bool _isInvited;
    NSString *_fbID;
    NSString *_fullName;
    NSString *_profilePictureURL;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isInvited; // @synthesize isInvited=_isInvited;
@property(readonly, copy, nonatomic) NSString *profilePictureURL; // @synthesize profilePictureURL=_profilePictureURL;
@property(readonly, copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(readonly, copy, nonatomic) NSString *fbID; // @synthesize fbID=_fbID;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) unsigned long long hash;
- (id)searchableContent;
- (id)searchID;
- (long long)entityType;
- (id)entityName;
- (id)entityID;
@property(readonly, nonatomic) NSString *pk;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFBID:(id)arg1 fullName:(id)arg2 profilePictureURL:(id)arg3 isInvited:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

