//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGListDiffable-Protocol.h>

@class IGHashtagModel, IGLocation, NSString;

@interface IGFollowListItemViewModel : NSObject <IGListDiffable>
{
    IGHashtagModel *_hashtag;
    IGLocation *_location;
    NSString *_sectionTitle;
    long long _followButtonState;
}

- (void).cxx_destruct;
@property(nonatomic) long long followButtonState; // @synthesize followButtonState=_followButtonState;
@property(readonly, nonatomic) NSString *sectionTitle; // @synthesize sectionTitle=_sectionTitle;
@property(readonly, nonatomic) IGLocation *location; // @synthesize location=_location;
@property(readonly, nonatomic) IGHashtagModel *hashtag; // @synthesize hashtag=_hashtag;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithLocation:(id)arg1 followButtonState:(long long)arg2 sectionTitle:(id)arg3;
- (id)initWithHashtag:(id)arg1 followButtonState:(long long)arg2 sectionTitle:(id)arg3;

@end

