//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class PHAssetCollection;

@protocol IGGalleryAlbumPickerDataSource <NSObject>
@property(readonly, nonatomic) long long numberOfCollections;
- (void)fetchCollectionInfoForCollectionAtIndex:(long long)arg1 thumbnailSize:(struct CGSize)arg2 completion:(void (^)(PHAssetCollection *, UIImage *, long long))arg3;
- (PHAssetCollection *)collectionAtIndex:(long long)arg1;
@end

