//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <InstagramAppCoreFramework/FBIntentTarget-Protocol.h>

@class IGStoryReelCoverInfo, NSArray, NSString;
@protocol IGStoryHighlightsCreationControllerDelegate;

@interface IGHighlightsCreationUserIntentTarget : NSObject <FBIntentTarget>
{
    _Bool _presentedModally;
    long long _creationMode;
    long long _entryPoint;
    NSArray *_items;
    NSString *_reelPK;
    NSString *_title;
    IGStoryReelCoverInfo *_coverInfo;
    id <IGStoryHighlightsCreationControllerDelegate> _delegate;
    long long _reelType;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long reelType; // @synthesize reelType=_reelType;
@property(readonly, nonatomic) _Bool presentedModally; // @synthesize presentedModally=_presentedModally;
@property(readonly, nonatomic) id <IGStoryHighlightsCreationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGStoryReelCoverInfo *coverInfo; // @synthesize coverInfo=_coverInfo;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *reelPK; // @synthesize reelPK=_reelPK;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) long long entryPoint; // @synthesize entryPoint=_entryPoint;
@property(readonly, nonatomic) long long creationMode; // @synthesize creationMode=_creationMode;
- (id)initWithCreationMode:(long long)arg1 entryPoint:(long long)arg2 items:(id)arg3 reelPK:(id)arg4 title:(id)arg5 coverInfo:(id)arg6 delegate:(id)arg7 presentedModally:(_Bool)arg8 reelType:(long long)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

