//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IGUserSession, NSString;

@interface IGMainFeedResponseStore : NSObject
{
    _Bool _hasDeserialized;
    unsigned long long _maxItemCount;
    NSString *_suffix;
    IGUserSession *_userSession;
}

- (void).cxx_destruct;
- (id)_deserializeEntriesAtPath:(id)arg1;
- (void)_archiveToFile:(id)arg1 posts:(id)arg2 nextMaxID:(id)arg3 extras:(id)arg4;
- (void)serializeDataWithPosts:(id)arg1 nextMaxID:(id)arg2 extras:(id)arg3;
- (void)serializeDataWithPosts:(id)arg1 nextMaxID:(id)arg2;
- (id)deserializeData;
- (id)_serializedDataFilePath;
- (id)initWithUserSession:(id)arg1;
- (id)initWithSuffix:(id)arg1 userSession:(id)arg2 maxItemCount:(unsigned long long)arg3;

@end

