//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FBMediaUploadConfig, FBMediaUploadContentSource, IGUploadOffProcessNetworkRequestUserScopedObjects, NSObject, NSString;
@protocol FBMediaUploadJob, FBMediaUploadListener, IGNetworking, IGUserLauncherSetProviding, OS_dispatch_queue;

@protocol IGMediaUploadJobFactory
- (id <FBMediaUploadJob>)newUploadJobWithUserPk:(NSString *)arg1 contentSource:(FBMediaUploadContentSource *)arg2 config:(FBMediaUploadConfig *)arg3 token:(NSString *)arg4 listener:(id <FBMediaUploadListener>)arg5 networkDispatcher:(id <IGNetworking>)arg6 offProcessNetworkRequestUserScopedObjects:(IGUploadOffProcessNetworkRequestUserScopedObjects *)arg7 queue:(NSObject<OS_dispatch_queue> *)arg8 launcherSetProvider:(id <IGUserLauncherSetProviding>)arg9;
@end

