//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InstagramAppCoreFramework/NSCoding-Protocol.h>
#import <InstagramAppCoreFramework/NSObject-Protocol.h>

@class NSString;

@protocol IGMusicBookmarkableAudioAssetProtocol <NSObject, NSCoding>
@property(nonatomic) _Bool isBookmarked;
@property(readonly, copy, nonatomic) NSString *originalAudioAssetId;
@property(readonly, copy, nonatomic) NSString *audioClusterId;
@property(readonly, copy, nonatomic) NSString *audioAssetId;
@end

