//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <InstagramAppCoreFramework/IGRTCBroadcastIntf-Protocol.h>

@class NSString;

@interface IGRTCBroadcastImpl : NSObject <IGRTCBroadcastIntf>
{
}

+ (id)sessionWithUserSession:(id)arg1 config:(CDStruct_886bc7b8)arg2 broadcastId:(id)arg3 remoteCallMessageHandler:(id)arg4 defaultVideoCropMode:(id)arg5 logger:(id)arg6 liveWithDelegate:(id)arg7 liveInfoDelegate:(id)arg8;
+ (id)broadcastSessionFactoryWithUserSession:(id)arg1 broadcastId:(id)arg2 config:(CDStruct_886bc7b8)arg3 logger:(id)arg4 liveWithDelegate:(id)arg5 liveInfoDelegate:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

