//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class IGUser, NSString;

@interface IGShoppingShopHeaderModel : FBValueObject <NSCopying, NSCoding>
{
    IGUser *_merchant;
    NSString *_contextInfo;
}

+ (id)valueWithJSONDictionary:(id)arg1 objectStores:(id)arg2 error:(id *)arg3;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *contextInfo; // @synthesize contextInfo=_contextInfo;
@property(readonly, copy, nonatomic) IGUser *merchant; // @synthesize merchant=_merchant;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithMerchant:(id)arg1 contextInfo:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

