//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <InstagramAppCoreFramework/IGShoppingHomeSectionFetching-Protocol.h>

@class IGObjectStores, NSMutableDictionary, NSString;
@protocol IGAPIClient, IGShoppingHomeSectionFetchServiceDelegate;

@interface IGShoppingHomeSectionFetchService : NSObject <IGShoppingHomeSectionFetching>
{
    NSMutableDictionary *_sectionToFetchTask;
    NSMutableDictionary *_sectionToFetchFailureCount;
    id <IGAPIClient> _networker;
    IGObjectStores *_objectStores;
    CDUnknownBlockType _sectionQueryBlock;
    id <IGShoppingHomeSectionFetchServiceDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGShoppingHomeSectionFetchServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fetchShortcutButtonsSectionWithViewModel:(id)arg1;
- (void)fetchSpotlightTileHScrollSectionWithViewModel:(id)arg1;
- (void)cancelAllSectionRequests;
- (id)fetchStateForSectionWithDataModel:(id)arg1;
- (void)fetchDataForSectionWithDataModel:(id)arg1;
- (void)fetchDataForSectionWithIdentifier:(id)arg1;
- (id)initWithNetworker:(id)arg1 objectStores:(id)arg2 sectionQueryBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

