//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IGMedia, IGSessionTracker, IGShoppingAdMetadata, IGShoppingNavigationAnalyticsContext, IGShoppingProductCollectionProperties, IGUserSession;

@interface IGShoppingMerchantLogger : NSObject
{
    IGUserSession *_userSession;
    IGShoppingProductCollectionProperties *_productCollectionInfo;
    IGMedia *_media;
    IGSessionTracker *_shoppingSessionTracker;
    IGShoppingAdMetadata *_adMetadata;
    IGShoppingNavigationAnalyticsContext *_navigationInfo;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGShoppingNavigationAnalyticsContext *navigationInfo; // @synthesize navigationInfo=_navigationInfo;
@property(readonly, nonatomic) IGShoppingAdMetadata *adMetadata; // @synthesize adMetadata=_adMetadata;
@property(readonly, nonatomic) IGSessionTracker *shoppingSessionTracker; // @synthesize shoppingSessionTracker=_shoppingSessionTracker;
- (void)logContinueShoppingRowTapForMerchantPk:(id)arg1;
- (void)logContinueShoppingRowImpressionForMerchantPk:(id)arg1;
- (id)initWithUserSession:(id)arg1 navigationInfo:(id)arg2 media:(id)arg3 productCollectionInfo:(id)arg4 shoppingSessionTracker:(id)arg5 adMetadata:(id)arg6;

@end

