//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import <InstagramAppCoreFramework/NSCoding-Protocol.h>
#import <InstagramAppCoreFramework/NSCopying-Protocol.h>

@interface IGShoppingContentTileDropsMetadata : FBValueObject <NSCopying, NSCoding>
{
    double _launchDateUnixTimestamp;
}

+ (id)valueWithJSONDictionary:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) double launchDateUnixTimestamp; // @synthesize launchDateUnixTimestamp=_launchDateUnixTimestamp;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithLaunchDateUnixTimestamp:(double)arg1;
- (id)initWithCoder:(id)arg1;

@end

