//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InstagramAppCoreFramework/NSObject-Protocol.h>

@class NSArray;
@protocol IGSlideshowDataSourceDelegate;

@protocol IGSlideshowDataSource <NSObject>
- (long long)endOfFeedMediaIndex;
- (long long)endOfFeedIndex;
- (long long)currentFetchAction;
- (unsigned long long)currentFetchState;
- (void)loadMore;
- (void)reload;
- (NSArray *)loadedItems;
- (_Bool)hasMoreAvailable;
- (void)setDelegate:(id <IGSlideshowDataSourceDelegate>)arg1;
@end

