//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IGTranscoderFrameRequest : NSObject
{
    long long _sampleInterval;
    CDStruct_1b6d18a9 _sampleTime;
}

+ (id)requestWithSampleTime:(CDStruct_1b6d18a9)arg1;
+ (id)requestWithSampleInterval:(long long)arg1;
+ (id)requestNothing;
@property(readonly, nonatomic) CDStruct_1b6d18a9 sampleTime; // @synthesize sampleTime=_sampleTime;
@property(readonly, nonatomic) long long sampleInterval; // @synthesize sampleInterval=_sampleInterval;
- (id)initWithSampleInterval:(long long)arg1 sampleTime:(CDStruct_1b6d18a9)arg2;

@end

