//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC20SlackInstrumentation9Clog_Perf : _TtCs12_SwiftObject
{
    // Error parsing type: , name: elapsed_time
    // Error parsing type: , name: items_count
    // Error parsing type: , name: object_id
    // Error parsing type: , name: messages_count
    // Error parsing type: , name: reactions_count
    // Error parsing type: , name: pins_count
    // Error parsing type: , name: stars_count
    // Error parsing type: , name: experiment_metric
    // Error parsing type: , name: experiment_id
    // Error parsing type: , name: experiment_group
    // Error parsing type: , name: experiment_attributes
    // Error parsing type: , name: error_msg
    // Error parsing type: , name: error_stack_trace
    // Error parsing type: , name: error_file
    // Error parsing type: , name: error_line
    // Error parsing type: , name: api_name
    // Error parsing type: , name: api_method
    // Error parsing type: , name: api_base_url
    // Error parsing type: , name: http_method
    // Error parsing type: , name: http_status_code
    // Error parsing type: , name: api_data
    // Error parsing type: , name: required_sync
    // Error parsing type: , name: session_id
    // Error parsing type: , name: time
    // Error parsing type: , name: build_type_deprecated
    // Error parsing type: , name: app_id
    // Error parsing type: , name: is_tablet
    // Error parsing type: , name: target_channel_id
    // Error parsing type: , name: end_state
    // Error parsing type: , name: hist_frame_render_time_deprecated
    // Error parsing type: , name: hist_janky_windows_deprecated
    // Error parsing type: , name: hist_frame_render_time
    // Error parsing type: , name: hist_janky_windows
    // Error parsing type: , name: duration_ms
    // Error parsing type: , name: sample_filter_deprecated
    // Error parsing type: , name: desktop_elapsed_time
    // Error parsing type: , name: build_type
    // Error parsing type: , name: app_version
    // Error parsing type: , name: app_release
    // Error parsing type: , name: release_version
    // Error parsing type: , name: upgrade
    // Error parsing type: , name: start_type
    // Error parsing type: , name: breadcrumbs
    // Error parsing type: , name: trigger
    // Error parsing type: , name: target_type
    // Error parsing type: , name: sample_filter
    // Error parsing type: , name: logs
    // Error parsing type: , name: wifi
    // Error parsing type: , name: lazy_channels
    // Error parsing type: , name: unique_id
    // Error parsing type: , name: slack_connection_id
    // Error parsing type: , name: raw_error_msg
    // Error parsing type: , name: lazy_user_groups
    // Error parsing type: , name: is_cross_workspace
    // Error parsing type: , name: impression_duration
}

@end

