//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC14MainAppLibrary19PaymentRegTextField.h"

@interface _TtC14MainAppLibrary43PaymentBRRegMerchantPayoutBankTypeTextField : _TtC14MainAppLibrary19PaymentRegTextField
{
    // Error parsing type: , name: pickerValues
    // Error parsing type: , name: picker.storage
    // Error parsing type: , name: type
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)becomeFirstResponder;
- (id)initWithCoder:(id)arg1;

@end

