//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNumber, NSString;

@protocol ACCPhotoUploadParamsProtocol <NSObject>
@property(retain, nonatomic) NSNumber *maxFailTimeEnabled;
@property(retain, nonatomic) NSNumber *maxFailTime;
@property(retain, nonatomic) NSNumber *socketNumber;
@property(retain, nonatomic) NSNumber *rwTimeout;
@property(retain, nonatomic) NSNumber *fileRetryCount;
@property(copy, nonatomic) NSString *authorization;
@property(copy, nonatomic) NSString *imageHostName;
@property(copy, nonatomic) NSString *fileHostName;
@property(copy, nonatomic) NSString *appKey;
@end

