//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HTSService.h"

#import "AWECommerceModuleService-Protocol.h"

@class NSString;

@interface AWECommerceModuleService : HTSService <AWECommerceModuleService>
{
}

- (id)openUniversalLinkAndLandingPageTaskWithContextBuilder:(CDUnknownBlockType)arg1;
- (Class)lightLandingClass;
- (id)newFeedAnchorViewManager;
- (void)uploadCompanyHeaderImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)splashConfig;
- (id)newAdPromptViewManager;
- (double)preferredCompanyChallengeViewControllerHeight;
- (id)newCompanyChallengeViewController;
- (id)newAdWebViewModalManagerWithModel:(id)arg1;
- (void)ironManAdTaskWithParam:(id)arg1;
- (_Bool)openAppWithOpenURL:(id)arg1 creativeID:(id)arg2 groupID:(id)arg3 logExtra:(id)arg4 event:(id)arg5;
- (void)trackEventWithEvent:(id)arg1 label:(id)arg2 logExtra:(id)arg3 creativeID:(id)arg4 groupID:(id)arg5 adExtra:(id)arg6 extra:(id)arg7;
- (void)trackEventWithEvent:(id)arg1 label:(id)arg2 duration:(id)arg3 videoLength:(id)arg4 logExtra:(id)arg5 creativeID:(id)arg6 groupID:(id)arg7;
- (void)openWebViewWithURL:(id)arg1 title:(id)arg2;
- (void)callSmartPhoneWithID:(id)arg1 phoneKey:(id)arg2 number:(id)arg3 positionTag:(id)arg4;
- (id)hotSearchBannerURLList;
- (id)loadHotSearchAdClickView;
- (id)loadMusicListAdView:(id)arg1 categoryName:(id)arg2;
- (void)preloadWebLandingResourcesForAwemes:(id)arg1;
- (void)preloadWebLandingResourcesForAweme:(id)arg1;
- (void)preloadShowcaseWithSchema:(id)arg1;
- (void)cleanLinkAdPublishData;
@property(copy, nonatomic) NSString *linkAdPublishData;
- (void)trackEventWithEvent:(id)arg1 label:(id)arg2 model:(id)arg3 extra:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

