//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

@class NSDictionary, NSNumber, NSString;

@interface AWEEffectPlatformTrackModel : MTLModel
{
    NSString *_trackName;
    NSNumber *_successStatus;
    NSNumber *_failStatus;
    NSNumber *_startTime;
    NSString *_effectIDKey;
    NSString *_effectNameKey;
    NSDictionary *_trackInfoDict;
    CDUnknownBlockType _extraTrackInfoDictBlock;
}

+ (id)modernStickerTrackModel;
@property(copy, nonatomic) CDUnknownBlockType extraTrackInfoDictBlock; // @synthesize extraTrackInfoDictBlock=_extraTrackInfoDictBlock;
@property(copy, nonatomic) NSDictionary *trackInfoDict; // @synthesize trackInfoDict=_trackInfoDict;
@property(copy, nonatomic) NSString *effectNameKey; // @synthesize effectNameKey=_effectNameKey;
@property(copy, nonatomic) NSString *effectIDKey; // @synthesize effectIDKey=_effectIDKey;
@property(copy, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSNumber *failStatus; // @synthesize failStatus=_failStatus;
@property(copy, nonatomic) NSNumber *successStatus; // @synthesize successStatus=_successStatus;
@property(copy, nonatomic) NSString *trackName; // @synthesize trackName=_trackName;
- (void).cxx_destruct;

@end

