//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AWELiveSchemaRegister : NSObject
{
}

+ (void)registerChargeController;
+ (void)registerWalletController;
+ (void)registerUrlsWithHost:(id)arg1 enumerateBlock:(CDUnknownBlockType)arg2;
+ (id)urlsWithHost:(id)arg1;
+ (id)liveSchemes;
+ (void)registerCJPay;
+ (void)registerFeed;
+ (void)registerSign;
+ (void)registerProfile;
+ (void)registerWebView;
+ (void)registerRoom;
+ (void)__awe__codeRunnerRun_28;

@end

