//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AWEBaseApiModel.h"

@class AWEPOIServiceSpuEntryModel, NSArray, NSString;

@interface AWEPOIProductInfoModel : AWEBaseApiModel
{
    _Bool _hotelDetailEntry;
    NSString *_leftTitle;
    NSString *_moreTitle;
    NSString *_moreUrl;
    NSArray *_products;
    unsigned long long _displayStyle;
    NSString *_source;
    NSString *_contactPhoneNo;
    NSString *_supplierId;
    NSArray *_hotelFacilitys;
    AWEPOIServiceSpuEntryModel *_poiCustomerEntry;
}

+ (id)hotelFacilitysJSONTransformer;
+ (id)productsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) AWEPOIServiceSpuEntryModel *poiCustomerEntry; // @synthesize poiCustomerEntry=_poiCustomerEntry;
@property(retain, nonatomic) NSArray *hotelFacilitys; // @synthesize hotelFacilitys=_hotelFacilitys;
@property(nonatomic) _Bool hotelDetailEntry; // @synthesize hotelDetailEntry=_hotelDetailEntry;
@property(copy, nonatomic) NSString *supplierId; // @synthesize supplierId=_supplierId;
@property(copy, nonatomic) NSString *contactPhoneNo; // @synthesize contactPhoneNo=_contactPhoneNo;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(nonatomic) unsigned long long displayStyle; // @synthesize displayStyle=_displayStyle;
@property(retain, nonatomic) NSArray *products; // @synthesize products=_products;
@property(copy, nonatomic) NSString *moreUrl; // @synthesize moreUrl=_moreUrl;
@property(copy, nonatomic) NSString *moreTitle; // @synthesize moreTitle=_moreTitle;
@property(copy, nonatomic) NSString *leftTitle; // @synthesize leftTitle=_leftTitle;
- (void).cxx_destruct;

@end

