//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AWERxProperty.h"

@interface AWERxReadonlyProperty : AWERxProperty
{
    long long _accessCode;
}

@property(nonatomic) long long accessCode; // @synthesize accessCode=_accessCode;
- (void)bind:(id)arg1 initValue:(id)arg2 accessCode:(long long)arg3;
- (void)bind:(id)arg1 accessCode:(long long)arg2;
- (void)setValue:(id)arg1 withContext:(id)arg2 accessCode:(long long)arg3;
- (void)setValue:(id)arg1 accessCode:(long long)arg2;
- (id)initWithValue:(id)arg1 accessCode:(long long)arg2;

@end

