//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AWEVideoCropViewDelegate-Protocol.h"
#import "AWEVideoRangeSliderDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class AVAssetImageGenerator, AWEAnimatedButton, AWEPlaybackView, AWEProgressLoadingView, AWEVideoCropExtraConfigModel, AWEVideoCropView, AWEVideoEditorModel, AWEVideoRangeSlider, NSArray, NSDictionary, NSObject, NSString, NSURL, UIButton, UICollectionView, UIView;
@protocol OS_dispatch_queue;

@interface AWEVideoCropViewController : UIViewController <AWEVideoCropViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource, AWEVideoRangeSliderDelegate>
{
    _Bool _initialContentOffsetSet;
    _Bool _hasOverEndTime;
    CDUnknownBlockType _completion;
    UIView *_bottomView;
    UICollectionView *_cropCollectionView;
    UIView *_bottomToolContainerView;
    UIView *_timeClipView;
    UICollectionView *_timeClipCollectionView;
    AWEVideoRangeSlider *_videoRangeSlider;
    UIView *_playerContainerView;
    AWEPlaybackView *_playbackView;
    AWEVideoCropView *_cropView;
    NSArray *_cropModeNameArray;
    NSArray *_cropModeImageNameArray;
    NSArray *_highLightCropModeImageNameArray;
    NSDictionary *_modeToIndexDict;
    NSDictionary *_indexToModeDict;
    long long _rotateFactor;
    UIView *_belowRotateButtonView;
    double _cropViewWidthAndHeightScale;
    AWEVideoEditorModel *_assetModel;
    double _duration;
    double _durationRate;
    double _maxDuration;
    unsigned long long _thumbCount;
    NSObject<OS_dispatch_queue> *_imageGeneratorQueue;
    AVAssetImageGenerator *_imageGenerator;
    NSArray *_thumbnailImageArray;
    UIButton *_buttonBack;
    NSArray *_observers;
    double _initialContentOffset;
    AWEAnimatedButton *_clipVideoButton;
    AWEVideoCropExtraConfigModel *_extraConfigModel;
    NSURL *_sourceUrl;
    UIButton *_completeButton;
    AWEProgressLoadingView *_loadingView;
    id _avPlayerPeriodicObserver;
    struct CGSize _normalItemSize;
    struct CGRect _sourceMediaRect;
}

@property(nonatomic) _Bool hasOverEndTime; // @synthesize hasOverEndTime=_hasOverEndTime;
@property(retain, nonatomic) id avPlayerPeriodicObserver; // @synthesize avPlayerPeriodicObserver=_avPlayerPeriodicObserver;
@property(nonatomic) struct CGRect sourceMediaRect; // @synthesize sourceMediaRect=_sourceMediaRect;
@property(retain, nonatomic) AWEProgressLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIButton *completeButton; // @synthesize completeButton=_completeButton;
@property(retain, nonatomic) NSURL *sourceUrl; // @synthesize sourceUrl=_sourceUrl;
@property(retain, nonatomic) AWEVideoCropExtraConfigModel *extraConfigModel; // @synthesize extraConfigModel=_extraConfigModel;
@property(retain, nonatomic) AWEAnimatedButton *clipVideoButton; // @synthesize clipVideoButton=_clipVideoButton;
@property(nonatomic) _Bool initialContentOffsetSet; // @synthesize initialContentOffsetSet=_initialContentOffsetSet;
@property(nonatomic) double initialContentOffset; // @synthesize initialContentOffset=_initialContentOffset;
@property(retain, nonatomic) NSArray *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) UIButton *buttonBack; // @synthesize buttonBack=_buttonBack;
@property(retain, nonatomic) NSArray *thumbnailImageArray; // @synthesize thumbnailImageArray=_thumbnailImageArray;
@property(retain, nonatomic) AVAssetImageGenerator *imageGenerator; // @synthesize imageGenerator=_imageGenerator;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *imageGeneratorQueue; // @synthesize imageGeneratorQueue=_imageGeneratorQueue;
@property(nonatomic) unsigned long long thumbCount; // @synthesize thumbCount=_thumbCount;
@property(nonatomic) struct CGSize normalItemSize; // @synthesize normalItemSize=_normalItemSize;
@property(nonatomic) double maxDuration; // @synthesize maxDuration=_maxDuration;
@property(nonatomic) double durationRate; // @synthesize durationRate=_durationRate;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) AWEVideoEditorModel *assetModel; // @synthesize assetModel=_assetModel;
@property(nonatomic) double cropViewWidthAndHeightScale; // @synthesize cropViewWidthAndHeightScale=_cropViewWidthAndHeightScale;
@property(retain, nonatomic) UIView *belowRotateButtonView; // @synthesize belowRotateButtonView=_belowRotateButtonView;
@property(nonatomic) long long rotateFactor; // @synthesize rotateFactor=_rotateFactor;
@property(retain, nonatomic) NSDictionary *indexToModeDict; // @synthesize indexToModeDict=_indexToModeDict;
@property(retain, nonatomic) NSDictionary *modeToIndexDict; // @synthesize modeToIndexDict=_modeToIndexDict;
@property(retain, nonatomic) NSArray *highLightCropModeImageNameArray; // @synthesize highLightCropModeImageNameArray=_highLightCropModeImageNameArray;
@property(retain, nonatomic) NSArray *cropModeImageNameArray; // @synthesize cropModeImageNameArray=_cropModeImageNameArray;
@property(retain, nonatomic) NSArray *cropModeNameArray; // @synthesize cropModeNameArray=_cropModeNameArray;
@property(retain, nonatomic) AWEVideoCropView *cropView; // @synthesize cropView=_cropView;
@property(retain, nonatomic) AWEPlaybackView *playbackView; // @synthesize playbackView=_playbackView;
@property(retain, nonatomic) UIView *playerContainerView; // @synthesize playerContainerView=_playerContainerView;
@property(retain, nonatomic) AWEVideoRangeSlider *videoRangeSlider; // @synthesize videoRangeSlider=_videoRangeSlider;
@property(retain, nonatomic) UICollectionView *timeClipCollectionView; // @synthesize timeClipCollectionView=_timeClipCollectionView;
@property(retain, nonatomic) UIView *timeClipView; // @synthesize timeClipView=_timeClipView;
@property(retain, nonatomic) UIView *bottomToolContainerView; // @synthesize bottomToolContainerView=_bottomToolContainerView;
@property(retain, nonatomic) UICollectionView *cropCollectionView; // @synthesize cropCollectionView=_cropCollectionView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (void)updateVideoIndicatorWithTime:(CDStruct_1b6d18a9)arg1;
- (void)removeAvPlayerObserver;
- (void)addAvPlayerPeriodicObserver;
- (void)addNotificationObservers;
- (void)handleGif;
- (void)videoToGifWithConfig:(id)arg1;
- (void)clickRotateButton:(id)arg1;
- (void)updateCropViewWithRotateFactor;
- (void)clickSaveButton;
- (void)backToTimeClipWithCropRect:(struct CGRect)arg1;
- (void)clickCancelButton;
- (void)clickCropAndRotateButton;
- (void)clickBackButton;
- (void)clickNextButton;
- (id)p_maskLayerForRect:(struct CGRect)arg1;
- (unsigned long long)actualShowCropMode:(unsigned long long)arg1;
- (_Bool)isHorizontalDirection;
- (double)getScaleBasedOnRotateFactor:(long long)arg1 oldRect:(struct CGRect)arg2 newRect:(struct CGRect)arg3;
- (struct CGAffineTransform)getTransformBasedOnRotateFactor;
- (struct CGRect)mediaSmallMediaContainerFrameForImageWidth:(double)arg1 height:(double)arg2;
- (void)videoCropViewTouchEnded;
- (void)videoCropViewTouchBegin;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)getImagesWithAsset:(id)arg1 atTimes:(id)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)updateThumbnail;
- (void)videoRangeDidChangByPosition:(double)arg1 movedType:(unsigned long long)arg2;
- (void)videoRangeDidEndByType:(unsigned long long)arg1;
- (void)videoRangeDidBeginByType:(unsigned long long)arg1;
- (_Bool)videoRangeIgnoreGesture;
- (double)getPostionFromPlaybackTime:(double)arg1;
- (double)getPlaybackTimeFromPosition:(double)arg1;
- (void)moviePlay;
- (void)moviePause;
- (unsigned long long)preferredScreenEdgesDeferringSystemGestures;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithVideoURL:(id)arg1;
- (id)initWithVideoURL:(id)arg1 extraConfigModel:(id)arg2;
- (double)baseSpeed;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

