//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, UIView;

@protocol HTSLiveToolbarTip
@property(nonatomic) _Bool shouldHideWithTabSpace;
- (void)showTip:(NSString *)arg1 withTipColorString:(NSString *)arg2 inView:(UIView *)arg3 atTopOf:(UIView *)arg4;
- (void)showView:(UIView *)arg1 inView:(UIView *)arg2 atTopOf:(UIView *)arg3 completionHandler:(void (^)(void))arg4;
- (void)showTip:(NSString *)arg1 inView:(UIView *)arg2 atBottomOf:(UIView *)arg3;
- (void)showTip:(NSString *)arg1 inView:(UIView *)arg2 atTopOf:(UIView *)arg3;
- (void)showTip:(NSString *)arg1 inView:(UIView *)arg2;
- (void)hide;
@end

