//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LiveRoomModel, NSIndexPath, NSString, UICollectionView;
@protocol IESLiveDislikeServiceDelegate;

@protocol IESLiveDislikeService <NSObject>
@property(nonatomic) __weak id <IESLiveDislikeServiceDelegate> delegate;
@property(readonly, nonatomic) __weak UICollectionView *collectionView;
@property(retain, nonatomic) NSString *actionType;
@property(retain, nonatomic) NSString *sourceModule;
@property(retain, nonatomic) NSString *eventModule;
@property(retain, nonatomic) NSString *enterFrom;
- (void)handleDislkieRoom:(LiveRoomModel *)arg1 indexPath:(NSIndexPath *)arg2 enterFrom:(NSString *)arg3 enterMethod:(NSString *)arg4;
- (void)hiddenMaskView;
- (id)initWithCollectionView:(UICollectionView *)arg1;
@end

