//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface KOStoryLinkInfo : NSObject
{
    NSString *_url;
    NSString *_requestedUrl;
    NSString *_host;
    NSString *_title;
    NSArray *_image;
    NSString *_desc;
    NSString *_section;
    NSString *_type;
}

@property(readonly, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *section; // @synthesize section=_section;
@property(readonly, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(readonly, nonatomic) NSArray *image; // @synthesize image=_image;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *host; // @synthesize host=_host;
@property(readonly, nonatomic) NSString *requestedUrl; // @synthesize requestedUrl=_requestedUrl;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)description;
- (id)initWithUrl:(id)arg1 requestedUrl:(id)arg2 host:(id)arg3 title:(id)arg4 image:(id)arg5 desc:(id)arg6 section:(id)arg7 type:(id)arg8;

@end

