//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LynxComponent.h"

@class LynxAnimationManager, LynxBackgroundManager, LynxBoxShadowManager, LynxLayoutAnimationManager, LynxUIContext, NSDictionary, NSString, UIView;

@interface LynxUI : LynxComponent
{
    int _displaySentinel;
    UIView *_view;
    LynxUIContext *_context;
    LynxBoxShadowManager *_shadowManager;
    long long _sign;
    NSString *_name;
    LynxBackgroundManager *_backgroundManager;
    LynxAnimationManager *_animationManager;
    NSDictionary *_eventSet;
    LynxLayoutAnimationManager *_layoutAnimationManager;
    struct CGRect _frame;
    struct UIEdgeInsets _padding;
    struct UIEdgeInsets _border;
}

+ (id)__lynx_prop_config__65243;
+ (id)__lynx_prop_config__64442;
+ (id)__lynx_prop_config__63641;
+ (id)__lynx_prop_config__62440;
+ (id)__lynx_prop_config__61639;
+ (id)__lynx_prop_config__60838;
+ (id)__lynx_prop_config__60037;
+ (id)__lynx_prop_config__58836;
+ (id)__lynx_prop_config__58035;
+ (id)__lynx_prop_config__57234;
+ (id)__lynx_prop_config__56433;
+ (id)__lynx_prop_config__55232;
+ (id)__lynx_prop_config__45631;
+ (id)__lynx_prop_config__44930;
+ (id)__lynx_prop_config__44029;
+ (id)__lynx_prop_config__43028;
+ (id)__lynx_prop_config__42327;
+ (id)__lynx_prop_config__41626;
+ (id)__lynx_prop_config__40925;
+ (id)__lynx_prop_config__40224;
+ (id)__lynx_prop_config__39223;
+ (id)__lynx_prop_config__38322;
+ (id)__lynx_prop_config__37421;
+ (id)__lynx_prop_config__36520;
+ (id)__lynx_prop_config__35619;
+ (id)__lynx_prop_config__34718;
+ (id)__lynx_prop_config__33817;
+ (id)__lynx_prop_config__32916;
+ (id)__lynx_prop_config__32015;
+ (id)__lynx_prop_config__31114;
+ (id)__lynx_prop_config__30213;
+ (id)__lynx_prop_config__29112;
+ (id)__lynx_prop_config__28111;
+ (id)__lynx_prop_config__27110;
+ (id)__lynx_prop_config__2619;
+ (id)__lynx_prop_config__2518;
+ (id)__lynx_prop_config__2417;
+ (id)__lynx_prop_config__2316;
+ (id)__lynx_prop_config__2225;
+ (id)__lynx_prop_config__2134;
+ (id)__lynx_prop_config__2033;
+ (id)__lynx_prop_config__1902;
+ (id)__lynx_prop_config__1791;
+ (id)__lynx_prop_config__1710;
+ (id)displayQueue;
+ (void)drawRect:(struct CGRect)arg1 withParameters:(id)arg2;
@property(readonly, nonatomic) LynxLayoutAnimationManager *layoutAnimationManager; // @synthesize layoutAnimationManager=_layoutAnimationManager;
@property(readonly, nonatomic) NSDictionary *eventSet; // @synthesize eventSet=_eventSet;
@property(readonly, nonatomic) LynxAnimationManager *animationManager; // @synthesize animationManager=_animationManager;
@property(readonly, nonatomic) LynxBackgroundManager *backgroundManager; // @synthesize backgroundManager=_backgroundManager;
@property(readonly, nonatomic) struct UIEdgeInsets border; // @synthesize border=_border;
@property(readonly, nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) __weak LynxUIContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long sign; // @synthesize sign=_sign;
- (void).cxx_destruct;
- (void)setLayoutAnimationDeleteAnimationType:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationDeleteProperty:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationDeleteDelay:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationDeleteDuration:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationUpdateAnimationType:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationUpdateProperty:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationUpdateDelay:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationUpdateDuration:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationCreateAnimationType:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationCreateProperty:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationCreateDelay:(id)arg1 requestReset:(_Bool)arg2;
- (void)setLayoutAnimationCreateDuration:(id)arg1 requestReset:(_Bool)arg2;
- (id)lazyGetDeleteAnimation;
- (id)lazyGetUpdateAnimation;
- (id)lazyGetCreateAnimation;
- (void)updateFrameWithLayoutAnimation:(struct CGRect)arg1 withPadding:(struct UIEdgeInsets)arg2 border:(struct UIEdgeInsets)arg3;
- (id)shadowManager;
- (void)setImplicitAnimation:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBoxShadow:(id)arg1 requestReset:(_Bool)arg2;
- (void)setName:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBorderStyle:(long long)arg1 requestReset:(_Bool)arg2;
- (void)setBorderRightColor:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBorderBottomColor:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBorderLeftColor:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBorderTopColor:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBorderColor:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBorderRightWidth:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderBottomWidth:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderLeftWidth:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderTopWidth:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderWidth:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderBottomRightRadius:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderTopRightRadius:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderBottomLeftRadius:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderTopLeftRadius:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBorderRadius:(double)arg1 requestReset:(_Bool)arg2;
- (void)setOpacity:(double)arg1 requestReset:(_Bool)arg2;
- (void)setBackgroudColor:(id)arg1 requestReset:(_Bool)arg2;
- (void)setBackground:(id)arg1 requestReset:(_Bool)arg2;
- (void)setTransform:(struct CATransform3D)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationPlayState:(unsigned long long)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationFillMode:(id)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationDirection:(unsigned long long)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationIterationCount:(id)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationDelay:(id)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationTimingFunction:(id)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationDuration:(id)arg1 requestReset:(_Bool)arg2;
- (void)setAnimationName:(id)arg1 requestReset:(_Bool)arg2;
- (void)setAnimation:(id)arg1 requestReset:(_Bool)arg2;
- (void)eventDidSet;
- (void)setRawEvents:(id)arg1;
- (_Bool)hasCustomLayout;
- (void)layoutDidFinished;
- (void)onReceiveUIOperation:(id)arg1;
- (void)willMoveToSuperComponent:(id)arg1;
- (void)willRemoveComponent:(id)arg1;
- (void)super_insertChild:(id)arg1 atIndex:(long long)arg2;
- (void)insertChild:(id)arg1 atIndex:(long long)arg2;
- (void)borderRadiiDidChange;
- (void)frameDidChange;
- (void)willMoveToWindow:(id)arg1;
- (void)propsDidUpdate;
- (void)updateFrameWithoutLayoutAnimation:(struct CGRect)arg1 withPadding:(struct UIEdgeInsets)arg2 border:(struct UIEdgeInsets)arg3;
- (void)updateFrame:(struct CGRect)arg1 withPadding:(struct UIEdgeInsets)arg2 border:(struct UIEdgeInsets)arg3 withLayoutAnimation:(_Bool)arg4;
@property(readonly, nonatomic) struct CGPoint contentOffset;
- (void)dispatchMoveToWindow:(id)arg1;
- (id)createView;
- (id)view;
- (id)initWithView:(id)arg1;
- (id)init;
- (void)displayAsynchronously;
- (id)drawParameter;

@end

