//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NHAccountPlatformProtocol-Protocol.h"

@class NSString;

@interface NHAccountPlatformApple : NSObject <NHAccountPlatformProtocol>
{
    NSString *_userId;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)requestBind:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2 cancel:(CDUnknownBlockType)arg3;
- (void)requestLogin:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2 cancel:(CDUnknownBlockType)arg3;
- (void)requestAccessToken:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2 cancel:(CDUnknownBlockType)arg3;
- (void)OAuth:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2 cancel:(CDUnknownBlockType)arg3;
- (void)showContinuePage:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)getCurrentAppleUserId;
- (_Bool)isSSOAvailable;
- (void)registerApp:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

