//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NHAccountUserExtraValueConfig : NSObject
{
    CDUnknownBlockType _validateBlock;
    CDUnknownBlockType _extraValueErrorParser;
    CDUnknownBlockType _customUserValueParser;
    CDUnknownBlockType _singleToMultiMigrationBlock;
    CDUnknownBlockType _multiToSingleMigrationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType multiToSingleMigrationBlock; // @synthesize multiToSingleMigrationBlock=_multiToSingleMigrationBlock;
@property(copy, nonatomic) CDUnknownBlockType singleToMultiMigrationBlock; // @synthesize singleToMultiMigrationBlock=_singleToMultiMigrationBlock;
@property(copy, nonatomic) CDUnknownBlockType customUserValueParser; // @synthesize customUserValueParser=_customUserValueParser;
@property(copy, nonatomic) CDUnknownBlockType extraValueErrorParser; // @synthesize extraValueErrorParser=_extraValueErrorParser;
@property(copy, nonatomic) CDUnknownBlockType validateBlock; // @synthesize validateBlock=_validateBlock;
- (void).cxx_destruct;

@end

