//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ZegoLiveRoom/VideoProcessFilter.h>

@interface VideoProcessBilateralFilter : VideoProcessFilter
{
    int m_nWidthOffsetUniform;
    int m_nHeightOffsetUniform;
    int m_nDistanceNormalizationFactorUniform;
    float step_;
    float distance_normalization_factor_;
}

- (void)setColorDistanceFactor:(float)arg1;
- (void)setSampleStep:(float)arg1;
- (void)setUniforms:(int)arg1;
- (void)initUniforms:(unsigned int)arg1;
- (id)init;

@end

