//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC4Hulu24LiveTabBarViewController : UIViewController
{
    // Error parsing type: , name: entityActionDelegate
    // Error parsing type: , name: goLiveGuideModel
    // Error parsing type: , name: pageInstanceId
    // Error parsing type: , name: currentPlayerController
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) long long preferredStatusBarStyle;

@end

