//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Module_Framework/GPBMessage.h>

@class NSData, NSString;

@interface YTIHeartbeatParams : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *drmSessionId; // @dynamic drmSessionId;
@property(nonatomic) _Bool hasDrmSessionId; // @dynamic hasDrmSessionId;
@property(nonatomic) _Bool hasHeartbeatServerData; // @dynamic hasHeartbeatServerData;
@property(nonatomic) _Bool hasHeartbeatToken; // @dynamic hasHeartbeatToken;
@property(nonatomic) _Bool hasIntervalMilliseconds; // @dynamic hasIntervalMilliseconds;
@property(nonatomic) _Bool hasMaxRetries; // @dynamic hasMaxRetries;
@property(nonatomic) _Bool hasSoftFailOnError; // @dynamic hasSoftFailOnError;
@property(nonatomic) _Bool hasUseInnertubeHeartbeatsForDrm; // @dynamic hasUseInnertubeHeartbeatsForDrm;
@property(copy, nonatomic) NSData *heartbeatServerData; // @dynamic heartbeatServerData;
@property(copy, nonatomic) NSString *heartbeatToken; // @dynamic heartbeatToken;
@property(nonatomic) long long intervalMilliseconds; // @dynamic intervalMilliseconds;
@property(nonatomic) long long maxRetries; // @dynamic maxRetries;
@property(nonatomic) _Bool softFailOnError; // @dynamic softFailOnError;
@property(nonatomic) _Bool useInnertubeHeartbeatsForDrm; // @dynamic useInnertubeHeartbeatsForDrm;

@end

