//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Module_Framework/NSObject-Protocol.h>

@class GPBMessage, NSData, NSObject, UIView, YTIInteractionLoggingClientData, YTIVisualElement;
@protocol YTGraftingViewController, YTInteractionLoggingButtonProtocol, YTResponder;

@protocol YTInteractionLoggingActions <NSObject>
- (void)sendStateChangedForButton:(id <YTInteractionLoggingButtonProtocol>)arg1 clientData:(YTIInteractionLoggingClientData *)arg2;
- (_Bool)interactionLogging_isEnabled;
- (void)interactionLogging_relogNewScreenAndAttaches;
- (void)logVisibilityUpdateForClientView:(UIView *)arg1 parentResponder:(NSObject<YTResponder> *)arg2;
- (void)setInteractionLoggingSearchButton:(id <YTInteractionLoggingButtonProtocol>)arg1;
- (id <YTInteractionLoggingButtonProtocol>)interactionLoggingSearchButton;
- (void)interactionLogging_returnFromBackButtonWithPreviousViewController:(id <YTGraftingViewController>)arg1;
- (void)interactionLogging_attachBackButton;
- (void)sendClickWithVisualElement:(YTIVisualElement *)arg1 clientData:(YTIInteractionLoggingClientData *)arg2;
- (void)sendClickForRenderer:(id)arg1 clientData:(YTIInteractionLoggingClientData *)arg2 gestureType:(int)arg3;
- (void)sendClickForRenderer:(id)arg1 clientData:(YTIInteractionLoggingClientData *)arg2;
- (void)sendClickForRenderer:(id)arg1;
- (void)updateVisibilityForRenderer:(id)arg1 eventType:(int)arg2;
- (void)sendClickForButton:(id <YTInteractionLoggingButtonProtocol>)arg1 gestureType:(int)arg2;
- (void)sendClickForButton:(id <YTInteractionLoggingButtonProtocol>)arg1;
- (void)updateVisibilityForButton:(id <YTInteractionLoggingButtonProtocol>)arg1 eventType:(int)arg2;
- (void)attachButton:(id <YTInteractionLoggingButtonProtocol>)arg1 withParentButton:(id <YTInteractionLoggingButtonProtocol>)arg2;
- (void)attachButton:(id <YTInteractionLoggingButtonProtocol>)arg1;
- (void)attachButtonAndUpdateVisibility:(id <YTInteractionLoggingButtonProtocol>)arg1;
- (void)interactionLoggingEndScreen;
- (void)interactionLoggingNewRootScreen;
- (void)interactionLoggingNewScreen;
- (void)attachTrackingParams:(NSData *)arg1;
- (void)attachResponse:(GPBMessage *)arg1 withParentResponse:(GPBMessage *)arg2;
- (void)attachResponse:(GPBMessage *)arg1;
- (void)enableInteractionLogging;
@end

