//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@protocol YTShortsTrimViewModel <NSObject, NSCopying>
@property(readonly, nonatomic) _Bool isPlaybackButtonPlaying;
@property(readonly, nonatomic) _Bool isShortsTrimToggled;
@property(readonly, nonatomic) _Bool displayPlayPauseOverlay;
@property(readonly, nonatomic) _Bool displayScrubber;
@property(readonly, nonatomic) _Bool displayTrimTool;
@property(readonly, nonatomic) _Bool displayTrimToggle;
@end

