//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBTimestamp, NSString;

@interface APPSWALDOCalendarBusy : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *eventSummary; // @dynamic eventSummary;
@property(nonatomic) _Bool hasNextAvailable; // @dynamic hasNextAvailable;
@property(nonatomic) _Bool hasOccupiedUntil; // @dynamic hasOccupiedUntil;
@property(retain, nonatomic) GPBTimestamp *nextAvailable; // @dynamic nextAvailable;
@property(retain, nonatomic) GPBTimestamp *occupiedUntil; // @dynamic occupiedUntil;

@end

