//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ASTAPIClientOp, NSArray, NSString;

@protocol ASTCCLClientOp <NSObject>
@property(readonly, nonatomic) NSArray *supportedClientOps;
- (void)performClientOperation:(ASTAPIClientOp *)arg1 interationID:(int)arg2 deviceSpecificRendering:(NSString *)arg3 statusCallback:(void (^)(int))arg4;

@optional
- (NSArray *)allPossibleSupportedClientOps;
@end

