//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class CDRBadge, CDRMultipleLineDisplayText, CDRSubstitutePricingInformation, LOGGsxVEData, NSString;

@interface CDRCompetitiveOffer : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *effectivePrice; // @dynamic effectivePrice;
@property(nonatomic) _Bool hasEffectivePrice; // @dynamic hasEffectivePrice;
@property(nonatomic) _Bool hasLinkedPageEri; // @dynamic hasLinkedPageEri;
@property(nonatomic) _Bool hasMerchantBadge; // @dynamic hasMerchantBadge;
@property(nonatomic) _Bool hasMerchantLogoURL; // @dynamic hasMerchantLogoURL;
@property(nonatomic) _Bool hasMerchantName; // @dynamic hasMerchantName;
@property(nonatomic) _Bool hasMultipleLineShippingInformation; // @dynamic hasMultipleLineShippingInformation;
@property(nonatomic) _Bool hasOriginalPrice; // @dynamic hasOriginalPrice;
@property(nonatomic) _Bool hasShippingInformation; // @dynamic hasShippingInformation;
@property(nonatomic) _Bool hasShowSubstitutePrice; // @dynamic hasShowSubstitutePrice;
@property(nonatomic) _Bool hasSubstitutePricingInformation; // @dynamic hasSubstitutePricingInformation;
@property(nonatomic) _Bool hasVeMetadata; // @dynamic hasVeMetadata;
@property(copy, nonatomic) NSString *linkedPageEri; // @dynamic linkedPageEri;
@property(retain, nonatomic) CDRBadge *merchantBadge; // @dynamic merchantBadge;
@property(copy, nonatomic) NSString *merchantLogoURL; // @dynamic merchantLogoURL;
@property(copy, nonatomic) NSString *merchantName; // @dynamic merchantName;
@property(retain, nonatomic) CDRMultipleLineDisplayText *multipleLineShippingInformation; // @dynamic multipleLineShippingInformation;
@property(copy, nonatomic) NSString *originalPrice; // @dynamic originalPrice;
@property(copy, nonatomic) NSString *shippingInformation; // @dynamic shippingInformation;
@property(nonatomic) _Bool showSubstitutePrice; // @dynamic showSubstitutePrice;
@property(retain, nonatomic) CDRSubstitutePricingInformation *substitutePricingInformation; // @dynamic substitutePricingInformation;
@property(retain, nonatomic) LOGGsxVEData *veMetadata; // @dynamic veMetadata;

@end

