//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class CDRShoppingListMetadata, CDRToastMessage, NSMutableArray, NSString;

@interface CDRCreateShoppingListScreenResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *collaboratorArray; // @dynamic collaboratorArray;
@property(readonly, nonatomic) unsigned long long collaboratorArray_Count; // @dynamic collaboratorArray_Count;
@property(nonatomic) _Bool hasListId; // @dynamic hasListId;
@property(nonatomic) _Bool hasListMetadata; // @dynamic hasListMetadata;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(nonatomic) _Bool hasToastMessage; // @dynamic hasToastMessage;
@property(retain, nonatomic) NSMutableArray *itemArray; // @dynamic itemArray;
@property(readonly, nonatomic) unsigned long long itemArray_Count; // @dynamic itemArray_Count;
@property(copy, nonatomic) NSString *listId; // @dynamic listId;
@property(retain, nonatomic) CDRShoppingListMetadata *listMetadata; // @dynamic listMetadata;
@property(copy, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) CDRToastMessage *toastMessage; // @dynamic toastMessage;

@end

