//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, SetupCastDevice;

@protocol LinkedDevicesManager
- (void)linkCastDevice:(SetupCastDevice *)arg1 completion:(void (^)(NSError *))arg2;
- (void)requestLinkedUsersForDeviceID:(NSString *)arg1 completion:(void (^)(NSArray *, NSError *))arg2;
- (void)requestLinkedDevicesWithCompletion:(void (^)(NSArray *, NSError *))arg1;
@end

