//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPAC2FlippyCarouselView.h"

#import "OPAC2ComponentTransformerClass-Protocol.h"
#import "OPAC2EventHandler-Protocol.h"

@interface OPAC2ItemSelectionCarouselView : OPAC2FlippyCarouselView <OPAC2ComponentTransformerClass, OPAC2EventHandler>
{
}

+ (Class)targetMessageClass;
+ (id)targetExtension;
+ (id)targetTypeString;
- (_Bool)handleEvent:(id)arg1 fromSource:(id)arg2;
- (void)hideAllPagesExceptIndex:(long long)arg1;
- (long long)findPageIndexForSubview:(id)arg1;
- (id)initWithMessage:(id)arg1 andContext:(id)arg2 fromFactory:(id)arg3;

@end

