//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class OpenUserIntent;

@protocol OpenUserIntentHandling <NSObject>
- (void)resolveUsernameForOpenUser:(OpenUserIntent *)arg1 withCompletion:(void (^)(INStringResolutionResult *))arg2;
- (void)handleOpenUser:(OpenUserIntent *)arg1 completion:(void (^)(OpenUserIntentResponse *))arg2;

@optional
- (void)confirmOpenUser:(OpenUserIntent *)arg1 completion:(void (^)(OpenUserIntentResponse *))arg2;
@end

