//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFreeTierPlaylistCellProviderDelegate-Protocol.h"

@class NSString;
@protocol SPTFreeTierPlaylistCellProviderDelegate;

@interface SPTFreeTierPlaylistCellProviderDelegateWrapper : NSObject <SPTFreeTierPlaylistCellProviderDelegate>
{
    id <SPTFreeTierPlaylistCellProviderDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SPTFreeTierPlaylistCellProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (id)itemForIndexPath:(id)arg1;
- (void)reloadCellsForCellProvider:(id)arg1;
- (void)contextMenuPressedForCellProvider:(id)arg1 sender:(id)arg2;
- (void)cellProvider:(id)arg1 playTrackAtIndexPath:(id)arg2 interactionId:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

