//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMIModuleViewControllerFactory.h"

@interface AMIModuleDefaultViewControllerFactory : AMIModuleViewControllerFactory
{
    long long _preferredPresentationStyle;
    CDUnknownBlockType _createViewControllerBlock;
}

+ (id)factoryWithCreateViewController:(CDUnknownBlockType)arg1 preferredPresentationStyle:(long long)arg2;
+ (id)factoryWithCreateViewController:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType createViewControllerBlock; // @synthesize createViewControllerBlock=_createViewControllerBlock;
@property(nonatomic) long long preferredPresentationStyle; // @synthesize preferredPresentationStyle=_preferredPresentationStyle;
- (void).cxx_destruct;
- (id)viewController;
- (id)initWithCreateViewController:(CDUnknownBlockType)arg1 preferredPresentationStyle:(long long)arg2;
- (id)initWithCreateViewController:(CDUnknownBlockType)arg1;

@end

