//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class APSSsnapUIController;

@interface APSSsnapViewController : UIViewController
{
    APSSsnapUIController *_uiController;
}

@property(retain, nonatomic) APSSsnapUIController *uiController; // @synthesize uiController=_uiController;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithChild:(id)arg1 withUIController:(id)arg2;

@end

