//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CIPConfigListener-Protocol.h"
#import "RDCMenuItemOverride-Protocol.h"

@class CIPAppDataProvider, CIPMenuIngressConfig, NSString;
@protocol RDCMenuDataService;

@interface CIPIngressNavMenuOverride : NSObject <CIPConfigListener, RDCMenuItemOverride>
{
    CIPMenuIngressConfig *_config;
    NSString *_menuGroup;
    id <RDCMenuDataService> _rdcMenuService;
    CIPAppDataProvider *_dataProvider;
}

@property(retain, nonatomic) CIPAppDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(retain, nonatomic) id <RDCMenuDataService> rdcMenuService; // @synthesize rdcMenuService=_rdcMenuService;
@property(readonly, nonatomic) NSString *menuGroup; // @synthesize menuGroup=_menuGroup;
@property(retain) CIPMenuIngressConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)onConfigChange:(id)arg1;
@property(readonly) _Bool visible;
- (id)overrideUri:(id)arg1;
- (unsigned long long)overrideVisibility:(unsigned long long)arg1;
- (id)overrideText:(id)arg1;
- (id)initWithContext:(id)arg1 menuGroup:(id)arg2 dataProvider:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

