//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UICDevice : NSObject
{
}

+ (_Bool)isForceTouchAvailable;
+ (_Bool)isRightToLeft;
+ (_Bool)isPortrait;
+ (_Bool)isLandscape;
+ (long long)orientation;
+ (double)pointSize;
+ (_Bool)isRetina;
+ (_Bool)isIPad;
+ (_Bool)isIPhone;
+ (_Bool)isPreIOS9;
+ (_Bool)isPreIOS8;
+ (_Bool)isIOS7;

@end

