//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NFUICollectionViewCellManager, NSArray, NSIndexPath, NSString, NavigationBarAppearanceManager, UIView;
@protocol NFUIManagedCollectionViewControllerDelegate><NFUICollectionViewCellManagerDelegate><NFUICellSelectionProtocol;

@protocol NFUIManagedCollectionViewControllerProtocol <NSObject>
@property(copy, nonatomic) CDUnknownBlockType vmBlock;
@property(copy, nonatomic) CDUnknownBlockType dequeueBlock;
@property(copy, nonatomic) CDUnknownBlockType sizeBlock;
@property(nonatomic) unsigned long long scrollPosition;
@property(nonatomic) _Bool shouldScrollIntoViewOnSelectionChange;
@property(retain, nonatomic) NFUICollectionViewCellManager *cellManager;
@property(retain, nonatomic) NavigationBarAppearanceManager *navBarManager;
@property(retain, nonatomic) UIView *fullScreenTransitionDestinationView;
@property(nonatomic) __weak id <NFUIManagedCollectionViewControllerDelegate><NFUICollectionViewCellManagerDelegate><NFUICellSelectionProtocol> delegate;
- (void)triggerScrollEvent;
- (id)dequeueCellForReuseIdentifier:(NSString *)arg1 forIndexPath:(NSIndexPath *)arg2 forKind:(NSString *)arg3;
- (void)reloadViewModelsAtIndexPaths:(NSArray *)arg1;
- (void)reloadViewModelAtIndexPath:(NSIndexPath *)arg1;
- (void)transitionCellAtIndexPathToFullScreen:(NSIndexPath *)arg1;
@end

