//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NFUIPlaybackPlayerProviderProtocol-Protocol.h"
#import "NFUIPlaybackValidatorProtocol-Protocol.h"

@class NSString;
@protocol DataBrokerDataProviderProtocol, NFUIPlaybackManagerDelegate, PlaybackPlayerProtocol;

@interface PlaybackManager : NSObject <NFUIPlaybackPlayerProviderProtocol, NFUIPlaybackValidatorProtocol>
{
    _Bool _playbackSessionActive;
    id <NFUIPlaybackManagerDelegate> _delegate;
    id <DataBrokerDataProviderProtocol> _dataBrokerDelegate;
    id <PlaybackPlayerProtocol> _currentPlaybackPlayer;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <PlaybackPlayerProtocol> currentPlaybackPlayer; // @synthesize currentPlaybackPlayer=_currentPlaybackPlayer;
@property(nonatomic, getter=isPlaybackSessionActive) _Bool playbackSessionActive; // @synthesize playbackSessionActive=_playbackSessionActive;
@property(nonatomic) __weak id <DataBrokerDataProviderProtocol> dataBrokerDelegate; // @synthesize dataBrokerDelegate=_dataBrokerDelegate;
@property(nonatomic) __weak id <NFUIPlaybackManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dismissPlayer:(CDUnknownBlockType)arg1;
- (void)restartPlaybackFromBeginning:(_Bool)arg1;
- (void)stopPlayback;
- (void)nero_internal_startPlayback:(id)arg1;
- (_Bool)isLocalPlayerBeingDismissed;
- (_Bool)isLocalPlayerActive;
- (void)showErrorDialogWithTitle:(id)arg1 message:(id)arg2 code:(long long)arg3;
- (void)validatePlayback:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)playerForPlaybackRequest:(id)arg1;
- (long long)currentlyInferredPlaybackTarget;
- (long long)expectedPlaybackTargetForRequest:(id)arg1;
- (void)initPlayerWithPlaybackRequest:(id)arg1;
- (void)validatePlayback:(id)arg1;
- (void)handlePlaybackNotification:(id)arg1;
- (void)addObservers;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

