//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableDictionary;

@interface IMPGetGhostIdsResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *ghostIds; // @dynamic ghostIds;
@property(readonly, nonatomic) unsigned long long ghostIds_Count; // @dynamic ghostIds_Count;

@end

