//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCConnectionClassManagerV2Listener-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol SCPerforming;

@interface SCBandwidthClassificationStats : NSObject <SCConnectionClassManagerV2Listener>
{
    id <SCPerforming> _bandwidthClassificationStatsPerformer;
    double _previousTime;
    NSMutableDictionary *_classificationResults;
    NSMutableDictionary *_classificationTime;
}

+ (id)shared;
@property(retain, nonatomic) NSMutableDictionary *classificationTime; // @synthesize classificationTime=_classificationTime;
@property(retain, nonatomic) NSMutableDictionary *classificationResults; // @synthesize classificationResults=_classificationResults;
- (void).cxx_destruct;
- (void)reset;
- (id)getClassificationTime;
- (id)getClassificationResults;
- (void)addClassificationResults:(id)arg1;
- (void)updateWithCurrentBandwidthClass:(id)arg1;
- (void)uploadConnectionClassDidChange:(id)arg1;
- (void)downloadConnectionClassDidChange:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

