//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCBitmojiManagerProtocol-Protocol.h"
#import "SCBitmojiMetricsProvider-Protocol.h"
#import "SCUserSessionScoped-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSString, SCBehaviorSubject, SCBitmojiDownloadQueue, SCBitmojiJobCollector, SCBitmojiMetricsCollector, SCBitmojiMetricsReporter, SCBitmojiNetworkPolicy, SCDisposableObserver, SCLazy, SCObservable, SCWeakTimer;
@protocol OS_dispatch_queue, SCBitmojiAvatarProvider, SCBitmojiNetworkStrategy;

@interface SCBitmojiManager : NSObject <SCBitmojiManagerProtocol, SCBitmojiMetricsProvider, SCUserSessionScoped>
{
    NSObject<OS_dispatch_queue> *_workQueue;
    SCLazy *_selfBitmojiCache;
    SCLazy *_friendBitmojiCache;
    SCBehaviorSubject *_metricsAnnouncer;
    SCBitmojiMetricsCollector *_metricsCollector;
    SCBitmojiMetricsReporter *_metricsReporter;
    int _outstandingDownloads;
    SCWeakTimer *_outstandingDownloadBackoff;
    SCBitmojiDownloadQueue *_downloadBacklog;
    SCBitmojiJobCollector *_jobCollector;
    NSMutableSet *_prefetchesDone;
    NSMutableDictionary *_negativeResponseCache;
    id <SCBitmojiAvatarProvider> _avatarProvider;
    id <SCBitmojiNetworkStrategy> _networkStrategy;
    SCBitmojiNetworkPolicy *_networkPolicy;
    // Error parsing type: AB, name: _invalidated
    SCDisposableObserver *_avatarIdObserver;
}

- (void).cxx_destruct;
- (_Bool)_cacheErrorIfPossible:(id)arg1 response:(id)arg2;
- (_Bool)_skipRequestDueToCachedError:(id)arg1;
- (double)_determineRandomTTL;
- (_Bool)_handleImageFailedForJob:(id)arg1 response:(id)arg2 allowRetry:(_Bool)arg3;
- (void)_handleImageResponse:(id)arg1 image:(id)arg2 job:(id)arg3 requestTrackingId:(id)arg4 isFromCache:(_Bool)arg5;
- (void)_checkCacheAndFetch:(id)arg1;
- (void)_checkCacheOnly:(id)arg1 failure:(CDUnknownBlockType)arg2;
- (void)_issueMultipleSingleImageFetches:(id)arg1;
- (void)_issueImageFetchForJob:(id)arg1 scheduleNextOnCompletion:(_Bool)arg2;
- (void)_checkImageFetchBacklog;
- (void)_clearDownloadBackoffTimer;
- (void)_kickDownloadSlots:(id)arg1;
- (void)_downloadSlotRelease;
- (_Bool)_downloadSlotAllocate;
- (void)cancelJob:(id)arg1;
- (id)_generateCacheKey:(id)arg1;
- (id)_generateCacheKey:(id)arg1 imageType:(unsigned long long)arg2;
- (id)_generateCacheKey:(id)arg1 imageType:(unsigned long long)arg2 scale:(unsigned long long)arg3;
- (void)_fetchBitmojiImage:(id)arg1;
- (_Bool)isBitmojiCached:(id)arg1;
- (id)prefetchBitmojiImage:(id)arg1 contexts:(id)arg2 feature:(long long)arg3 completionQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (void)_completePrefetchQueue:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)_startFetch:(id)arg1;
- (id)fetchBitmojiImageData:(id)arg1 contexts:(id)arg2 feature:(long long)arg3 transform:(CDUnknownBlockType)arg4 completionQueue:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)fetchCurrentOrPrior:(id)arg1 contexts:(id)arg2 feature:(long long)arg3 transform:(CDUnknownBlockType)arg4 completionQueue:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)_determineImageParamsWithPriorAvatarVersion:(id)arg1;
- (id)fetchBitmojiImage:(id)arg1 contexts:(id)arg2 feature:(long long)arg3 completionQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)_determineContexts:(id)arg1;
- (void)_lookupInCaches:(id)arg1 imageType:(unsigned long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)_lookupInCaches:(id)arg1 block:(CDUnknownBlockType)arg2;
- (_Bool)_isBitmojiCached:(id)arg1;
- (id)_keyForCachedBitmoji:(id)arg1 cachedImageType:(unsigned long long *)arg2;
- (id)describeEndpointMetrics;
- (void)resetMetrics;
@property(readonly, nonatomic) SCObservable *metricsObservable;
- (id)_cacheForBitmoji:(id)arg1;
- (void)resetCache;
- (void)clearMemoryCache;
- (void)_resetPendingDownloads;
- (void)invalidate;
- (void)_willEnterBackground;
- (id)_determineNetworkStrategy:(id)arg1;
- (void)dealloc;
- (id)initSelfCache:(id)arg1 friendCache:(id)arg2 avatarProvider:(id)arg3 requestManager:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

