//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;
@protocol SCChatGroup;

@protocol SCChatConversation <NSObject>
@property(readonly, nonatomic) _Bool earlierContentExists;
@property(readonly, nonatomic) long long loadingStatus;
@property(readonly, nonatomic) long long historyLoadingStatus;
@property(readonly, copy, nonatomic) NSArray *messages;
@property(readonly, copy, nonatomic) id <SCChatGroup> group;
@property(readonly, copy, nonatomic) NSString *id;
@end

