//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface SCContextCompositeCardView : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned int defaultCardsVisible; // @dynamic defaultCardsVisible;
@property(nonatomic) _Bool hasSeparatorLines; // @dynamic hasSeparatorLines;
@property(retain, nonatomic) NSMutableArray *sectionsArray; // @dynamic sectionsArray;
@property(readonly, nonatomic) unsigned long long sectionsArray_Count; // @dynamic sectionsArray_Count;
@property(copy, nonatomic) NSString *showMoreText; // @dynamic showMoreText;

@end

