//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCDiscoverFeedTileOverlayViewModel : NSObject <NSCopying>
{
    _Bool _subscribed;
    _Bool _isLive;
    _Bool _enableReplayOverlay;
    NSString *_bannerText;
}

@property(readonly, nonatomic) _Bool enableReplayOverlay; // @synthesize enableReplayOverlay=_enableReplayOverlay;
@property(readonly, nonatomic) _Bool isLive; // @synthesize isLive=_isLive;
@property(readonly, copy, nonatomic) NSString *bannerText; // @synthesize bannerText=_bannerText;
@property(readonly, nonatomic) _Bool subscribed; // @synthesize subscribed=_subscribed;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSubscribed:(_Bool)arg1 bannerText:(id)arg2 isLive:(_Bool)arg3 enableReplayOverlay:(_Bool)arg4;

@end

