//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCDiscoverFeedOurStorySummary, SCDiscoverFeedPublicUserSummary, SCDiscoverFeedPublisherSummary;

@interface SCDiscoverFeedStorySummary : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCDiscoverFeedPublisherSummary *_publisherSummary_publisherSummary;
    SCDiscoverFeedPublicUserSummary *_publicUserSummary_publicUserSummary;
    SCDiscoverFeedOurStorySummary *_ourStorySummary_ourStorySummary;
}

+ (id)publisherSummaryWithPublisherSummary:(id)arg1;
+ (id)publicUserSummaryWithPublicUserSummary:(id)arg1;
+ (id)ourStorySummaryWithOurStorySummary:(id)arg1;
- (void).cxx_destruct;
- (void)matchPublisherSummary:(CDUnknownBlockType)arg1 publicUserSummary:(CDUnknownBlockType)arg2 ourStorySummary:(CDUnknownBlockType)arg3;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)asOurStorySummary;
- (id)asPublicUserSummary;
- (id)asPublisherSummary;
- (unsigned long long)subtype;
- (_Bool)isSameSubtype:(id)arg1;
- (id)xLogObjectInfo;

@end

