//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCGalleryInformationWebViewControllerDelegate-Protocol.h"
#import "SCGalleryPrivateGalleryConfirmPassphraseViewControllerDelegate-Protocol.h"
#import "SCGalleryPrivateGalleryEnterPasscodeViewControllerDelegate-Protocol.h"
#import "SCGalleryPrivateGalleryEnterPassphraseViewControllerDelegate-Protocol.h"
#import "SCGalleryPrivateGalleryFinishSetupViewControllerDelegate-Protocol.h"
#import "SCGalleryPrivateGalleryStartSetupViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, SCGalleryInformationWebViewController, SCGalleryPrivateGalleryConfirmPassphraseViewController, SCGalleryPrivateGalleryEnterPasscodeViewController, SCGalleryPrivateGalleryEnterPassphraseViewController, SCGalleryPrivateGalleryFinishSetupViewController, SCGalleryPrivateGalleryFlowNavigationController, SCGalleryPrivateGalleryStartSetupViewController, SCUserSession, UIViewController;
@protocol SCGalleryPrivateGallerySetupFlowDelegate;

@interface SCGalleryPrivateGallerySetupFlow : NSObject <UINavigationControllerDelegate, UIViewControllerTransitioningDelegate, SCGalleryPrivateGalleryStartSetupViewControllerDelegate, SCGalleryPrivateGalleryFinishSetupViewControllerDelegate, SCGalleryPrivateGalleryEnterPasscodeViewControllerDelegate, SCGalleryPrivateGalleryEnterPassphraseViewControllerDelegate, SCGalleryPrivateGalleryConfirmPassphraseViewControllerDelegate, SCGalleryInformationWebViewControllerDelegate>
{
    SCUserSession *_userSession;
    UIViewController *_fromViewController;
    NSString *_passcode;
    NSString *_passphrase;
    SCGalleryPrivateGalleryFlowNavigationController *_navigationController;
    SCGalleryPrivateGalleryStartSetupViewController *_startSetupViewController;
    SCGalleryPrivateGalleryFinishSetupViewController *_finishSetupViewController;
    SCGalleryPrivateGalleryEnterPasscodeViewController *_createPasscodeViewController;
    SCGalleryPrivateGalleryEnterPasscodeViewController *_confirmPasscodeViewController;
    SCGalleryPrivateGalleryConfirmPassphraseViewController *_showPasscodeViewController;
    SCGalleryPrivateGalleryEnterPassphraseViewController *_createPassphraseViewController;
    SCGalleryPrivateGalleryConfirmPassphraseViewController *_confirmPassphraseViewController;
    SCGalleryInformationWebViewController *_informationViewController;
    SCGalleryInformationWebViewController *_topSecretInformationViewController;
    id <SCGalleryPrivateGallerySetupFlowDelegate> _delegate;
}

@property(nonatomic) __weak id <SCGalleryPrivateGallerySetupFlowDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_reset;
- (void)_setPrivateGalleryPassphrase;
- (void)galleryInformationWebViewControllerDidPressBack:(id)arg1;
- (void)confirmPassphraseViewControllerDidConfirmPassphrase:(id)arg1;
- (void)confirmPassphraseViewControllerDidPressQuestionMark:(id)arg1;
- (void)confirmPassphraseViewControllerDidPressBack:(id)arg1;
- (void)enterPassphraseViewController:(id)arg1 didCreatePassphrase:(id)arg2;
- (void)enterPassphraseViewControllerDidPressBack:(id)arg1;
- (void)enterPasscodeViewControllerDidConfirmPasscode:(id)arg1;
- (void)enterPasscodeViewControllerDidPressUsePassphrase:(id)arg1;
- (void)enterPasscodeViewController:(id)arg1 didCreatePasscode:(id)arg2;
- (void)enterPasscodeViewControllerDidPressBack:(id)arg1;
- (void)finishSetupViewControllerDidPressFinish:(id)arg1;
- (void)startSetupViewControllerDidPressBack:(id)arg1;
- (void)startSetupViewControllerDidPressStart:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)start;
- (_Bool)isStarted;
- (id)initWithUserSession:(id)arg1 fromViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

