//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCMapCarouselContainerView;

@protocol SCMapCarouselContainerViewDelegate <NSObject>

@optional
- (void)mapCarouselContainer:(SCMapCarouselContainerView *)arg1 didScrollToIndex:(long long)arg2 action:(unsigned long long)arg3;
- (void)mapCarouselContainerWantsDismissal:(SCMapCarouselContainerView *)arg1;
@end

