//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, NSURL;

@interface SCOperaInteractionZoneLayerItem : NSObject
{
    long long _attachmentType;
    NSString *_iconImageKey;
    NSURL *_webViewUrl;
    NSURL *_deepLinkUri;
    long long _deepLinkFallbackType;
    NSNumber *_deepLinkFallBackAppId;
    NSURL *_deepLinkFallBackUrl;
}

@property(readonly, nonatomic) NSURL *deepLinkFallBackUrl; // @synthesize deepLinkFallBackUrl=_deepLinkFallBackUrl;
@property(readonly, nonatomic) NSNumber *deepLinkFallBackAppId; // @synthesize deepLinkFallBackAppId=_deepLinkFallBackAppId;
@property(readonly, nonatomic) long long deepLinkFallbackType; // @synthesize deepLinkFallbackType=_deepLinkFallbackType;
@property(readonly, nonatomic) NSURL *deepLinkUri; // @synthesize deepLinkUri=_deepLinkUri;
@property(readonly, nonatomic) NSURL *webViewUrl; // @synthesize webViewUrl=_webViewUrl;
@property(readonly, copy, nonatomic) NSString *iconImageKey; // @synthesize iconImageKey=_iconImageKey;
@property(readonly, nonatomic) long long attachmentType; // @synthesize attachmentType=_attachmentType;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)initWithProperties:(id)arg1;

@end

