//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSnapAirLogWriter-Protocol.h"

@class NSArray;

@interface SCSnapchatBetaShakeLogWriter : NSObject <SCSnapAirLogWriter>
{
}

+ (id)shared;
- (_Bool)_dumpBetaLogs:(id)arg1;
@property(readonly, nonatomic) NSArray *asyncLogSources;
- (_Bool)writeLogsToURL:(id)arg1;

@end

