//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSpectaclesResponseMessage.h"

@class VLKNrfResponse;

@interface SCSpectaclesLagunaNrfResponseMessage : SCSpectaclesResponseMessage
{
    VLKNrfResponse *_nrfResponse;
}

+ (id)_descriptionForFailureReason:(int)arg1;
@property(readonly, nonatomic) VLKNrfResponse *nrfResponse; // @synthesize nrfResponse=_nrfResponse;
- (void).cxx_destruct;
- (id)mediaCount;
- (_Bool)videoRecordingHasStarted;
- (_Bool)ambaCrashed;
- (_Bool)contentCleared;
- (id)backgroundUpdateFailureReason;
- (id)backgroundUpdateParameters;
- (id)firmwareDigest;
- (_Bool)patchApplied;
- (_Bool)hasPatchApplied;
- (long long)firmwareUpdateResponseType;
- (_Bool)hasFirmwareUpdateResponse;
- (id)ipAddress;
- (_Bool)wifiOn;
- (_Bool)hasWifiState;
- (long long)bluetoothEvent;
- (_Bool)hasBluetoothEvent;
- (id)wifiTemperature;
- (id)coulombCounterTemperature;
- (id)ambaTemperature;
- (id)nordicTemperature;
- (id)hardwareVersion;
- (id)storagePercentage;
- (_Bool)hasSpaceToRecord;
- (_Bool)hasHasSpaceToRecord;
- (id)serialNumber;
- (id)firmwareVersion;
- (long long)deviceColor;
- (_Bool)hasDeviceColor;
- (_Bool)charging;
- (_Bool)hasCharging;
- (id)voltageLevel;
- (id)batteryLevel;
- (_Bool)hasNrfError;
- (unsigned long long)nrfErrorType;
- (id)crashReports;
- (long long)responseStatus;
- (id)description;
- (id)initWithNrfResponse:(id)arg1 request:(id)arg2;

@end

