//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCBackgroundPrefetchProtocol-Protocol.h"
#import "SCDataCoordinatorListener-Protocol.h"

@class NSString, SCCircumstanceEngine, SCExperimentManager, SCLazy, SCNetworkingUserProfileLoader, SCQueuePerformer, SCStoriesMediaFetcher, SCUserSession;
@protocol SCStoriesMediaCoordinating, SCStoriesMetadataCoordinating;

@interface SCStoriesBackgroundPrefetcher : NSObject <SCBackgroundPrefetchProtocol, SCDataCoordinatorListener>
{
    SCUserSession *_userSession;
    id <SCStoriesMetadataCoordinating> _storiesDataCoordinator;
    id <SCStoriesMediaCoordinating> _storiesMediaCoordinator;
    SCLazy *_storiesSummaryInfoProvider;
    SCLazy *_lazyDocObjectContext;
    SCLazy *_imageDownloader;
    CDUnknownBlockType _backgroundPrefetchCompletionHandler;
    SCStoriesMediaFetcher *_storiesMediaFetcher;
    SCQueuePerformer *_queuePerformer;
    unsigned long long _backgroundFetchResult;
    _Bool _hasRespondedToMetadataDownload;
    SCNetworkingUserProfileLoader *_userProfileLoader;
    SCExperimentManager *_experimentManager;
    SCCircumstanceEngine *_circumstanceEngine;
}

- (void).cxx_destruct;
- (void)_updateBackgroundFetchResult:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_handleDownloadStoriesSnapPlaybackInfo:(id)arg1 mediaState:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_downloadMediaForPlaybackInfoList:(id)arg1 storiesDownloadGroup:(id)arg2;
- (void)_downloadThumbnail:(id)arg1 completion:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)_playbackInfoMapToDownloadWithAllPlaybackInfoMap:(id)arg1 rankedStoryIds:(id)arg2 numOfFriendStoriesToDownload:(unsigned long long)arg3 numOfSnapsInEachStoryToDownload:(unsigned long long)arg4 maxNumOfSnapsInEachStoryToDownload:(unsigned long long)arg5 storyScore:(float)arg6;
- (void)_handleStoriesDownloadCompletion;
- (void)_handleDownloadStoriesWithFilteredPlaybackInfoMap:(id)arg1 summaryData:(id)arg2;
- (void)_handleDownloadStoriesWithFilteredPlaybackInfoMap:(id)arg1;
- (void)_handleDownloadStoriesWithPlaybackInfoMap:(id)arg1 rankedStoryIds:(id)arg2 numOfFriendStoriesToDownload:(unsigned long long)arg3 numOfSnapsInEachStoryToDownload:(unsigned long long)arg4 maxNumOfSnapsInEachStoryToDownload:(unsigned long long)arg5 storyScore:(float)arg6;
- (void)_handleStoriesPrefetchUsingUserProfile:(id)arg1 playbackInfoMap:(id)arg2 rankedStoryIds:(id)arg3;
- (void)_handleStoriesPrefetchWithConfig:(id)arg1 playbackInfoMap:(id)arg2 rankedStoryIds:(id)arg3;
- (void)_handleDownloadStoriesWithPlaybackInfoMap:(id)arg1 rankedStoryIds:(id)arg2;
- (void)_handleDownloadStoriesWithRankedStoryIds:(id)arg1;
- (void)_handleDataCoordinatorDidUpdateWithIdentifier:(id)arg1 dataRequest:(id)arg2;
- (void)dataCoordinatorDidUpdateWithIdentifier:(id)arg1 dataRequest:(id)arg2;
- (unsigned long long)prefetchIntervalInSeconds;
- (id)name;
- (void)backgroundPrefetchMediaWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithUserSession:(id)arg1 storiesDataCoordinator:(id)arg2 storiesSummaryInfoProvider:(id)arg3 storiesMediaCoordinator:(id)arg4 lazyDocObjectContext:(id)arg5 imageDownloader:(id)arg6 circumstanceEngine:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

