//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOJUUnlockablesOndemandApprovalStatus-Protocol.h"

@class NSString, SOJUUnlockablesOndemandLineItemApprovalDetails;

@interface SOJUUnlockablesOndemandApprovalStatus : NSObject <SOJUUnlockablesOndemandApprovalStatus>
{
    NSString *_status;
    SOJUUnlockablesOndemandLineItemApprovalDetails *_rejectionDetails;
    SOJUUnlockablesOndemandLineItemApprovalDetails *_revocationDetails;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
+ (_Bool)canInitFromProto;
@property(readonly, copy, nonatomic) SOJUUnlockablesOndemandLineItemApprovalDetails *revocationDetails; // @synthesize revocationDetails=_revocationDetails;
@property(readonly, copy, nonatomic) SOJUUnlockablesOndemandLineItemApprovalDetails *rejectionDetails; // @synthesize rejectionDetails=_rejectionDetails;
@property(readonly, copy, nonatomic) NSString *status; // @synthesize status=_status;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithStatus:(id)arg1 rejectionDetails:(id)arg2 revocationDetails:(id)arg3;
- (id)toJson;
- (id)toDictionary;
- (id)initWithJSONDictionary:(id)arg1;
- (long long)statusEnum;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

