//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ChromeInternal/DSCHostImageFetcher-Protocol.h>

@class GIPNetworkImageFetcher, GIPPersistentCache, GTMSessionFetcherService, NSString;
@protocol OS_dispatch_queue;

@interface DSCDefaultHostImageFetcher : NSObject <DSCHostImageFetcher>
{
    GIPNetworkImageFetcher *_imageFetcher;
    GIPPersistentCache *_imageCache;
    GTMSessionFetcherService *_fetcherService;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) GTMSessionFetcherService *fetcherService; // @synthesize fetcherService=_fetcherService;
@property(retain, nonatomic) GIPPersistentCache *imageCache; // @synthesize imageCache=_imageCache;
@property(retain, nonatomic) GIPNetworkImageFetcher *imageFetcher; // @synthesize imageFetcher=_imageFetcher;
- (void)dispatchSync:(CDUnknownBlockType)arg1;
- (void)dispatchAsync:(CDUnknownBlockType)arg1;
- (_Bool)fetchImageWithURL:(id)arg1 owner:(id)arg2 callbackQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)cachedImageForURL:(id)arg1 callbackQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)cachedImageForURL:(id)arg1;
- (void)cancelFetchesForOwner:(id)arg1;
- (_Bool)fetchImageWithURL:(id)arg1 owner:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithImageCacheSize:(unsigned long long)arg1 userAgent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

