//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseFeedDisplayNode.h"

@interface _TtC6RedditP33_B161AF0B378F5C5F34D9827BA20048CF25OnboardingSegmentItemNode : BaseFeedDisplayNode
{
    // Error parsing type: , name: selected
    // Error parsing type: , name: item
    // Error parsing type: , name: buttonNode
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithVisibilityTracker:(id)arg1 visibilityOptions:(id)arg2;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;

@end

