//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSNumber, NSString, NSURL, UIColor, UIImage;

@interface SelectedAwardViewModel : NSObject
{
    _Bool _isProcessing;
    _Bool _enableActionButton;
    NSString *_name;
    NSURL *_iconImageURL;
    NSAttributedString *_attributedPrice;
    NSAttributedString *_itemDescription;
    NSString *_optionsText;
    NSString *_actionButtonText;
    NSString *_awardInfoText;
    unsigned long long _awardInfoIconType;
    UIImage *_defaultSubredditIcon;
    UIColor *_subredditColor;
    NSURL *_subredditIconURL;
    NSNumber *_subredditCoins;
}

@property(readonly, nonatomic) _Bool enableActionButton; // @synthesize enableActionButton=_enableActionButton;
@property(readonly, nonatomic) _Bool isProcessing; // @synthesize isProcessing=_isProcessing;
@property(readonly, nonatomic) NSNumber *subredditCoins; // @synthesize subredditCoins=_subredditCoins;
@property(readonly, nonatomic) NSURL *subredditIconURL; // @synthesize subredditIconURL=_subredditIconURL;
@property(readonly, nonatomic) UIColor *subredditColor; // @synthesize subredditColor=_subredditColor;
@property(readonly, nonatomic) UIImage *defaultSubredditIcon; // @synthesize defaultSubredditIcon=_defaultSubredditIcon;
@property(readonly, nonatomic) unsigned long long awardInfoIconType; // @synthesize awardInfoIconType=_awardInfoIconType;
@property(readonly, nonatomic) NSString *awardInfoText; // @synthesize awardInfoText=_awardInfoText;
@property(readonly, nonatomic) NSString *actionButtonText; // @synthesize actionButtonText=_actionButtonText;
@property(readonly, nonatomic) NSString *optionsText; // @synthesize optionsText=_optionsText;
@property(readonly, nonatomic) NSAttributedString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(readonly, nonatomic) NSAttributedString *attributedPrice; // @synthesize attributedPrice=_attributedPrice;
@property(readonly, nonatomic) NSURL *iconImageURL; // @synthesize iconImageURL=_iconImageURL;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithAward:(id)arg1 subreddit:(id)arg2 subredditCoins:(id)arg3 target:(unsigned long long)arg4 options:(unsigned long long)arg5;

@end

