//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AriaObjC/NSObject-Protocol.h>

@class NSString;

@protocol ACTISemanticContext <NSObject>
- (void)setAppExperimentImpressionId:(NSString *)arg1;
- (void)setAppExperimentETag:(NSString *)arg1;
- (void)setAppExperimentIds:(NSString *)arg1 forEvent:(NSString *)arg2;
- (void)setAppExperimentIds:(NSString *)arg1;
- (void)setAppLanguage:(NSString *)arg1;
- (void)setUserTimeZone:(NSString *)arg1;
- (void)setUserLanguage:(NSString *)arg1;
- (void)setUserAdvertisingId:(NSString *)arg1;
- (void)setUserANID:(NSString *)arg1;
- (void)setUserId:(NSString *)arg1;
- (void)setUserMsaId:(NSString *)arg1;
- (void)setUserId:(NSString *)arg1 piiKind:(int)arg2;
- (void)setOsBuild:(NSString *)arg1;
- (void)setOsVersion:(NSString *)arg1;
- (void)setOsName:(NSString *)arg1;
- (void)setNetworkProvider:(NSString *)arg1;
- (void)setDeviceModel:(NSString *)arg1;
- (void)setDeviceMake:(NSString *)arg1;
- (void)setDeviceId:(NSString *)arg1;
- (void)setAppVersion:(NSString *)arg1;
- (void)setAppId:(NSString *)arg1;
@end

