//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSAConfigManager, MSAEnvironmentInternal, NSString;

@interface MSASessionRequestFactory : NSObject
{
    MSAEnvironmentInternal *_environment;
    MSAConfigManager *_configManager;
    NSString *_clientType;
}

- (void).cxx_destruct;
- (void)initializeRequest:(id)arg1 deviceIdentity:(id)arg2;
- (id)createListSessionsRequest:(id)arg1 deviceIdentity:(id)arg2 checkRegistrations:(_Bool)arg3;
- (id)createNgcApproveSessionRequest:(id)arg1 account:(id)arg2 deviceIdentity:(id)arg3 ngcToken:(id)arg4 type:(long long)arg5;
- (id)createEcNgcApproveSessionRequest:(id)arg1 account:(id)arg2 deviceIdentity:(id)arg3 jsonFidoAssertion:(id)arg4;
- (id)createRsaNgcApproveSessionRequest:(id)arg1 account:(id)arg2 deviceIdentity:(id)arg3 ngcToken:(id)arg4;
- (id)createNgcGetNonceRequest:(id)arg1 account:(id)arg2;
- (id)createApproveSessionRequest:(id)arg1 action:(long long)arg2 deviceIdentity:(id)arg3;
- (id)createUnregisterApproverRequest:(id)arg1 userPuid:(id)arg2;
- (id)createUpdateApproverRequest:(id)arg1 userPuid:(id)arg2 registrationId:(id)arg3;
- (id)createRegisterApproverRequest:(id)arg1 deviceIdentity:(id)arg2 registrationId:(id)arg3 serverKeyIdentifier:(id)arg4 market:(id)arg5;
- (id)createRegisterApproverRequest:(id)arg1 deviceIdentity:(id)arg2 registrationId:(id)arg3 market:(id)arg4;
- (id)createRegisterECLoginKeyRequest:(id)arg1 friendlyName:(id)arg2 publicKeyFidoBlob:(id)arg3 userDAToken:(id)arg4 deviceIdentity:(id)arg5;
- (id)createRegisterRSALoginKeyRequest:(id)arg1 exponent:(id)arg2 modulus:(id)arg3 userDAToken:(id)arg4 deviceIdentity:(id)arg5;
- (id)initForEnvironment:(id)arg1 clientType:(id)arg2;
- (id)init;

@end

