//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MSAL/MSIDAADTokenResponse.h>

@class NSString;

@interface MSIDAADV1TokenResponse : MSIDAADTokenResponse
{
    NSString *_resource;
}

+ (long long)providerType;
+ (void)load;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *resource; // @synthesize resource=_resource;
- (id)jsonDictionary;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;
- (long long)accountType;
- (id)target;
- (_Bool)isMultiResource;
- (id)tokenClaimsFromRawIdToken:(id)arg1 error:(id *)arg2;

@end

