//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSIDCache;

@interface MSIDBackgroundTaskManager : NSObject
{
    MSIDCache *_taskCache;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) MSIDCache *taskCache; // @synthesize taskCache=_taskCache;
- (void)setBackgroundTask:(unsigned long long)arg1 forType:(long long)arg2;
- (unsigned long long)backgroundTaskWithType:(long long)arg1;
- (void)stopOperationWithType:(long long)arg1;
- (void)startOperationWithType:(long long)arg1;
- (id)initInternal;

@end

