//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PopupViewController.h"

@interface _TtC6Reddit23FlagAwardViewController : PopupViewController
{
    // Error parsing type: , name: alertTitleLabel
}

- (void).cxx_destruct;
- (id)initWithAccountContext:(id)arg1 analyticsContext:(id)arg2 contentView:(id)arg3 bottomButtons:(id)arg4;
- (void)close;
- (id)initWithAccountContext:(id)arg1 analyticsContext:(id)arg2 title:(id)arg3 actions:(id)arg4;

@end

