//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AnalyticsFramework/NSCoding-Protocol.h>
#import <AnalyticsFramework/NSCopying-Protocol.h>
#import <AnalyticsFramework/TBase-Protocol.h>

@class NSString;

@interface AnalyticsResponse : NSObject <TBase, NSCoding, NSCopying>
{
    _Bool _last_modified_timestampIsSet;
    _Bool _codeIsSet;
    int _code;
    long long _last_modified_timestamp;
}

@property(nonatomic) _Bool codeIsSet; // @synthesize codeIsSet=_codeIsSet;
@property(nonatomic) int code; // @synthesize code=_code;
@property(nonatomic) _Bool last_modified_timestampIsSet; // @synthesize last_modified_timestampIsSet=_last_modified_timestampIsSet;
@property(nonatomic) long long last_modified_timestamp; // @synthesize last_modified_timestamp=_last_modified_timestamp;
@property(readonly, copy) NSString *description;
- (_Bool)validate:(id *)arg1;
- (_Bool)write:(id)arg1 error:(id *)arg2;
- (_Bool)read:(id)arg1 error:(id *)arg2;
- (void)unsetCode;
- (void)unsetLast_modified_timestamp;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLast_modified_timestamp:(long long)arg1 code:(int)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

