//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol IBGFeatureDetailAddCommentViewDelegate
- (void)didTapPostWithName:(NSString *)arg1 email:(NSString *)arg2 comment:(NSString *)arg3;
- (void)didTapCancel;
@end

