//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNotificationCenter, NSNumber, RedditService;

@interface InitialHomeFeedController : NSObject
{
    _Bool _didPostInitialFeedDidPerformInitialFetchNotification;
    RedditService *_service;
    NSNotificationCenter *_notificationCenter;
    NSNumber *_calculatedHomeFeed;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *calculatedHomeFeed; // @synthesize calculatedHomeFeed=_calculatedHomeFeed;
@property(nonatomic) _Bool didPostInitialFeedDidPerformInitialFetchNotification; // @synthesize didPostInitialFeedDidPerformInitialFetchNotification=_didPostInitialFeedDidPerformInitialFetchNotification;
@property(retain, nonatomic) NSNotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
@property(readonly, nonatomic) __weak RedditService *service; // @synthesize service=_service;
- (void)initialFeedDidPerformInitialFetchForFeedType:(unsigned long long)arg1 didFetchSuccessfully:(_Bool)arg2;
@property(readonly, nonatomic) unsigned long long homeFeed;
- (id)initWithService:(id)arg1 notificationCenter:(id)arg2;

@end

