//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SubredditAboutViewModel.h"

@class NSMutableSet, SubredditCommunityListWidget;

@interface SubredditAboutCommunityListWidgetViewModel : SubredditAboutViewModel
{
    NSMutableSet *_subscribedCommunities;
    SubredditCommunityListWidget *_communityListWidget;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SubredditCommunityListWidget *communityListWidget; // @synthesize communityListWidget=_communityListWidget;
@property(retain, nonatomic) NSMutableSet *subscribedCommunities; // @synthesize subscribedCommunities=_subscribedCommunities;
- (void)unsubscribeFromCommunity:(id)arg1;
- (void)subscribeToCommunity:(id)arg1;
- (_Bool)isUserSubscribedToCommunity:(id)arg1;
- (long long)numberOfRowItems;
- (id)titleLabelText;
- (double)heightForRow:(long long)arg1 rowWidth:(double)arg2;
- (double)footerHeight;
- (double)headerHeight;
- (id)widget;
- (id)initWithSubredditWidget:(id)arg1;

@end

