//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ImagePopupViewControllerActiveDelegate-Protocol.h"
#import "ImagePopupViewControllerDelegate-Protocol.h"

@interface UIViewController (Sharing) <ImagePopupViewControllerDelegate, ImagePopupViewControllerActiveDelegate>
+ (id)subredditOrUserPageViewControllerForSubreddit:(id)arg1 accountContext:(id)arg2;
+ (id)subredditOrUserPageViewControllerForCommunityName:(id)arg1 accountContext:(id)arg2;
- (void)imagePopupViewControllerDidPressActiveButton:(id)arg1 accountContext:(id)arg2;
- (void)imagePopupViewControllerDidConfirm:(id)arg1;
- (void)imagePopupViewControllerDidClose:(id)arg1;
- (void)imagePopupViewControllerDidCancel:(id)arg1;
- (void)imagePopupViewController:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)presentDirectShareForSubject:(id)arg1 body:(id)arg2 sender:(id)arg3 accountContext:(id)arg4;
- (void)didTapCloseButton:(id)arg1;
- (void)showInformationalModalViewWithAccountContext:(id)arg1;
- (void)showErrorToastForPostType:(unsigned long long)arg1 activityType:(id)arg2 error:(id)arg3;
- (void)showSuccessToastForPostType:(unsigned long long)arg1 activityType:(id)arg2 accountContext:(id)arg3;
- (id)activityViewControllerForShareData:(id)arg1 accountContext:(id)arg2;
- (void)presentShareViewForData:(id)arg1 accountContext:(id)arg2;
- (void)presentShareViewForTextString:(id)arg1 urlString:(id)arg2 analyticsSource:(id)arg3 sender:(id)arg4 accountContext:(id)arg5;
- (void)navigateToViewController:(id)arg1 animated:(_Bool)arg2;
@property(nonatomic, readonly) _Bool viewIsInWindowBounds;
@property(nonatomic, readonly) _Bool isModal;
@end

