//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface RLMSyncUser : NSObject
{
    shared_ptr_324a0594 _user;
}

+ (void)_performLoginForCustomRefreshTokenCredentials:(id)arg1 authServerURL:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (void)_performLoginForDirectAccessTokenCredentials:(id)arg1 authServerURL:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (void)_setUpBindingContextFactory;
+ (void)confirmEmailForAuthServer:(id)arg1 token:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)requestEmailConfirmationForAuthServer:(id)arg1 userEmail:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)completePasswordResetForAuthServer:(id)arg1 token:(id)arg2 password:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)requestPasswordResetForAuthServer:(id)arg1 userEmail:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)logInWithCredentials:(id)arg1 authServerURL:(id)arg2 timeout:(double)arg3 callbackQueue:(id)arg4 onCompletion:(CDUnknownBlockType)arg5;
+ (void)logInWithCredentials:(id)arg1 authServerURL:(id)arg2 onCompletion:(CDUnknownBlockType)arg3;
+ (id)currentUser;
+ (id)allUsers;
- (id).cxx_construct;
- (void).cxx_destruct;
- (shared_ptr_324a0594)_syncUser;
@property(readonly, nonatomic) NSString *refreshToken;
- (id)defaultRealmURL;
- (id)urlForPath:(id)arg1;
- (void)retrievePermissionOffersWithCallback:(CDUnknownBlockType)arg1;
- (void)invalidateOfferForToken:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)acceptOfferForToken:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)createOfferForRealmAtURL:(id)arg1 accessLevel:(unsigned long long)arg2 expiration:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)applyPermission:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)retrievePermissionsWithCallback:(CDUnknownBlockType)arg1;
- (void)retrieveInfoForUser:(id)arg1 identityProvider:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)changePassword:(id)arg1 forUserID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)changePassword:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool isAdmin;
@property(readonly, nonatomic) NSURL *authenticationServer;
@property(readonly, nonatomic) unsigned long long state;
@property(readonly, nonatomic) NSString *identity;
- (id)allSessions;
- (id)sessionForURL:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType errorHandler;
- (void)invalidate;
- (void)logOut;
- (id)configurationWithURL:(id)arg1 fullSynchronization:(_Bool)arg2 enableSSLValidation:(_Bool)arg3 urlPrefix:(id)arg4;
- (id)configurationWithURL:(id)arg1 fullSynchronization:(_Bool)arg2;
- (id)configurationWithURL:(id)arg1;
- (id)configuration;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSyncUser:(shared_ptr_324a0594)arg1;

@end

