//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ContactsUI/CNContactPickerViewController.h>

@class TFSTwitterScribeContext, TFSTwitterUserReference, UIImage;

@interface T1ContactPickerViewController : CNContactPickerViewController
{
    TFSTwitterUserReference *_userReference;
    UIImage *_userAvatar;
    TFSTwitterScribeContext *_scribeContext;
}

- (void).cxx_destruct;
@property(copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(retain, nonatomic) UIImage *userAvatar; // @synthesize userAvatar=_userAvatar;
@property(retain, nonatomic) TFSTwitterUserReference *userReference; // @synthesize userReference=_userReference;

@end

