//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _TtC8libFunny16GuideServiceImpl : NSObject
{
    // Error parsing type: , name: guideShownInCurrentSession
    // Error parsing type: , name: applicationController
    // Error parsing type: , name: extendedGuide
    // Error parsing type: , name: pushNotificationsRequestingService
    // Error parsing type: , name: feedController
    // Error parsing type: , name: idfaService
    // Error parsing type: , name: PushFullScreenWasShownKey
    // Error parsing type: , name: latService
}

- (void).cxx_destruct;
- (id)init;
- (void)showWithFeedViewController:(id)arg1;
@property(nonatomic) _Bool guideShownInCurrentSession; // @synthesize guideShownInCurrentSession;

@end

