//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Funny/MPNativeCustomEvent.h>

#import <Funny/AdIdentifierEvent-Protocol.h>
#import <Funny/BiddingEvent-Protocol.h>
#import <Funny/KeywordsEvent-Protocol.h>
#import <Funny/MPAdViewDelegate-Protocol.h>
#import <Funny/_TtP15FCAdvertisement13BidderIdEvent_-Protocol.h>

@class Bid, NSDecimalNumber, NSDictionary, NSString, _TtC15FCAdvertisement20Mopub2InstanceLoader;

@interface AmazonMRECBiddingCustomEvent : MPNativeCustomEvent <MPAdViewDelegate, KeywordsEvent, AdIdentifierEvent, BiddingEvent, _TtP15FCAdvertisement13BidderIdEvent_>
{
    Bid *_bid;
    NSString *_adIdentifier;
    NSString *_originalAdIdentifier;
    _TtC15FCAdvertisement20Mopub2InstanceLoader *_loader;
    NSDecimalNumber *_biddingWinnerPriceLastAuction;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDecimalNumber *biddingWinnerPriceLastAuction; // @synthesize biddingWinnerPriceLastAuction=_biddingWinnerPriceLastAuction;
@property(retain, nonatomic) _TtC15FCAdvertisement20Mopub2InstanceLoader *loader; // @synthesize loader=_loader;
@property(copy, nonatomic) NSString *originalAdIdentifier; // @synthesize originalAdIdentifier=_originalAdIdentifier;
@property(copy, nonatomic) NSString *adIdentifier; // @synthesize adIdentifier=_adIdentifier;
@property(readonly, nonatomic) Bid *bid; // @synthesize bid=_bid;
- (id)eventBidderId;
@property(readonly, nonatomic) NSDictionary *keywords;
- (double)requestsLoadingTimeout;
- (void)requestAdWithCustomEventInfo:(id)arg1 adMarkup:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

