//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBAdKVOController;
@protocol FNFAVPlayer, FNFAVPlayerLayer;

@interface FBAdVideoPlayerView : UIView
{
    _Bool _initialized;
    id <FNFAVPlayer> _player;
    id <FNFAVPlayerLayer> _playerLayer;
    FBAdKVOController *_readyForDisplayKVOController;
    CDUnknownBlockType _videoReadyToDisplay;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType videoReadyToDisplay; // @synthesize videoReadyToDisplay=_videoReadyToDisplay;
@property(retain, nonatomic) FBAdKVOController *readyForDisplayKVOController; // @synthesize readyForDisplayKVOController=_readyForDisplayKVOController;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
@property(nonatomic) __weak id <FNFAVPlayerLayer> playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) id <FNFAVPlayer> player; // @synthesize player=_player;
- (void)layoutSubviews;
- (void)updateView:(_Bool)arg1;
- (void)dealloc;
- (void)initVideoLayer;
- (id)initWithFrame:(struct CGRect)arg1 videoReadyToDisplay:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithVideoReadyToDisplay:(CDUnknownBlockType)arg1;
- (id)init;

@end

