//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Funny/IFDWHBaseEvent.h>

@class NSString;

@interface IFDWHAdAttemptEvent : IFDWHBaseEvent
{
    unsigned long long _type;
    NSString *_tier;
    unsigned long long _status;
    double _timeInMilliseconds;
    long long _feedType;
    NSString *_errorMessage;
    NSString *_creativeId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *creativeId; // @synthesize creativeId=_creativeId;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(nonatomic) long long feedType; // @synthesize feedType=_feedType;
@property(nonatomic) double timeInMilliseconds; // @synthesize timeInMilliseconds=_timeInMilliseconds;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *tier; // @synthesize tier=_tier;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id)feedName;
- (id)stringType;
- (id)parameters;
- (unsigned long long)defaultTriggeredBy;
- (id)name;
- (id)initWithType:(unsigned long long)arg1 tier:(id)arg2 status:(unsigned long long)arg3 timeInMilliseconds:(double)arg4 feedType:(long long)arg5 errorMessage:(id)arg6 creativeId:(id)arg7;

@end

