//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSString, T1CachedImageColorExtractor, UIColor, UIImage;

@protocol T1CachedImageColorExtractorDelegate <NSObject>
- (void)imageColorExtractor:(T1CachedImageColorExtractor *)arg1 didFinishExtractingMostDominantColor:(UIColor *)arg2 image:(UIImage *)arg3 identifier:(NSString *)arg4;
@end

