//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIView;

@protocol T1FlexibleLayoutItem
@property(readonly, nonatomic) CDUnknownBlockType flexibleLayoutContentSpacingCalculator;
@property(readonly, nonatomic) CDUnknownBlockType flexibleLayoutVisibilityCalculator;
@property(readonly, nonatomic) CDUnknownBlockType flexibleLayoutContentInsetsCalculator;
@property(readonly, nonatomic) CDUnknownBlockType flexibleLayoutFrameCalculator;
@property(readonly, nonatomic) CDUnknownBlockType flexibleLayoutSizeCalculator;
@property(readonly, nonatomic) CDUnknownBlockType flexibleLayoutFrameAnimator;
@property(readonly, nonatomic) UIView *flexibleLayoutView;
@end

