//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FAuthTokenProvider-Protocol.h"

@class NSMutableArray, NSString;
@protocol FIRAuthInterop;

@interface FIRFirebaseAuthTokenProvider : NSObject <FAuthTokenProvider>
{
    id <FIRAuthInterop> _auth;
    NSMutableArray *_authListeners;
}

@property(retain, nonatomic) NSMutableArray *authListeners; // @synthesize authListeners=_authListeners;
@property(retain, nonatomic) id <FIRAuthInterop> auth; // @synthesize auth=_auth;
- (void).cxx_destruct;
- (void)listenForTokenChanges:(CDUnknownBlockType)arg1;
- (void)fetchTokenForcingRefresh:(_Bool)arg1 withCallback:(CDUnknownBlockType)arg2;
- (id)initWithAuth:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

