//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDKmzTemplate, NSMutableDictionary, NSMutableSet, NSURL;

@interface IDKmzGenerator : NSObject
{
    NSMutableSet *_exportedObjects;
    IDKmzTemplate *_template;
    NSURL *_exportUrl;
    NSMutableDictionary *_hashCache;
}

@property(retain) NSMutableDictionary *hashCache; // @synthesize hashCache=_hashCache;
@property(retain) NSURL *exportUrl; // @synthesize exportUrl=_exportUrl;
@property(retain) IDKmzTemplate *template; // @synthesize template=_template;
@property(retain) NSMutableSet *exportedObjects; // @synthesize exportedObjects=_exportedObjects;
- (void).cxx_destruct;
- (void)exportStyleMapDefinition:(id)arg1;
- (_Bool)exportKmlWithError:(id *)arg1;
- (void)exportImage:(id)arg1;
- (id)deriveImageName:(id)arg1;
- (id)derivePlacemarkStyleName:(id)arg1;
- (id)createKmzFileContent:(id)arg1;

@end

