//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTContextMenuAction-Protocol.h"

@class NSNumber, NSNumberFormatter, NSString, SPTPodcastPreferences, UIView;
@protocol SPTPodcastPlaybackSpeedMenuActionDelegate;

@interface SPTPodcastPlaybackSpeedMenuAction : NSObject <SPTContextMenuAction>
{
    NSString *_title;
    NSNumber *_playbackSpeed;
    NSNumberFormatter *_speedNumberFormatter;
    SPTPodcastPreferences *_podcastPreferences;
    UIView *_accessoryViewCache;
    id <SPTPodcastPlaybackSpeedMenuActionDelegate> _delegate;
}

+ (id)speedControlContextMenuActionsForOptions:(id)arg1 withNumberFormatter:(id)arg2 podcastPreferences:(id)arg3 delegate:(id)arg4;
@property(nonatomic) __weak id <SPTPodcastPlaybackSpeedMenuActionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *accessoryViewCache; // @synthesize accessoryViewCache=_accessoryViewCache;
@property(retain, nonatomic) SPTPodcastPreferences *podcastPreferences; // @synthesize podcastPreferences=_podcastPreferences;
@property(readonly, nonatomic) NSNumberFormatter *speedNumberFormatter; // @synthesize speedNumberFormatter=_speedNumberFormatter;
@property(readonly, nonatomic) NSNumber *playbackSpeed; // @synthesize playbackSpeed=_playbackSpeed;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)accessoryView;
- (id)performAction;
- (id)initWithPlaybackSpeed:(id)arg1 title:(id)arg2 numberFormatter:(id)arg3 podcastPreferences:(id)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

