//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityView.h"

#import "NFUIDisplayPagePlayButtonViewDelegateProtocol-Protocol.h"
#import "NFUIFamiliarityPlayerProtocol-Protocol.h"
#import "NFUIFamiliarityVolumeButtonDelegateProtocol-Protocol.h"
#import "NFUIPlayerDelegate-Protocol.h"

@class NFUIDisplayPagePlayButtonView, NFUIFamiliarityLargeViewModel, NFUIFamiliarityMetaDataView, NFUIFamiliaritySimpleTagsView, NFUIFamiliarityVolumeButton, NFUIGradientView, NFUIIconButton, NFUILabel, NSLayoutConstraint, NSString, UIActivityIndicatorView, UIImageViewAligned, UITapGestureRecognizer, UIView, UIViewController;
@protocol NFUIFamiliarityViewProtocol, NFUIPlayer;

@interface NFUIFamiliarityLargeView : NFUIFamiliarityView <NFUIDisplayPagePlayButtonViewDelegateProtocol, NFUIFamiliarityVolumeButtonDelegateProtocol, NFUIPlayerDelegate, NFUIFamiliarityPlayerProtocol>
{
    _Bool _isLayoutPass;
    _Bool _hasInlineVideo;
    _Bool _hasConstraints;
    NFUIFamiliarityLargeViewModel *_viewModel;
    UIViewController *delegateViewController;
    id <NFUIPlayer> _player;
    UITapGestureRecognizer *_infoTapGesture;
    UIView *_miniPlayerImageContainer;
    UIView *_imageViewContainer;
    UIImageViewAligned *_imageView;
    NFUIGradientView *_gradientView;
    NFUIGradientView *_horizontalGradientView;
    UIImageViewAligned *_titleTreatment;
    NFUILabel *_titleLabel;
    NFUIFamiliarityMetaDataView *_metaContainer;
    NFUIDisplayPagePlayButtonView *_playButton;
    NFUIFamiliaritySimpleTagsView *_tagsContainer;
    NFUILabel *_typeDurationLabel;
    NFUILabel *_synopsisLabel;
    NFUIIconButton *_myListButton;
    NFUIIconButton *_infoButton;
    NFUIFamiliarityVolumeButton *_volumeButton;
    NSLayoutConstraint *_playButtonWidthConstraint;
    UIActivityIndicatorView *_activityIndicator;
    UIView *_activityIndicatorContainer;
    NSLayoutConstraint *_metaHeightConstraint;
}

+ (id)viewModelForListModel:(id)arg1 withIndexPath:(id)arg2;
@property(retain, nonatomic) NSLayoutConstraint *metaHeightConstraint; // @synthesize metaHeightConstraint=_metaHeightConstraint;
@property(nonatomic) _Bool hasConstraints; // @synthesize hasConstraints=_hasConstraints;
@property(retain, nonatomic) UIView *activityIndicatorContainer; // @synthesize activityIndicatorContainer=_activityIndicatorContainer;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) NSLayoutConstraint *playButtonWidthConstraint; // @synthesize playButtonWidthConstraint=_playButtonWidthConstraint;
@property(retain, nonatomic) NFUIFamiliarityVolumeButton *volumeButton; // @synthesize volumeButton=_volumeButton;
@property(retain, nonatomic) NFUIIconButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) NFUIIconButton *myListButton; // @synthesize myListButton=_myListButton;
@property(retain, nonatomic) NFUILabel *synopsisLabel; // @synthesize synopsisLabel=_synopsisLabel;
@property(retain, nonatomic) NFUILabel *typeDurationLabel; // @synthesize typeDurationLabel=_typeDurationLabel;
@property(retain, nonatomic) NFUIFamiliaritySimpleTagsView *tagsContainer; // @synthesize tagsContainer=_tagsContainer;
@property(retain, nonatomic) NFUIDisplayPagePlayButtonView *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) NFUIFamiliarityMetaDataView *metaContainer; // @synthesize metaContainer=_metaContainer;
@property(retain, nonatomic) NFUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageViewAligned *titleTreatment; // @synthesize titleTreatment=_titleTreatment;
@property(retain, nonatomic) NFUIGradientView *horizontalGradientView; // @synthesize horizontalGradientView=_horizontalGradientView;
@property(retain, nonatomic) NFUIGradientView *gradientView; // @synthesize gradientView=_gradientView;
@property(retain, nonatomic) UIImageViewAligned *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *imageViewContainer; // @synthesize imageViewContainer=_imageViewContainer;
@property(retain, nonatomic) UIView *miniPlayerImageContainer; // @synthesize miniPlayerImageContainer=_miniPlayerImageContainer;
@property(retain, nonatomic) UITapGestureRecognizer *infoTapGesture; // @synthesize infoTapGesture=_infoTapGesture;
@property(nonatomic) __weak id <NFUIPlayer> player; // @synthesize player=_player;
- (void)setHasInlineVideo:(_Bool)arg1;
- (void)setDelegateViewController:(id)arg1;
- (id)delegateViewController;
- (void)setIsLayoutPass:(_Bool)arg1;
- (_Bool)isLayoutPass;
@property(retain, nonatomic) NFUIFamiliarityLargeViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)shouldShowActivityIndicator:(_Bool)arg1;
- (void)volumeStateChanged:(_Bool)arg1;
- (void)hideVolumeControl;
- (void)showVolumeControl;
- (void)resetState;
- (void)showImage:(_Bool)arg1;
- (void)player:(id)arg1 stateChange:(unsigned long long)arg2 previous:(unsigned long long)arg3;
- (void)pause;
- (void)play;
- (void)player:(id)arg1 error:(id)arg2;
- (void)playerWillPause:(id)arg1;
- (void)playerWillStop:(id)arg1;
- (void)playerWillPlay:(id)arg1;
- (void)pauseSupplemental;
- (void)checkPlayerInstance:(_Bool)arg1;
- (void)playSupplemental:(_Bool)arg1;
- (void)playTapped;
- (void)infoButtonPressed:(id)arg1;
- (void)myListButtonPressed:(id)arg1;
- (void)setupConstraints;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)queueModified:(id)arg1;
- (void)volumeDidChange;
- (_Bool)hasInlineVideo;
- (void)commonInit;
- (void)cancelImageLoad;
- (void)reloadViewModel;
- (void)configureForDisabledPlayback:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <NFUIFamiliarityViewProtocol> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

