//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RLMNotificationToken.h"

@class RLMRealm;

@interface RLMRealmNotificationToken : RLMNotificationToken
{
    RLMRealm *_realm;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) RLMRealm *realm; // @synthesize realm=_realm;
- (void).cxx_destruct;
- (void)dealloc;
- (void)suppressNextNotification;
- (void)stop;

@end

