//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMapTable, NSMutableArray;
@protocol OS_dispatch_queue;

@interface TaskResumeManager : NSObject
{
    NSMutableArray *_queuedTasks;
    NSMapTable *_pendingTasks;
    NSMapTable *_progressingTasks;
    NSDate *_lastResumeTime;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) NSDate *lastResumeTime; // @synthesize lastResumeTime=_lastResumeTime;
@property(retain) NSMapTable *progressingTasks; // @synthesize progressingTasks=_progressingTasks;
@property(retain) NSMapTable *pendingTasks; // @synthesize pendingTasks=_pendingTasks;
@property(retain) NSMutableArray *queuedTasks; // @synthesize queuedTasks=_queuedTasks;
- (void).cxx_destruct;
- (void)taskCompleted:(id)arg1;
- (void)progressNotified:(id)arg1;
- (void)queueTask:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)_taskCompleted:(id)arg1;
- (void)_queueTask:(id)arg1;
- (void)_handleProgressNotification:(id)arg1;
- (void)_resumeNextTask;
- (void)_maybeResumeNextTask;
- (void)_resetStateForForeground;
- (void)_resumeAllTasksForBackground;
- (_Bool)_isInBackground;
- (id)init;

@end

