//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TokenHolder : NSObject
{
    NSString *_stringValue;
    shared_ptr_1dc51f47 _encodeFactory;
}

@property(readonly, nonatomic) shared_ptr_1dc51f47 encodeFactory; // @synthesize encodeFactory=_encodeFactory;
@property(readonly, copy, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithEncoderFactory:(shared_ptr_1dc51f47)arg1;

@end

