//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ServiceChat/SCManagedSingleton-Protocol.h>
#import <ServiceChat/SCSChatBotMenuDelegate-Protocol.h>
#import <ServiceChat/SCSChatEventDelegate-Protocol.h>
#import <ServiceChat/SCSChatSessionDelegate-Protocol.h>

@class MultiCastDelegateManager, NSString, SCAppearanceConfiguration, SCInterfaceRouter, SCSChat, SCSChatBotMenu;
@protocol SCSChatInterfaceFlow;

@interface SCSChatInterface : NSObject <SCManagedSingleton, SCSChatEventDelegate, SCSChatBotMenuDelegate, SCSChatSessionDelegate>
{
    MultiCastDelegateManager *_delegateManager;
    NSObject<SCSChatInterfaceFlow> *_interfaceFlow;
    SCInterfaceRouter *_interfaceRouter;
    SCAppearanceConfiguration *_appearanceConfiguration;
    long long _endReason;
    SCSChatBotMenu *_footerMenu;
    SCSChatBotMenu *_quickReplyMenu;
}

+ (id)nameForServiceInManager:(id)arg1;
@property(retain, nonatomic) SCSChatBotMenu *quickReplyMenu; // @synthesize quickReplyMenu=_quickReplyMenu;
@property(retain, nonatomic) SCSChatBotMenu *footerMenu; // @synthesize footerMenu=_footerMenu;
@property(nonatomic) long long endReason; // @synthesize endReason=_endReason;
@property(nonatomic) __weak SCAppearanceConfiguration *appearanceConfiguration; // @synthesize appearanceConfiguration=_appearanceConfiguration;
@property(nonatomic) __weak SCInterfaceRouter *interfaceRouter; // @synthesize interfaceRouter=_interfaceRouter;
@property(retain, nonatomic) NSObject<SCSChatInterfaceFlow> *interfaceFlow; // @synthesize interfaceFlow=_interfaceFlow;
@property(retain, nonatomic) MultiCastDelegateManager *delegateManager; // @synthesize delegateManager=_delegateManager;
- (void).cxx_destruct;
- (void)dismissChat;
- (void)showChatWithConfiguration:(id)arg1 showPrechat:(_Bool)arg2;
- (void)showChatWithConfiguration:(id)arg1;
- (void)showPrechatWithFields:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showPrechatWithFields:(id)arg1 modal:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)shouldDisplayNotificationInForeground;
- (void)handleNotification:(id)arg1;
- (void)removeViewControllerDelegate:(id)arg1;
- (void)addViewControllerDelegate:(id)arg1;
- (void)session:(id)arg1 didEnd:(id)arg2;
- (void)session:(id)arg1 didError:(id)arg2 fatal:(_Bool)arg3;
- (void)session:(id)arg1 didUpdateQueuePosition:(id)arg2 estimatedWaitTime:(id)arg3;
- (void)cleanUp;
- (void)session:(id)arg1 didTransitionFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;
- (void)chatMenuExpired:(id)arg1;
- (void)session:(id)arg1 agentLeftConference:(id)arg2;
- (void)session:(id)arg1 didReceiveURL:(id)arg2;
- (void)session:(id)arg1 processedOutgoingMessage:(id)arg2;
- (void)session:(id)arg1 didReceiveFileTransferRequest:(id)arg2;
- (void)session:(id)arg1 didUpdateOutgoingMessageDeliveryStatus:(id)arg2;
- (void)session:(id)arg1 didReceiveChatBotMenu:(id)arg2;
- (void)session:(id)arg1 didSelectMenuItem:(id)arg2;
- (void)session:(id)arg1 didReceiveMessage:(id)arg2;
- (void)session:(id)arg1 agentJoined:(id)arg2;
- (void)transferToButtonFailedWithSession:(id)arg1 error:(id)arg2;
- (void)transferToButtonInitiatedWithSession:(id)arg1;
- (void)transferToButtonCompletedWithSession:(id)arg1;
- (void)agentFinishedTypingWithSession:(id)arg1;
- (void)agentBeganTypingWithSession:(id)arg1;
- (void)registerDelegates;
@property(readonly, nonatomic) __weak SCSChat *sessionManager;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

