//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DBDevicePaywallFlowController : NSObject
{
    // Error parsing type: , name: loadingView
    // Error parsing type: , name: isPresenting
    // Error parsing type: , name: isEnding
    // Error parsing type: , name: navigationController
    // Error parsing type: , name: userState
    // Error parsing type: , name: deviceManager
    // Error parsing type: , name: modalManager
    // Error parsing type: , name: payments
    // Error parsing type: , name: deviceLimitObserverHandle
    // Error parsing type: , name: deviceLimitsInfo
    // Error parsing type: , name: paywallViewController
    // Error parsing type: , name: logger
}

- (void).cxx_destruct;
- (id)init;
- (void)debug_startPaywallFlow;
- (void)paymentsStatusChanged:(id)arg1;
- (void)dealloc;
- (id)initWithUserState:(id)arg1 payments:(id)arg2 noauthStormcrow:(id)arg3 logger:(id)arg4 modalManager:(id)arg5 navigationController:(id)arg6;

@end

