//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DropboxExtensions/DBSerializable-Protocol.h>
#import <DropboxExtensions/NSCopying-Protocol.h>

@class DBFILESFswRequest, NSArray, NSNumber, NSString;

@interface DBFILESRelocationBatchArgBase : NSObject <DBSerializable, NSCopying>
{
    NSArray *_entries;
    NSNumber *_autorename;
    DBFILESFswRequest *_fswRequest;
}

+ (id)deserialize:(id)arg1;
+ (id)serialize:(id)arg1;
@property(readonly, nonatomic) DBFILESFswRequest *fswRequest; // @synthesize fswRequest=_fswRequest;
@property(readonly, nonatomic) NSNumber *autorename; // @synthesize autorename=_autorename;
@property(readonly, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (void).cxx_destruct;
- (_Bool)isEqualToRelocationBatchArgBase:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithEntries:(id)arg1;
- (id)initWithEntries:(id)arg1 autorename:(id)arg2 fswRequest:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

