//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

#import "CAAnimationDelegate-Protocol.h"

@class NSAttributedString, NSString, UIColor, UIFont, UIView;

@interface DBMarqueeLabel : UILabel <CAAnimationDelegate>
{
    // Error parsing type: , name: type
    // Error parsing type: , name: scrollSequence
    // Error parsing type: , name: animationCurve
    // Error parsing type: , name: labelize
    // Error parsing type: , name: holdScrolling
    // Error parsing type: , name: tapToScroll
    // Error parsing type: , name: speed
    // Error parsing type: , name: leadingBuffer
    // Error parsing type: , name: trailingBuffer
    // Error parsing type: , name: fadeLength
    // Error parsing type: , name: animationDelay
    // Error parsing type: , name: sublabel
    // Error parsing type: , name: homeLabelFrame
    // Error parsing type: , name: awayOffset
    // Error parsing type: , name: scrollCompletionBlock
}

+ (Class)layerClass;
- (void).cxx_destruct;
@property(nonatomic) _Bool isAccessibilityElement;
@property(nonatomic) long long contentMode;
- (void)tintColorDidChange;
@property(nonatomic, retain) UIColor *tintColor;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
@property(nonatomic) long long baselineAdjustment;
@property(nonatomic) double minimumScaleFactor;
@property(nonatomic) _Bool adjustsFontSizeToFitWidth;
@property(nonatomic) long long numberOfLines;
@property(nonatomic) _Bool enabled;
- (_Bool)isEnabled;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
@property(nonatomic, retain) UIColor *highlightedTextColor;
@property(nonatomic) struct CGSize shadowOffset;
@property(nonatomic, retain) UIColor *shadowColor;
@property(nonatomic, retain) UIColor *backgroundColor;
@property(nonatomic, retain) UIColor *textColor;
@property(nonatomic, retain) UIFont *font;
@property(nonatomic, retain) NSAttributedString *attributedText;
@property(nonatomic, copy) NSString *text;
@property(nonatomic, readonly) UIView *viewForLastBaselineLayout;
- (id)viewForBaselineLayout;
- (void)labelWasTapped:(id)arg1;
- (void)shutdownLabel;
- (void)restartLabel;
- (void)animateForController:(id)arg1;
- (void)labelizeForController:(id)arg1;
- (void)restartForViewController:(id)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForInterfaceBuilder;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) double animationDelay; // @synthesize animationDelay;
@property(nonatomic) double fadeLength; // @synthesize fadeLength;
@property(nonatomic) double trailingBuffer; // @synthesize trailingBuffer;
@property(nonatomic) double leadingBuffer; // @synthesize leadingBuffer;
@property(nonatomic) double scrollRate;
@property(nonatomic) double scrollDuration;
@property(nonatomic) _Bool tapToScroll; // @synthesize tapToScroll;
@property(nonatomic) _Bool holdScrolling; // @synthesize holdScrolling;
@property(nonatomic) _Bool labelize; // @synthesize labelize;

@end

