//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DBDatabaseQueryQueue, DBObserverBlockMap;

@interface DBMetadataDatabase : NSObject
{
    DBDatabaseQueryQueue *_dbQueue;
    DBObserverBlockMap *_updateObservers;
    DBObserverBlockMap *_deltaUpdateObservers;
}

+ (struct NSDictionary *)db_pathDictionaryFromMetadataArray:(id)arg1;
+ (id)db_computeDiffFromExistingMetadata:(struct NSDictionary *)arg1 toNewContentMetadataArray:(struct NSDictionary *)arg2;
+ (_Bool)db_updateRowWithMetadata:(id)arg1 fromMetadata:(id)arg2 withQueryHelper:(id)arg3;
+ (id)db_directoryContentsForPath:(id)arg1 page:(id)arg2 queryHelper:(id)arg3 shouldRollback:(_Bool *)arg4;
+ (id)db_metadataAndCursorForPath:(id)arg1 queryHelper:(id)arg2 outSuccess:(_Bool *)arg3;
+ (id)db_metadataAndCursorForPath:(id)arg1 queryHelper:(id)arg2;
+ (id)db_metadataForPath:(id)arg1 queryHelper:(id)arg2;
+ (_Bool)db_getMetadataForPath:(id)arg1 queryHelper:(id)arg2 outMetadata:(id *)arg3;
+ (void)db_queueInitAnalyticsOnQueue:(id)arg1 analyticsLogger:(id)arg2;
- (void).cxx_destruct;
- (void)db_invokeDeltaObserversWithUpdatedMetadatas:(id)arg1 removedPaths:(id)arg2;
- (void)db_invokeObserversWithAddedMetadatas:(struct NSDictionary *)arg1 updatedMetadatas:(struct NSDictionary *)arg2 context:(id)arg3 removedPaths:(id)arg4;
- (id)addDeltaUpdateObserver:(CDUnknownBlockType)arg1;
- (id)addUpdateObserver:(CDUnknownBlockType)arg1;
- (void)terminateWithCompletion:(CDUnknownBlockType)arg1;
- (void)debug_wipeMetadataJournalTable:(CDUnknownBlockType)arg1;
- (void)debug_wipeMetadataTable:(CDUnknownBlockType)arg1;
- (void)debug_getRowsInMetadataDeltaCursorsTable:(CDUnknownBlockType)arg1;
- (void)debug_getRowsInMetadataJournalTable:(CDUnknownBlockType)arg1;
- (void)debug_getRowsInMetadataTable:(CDUnknownBlockType)arg1;
- (void)debug_getRowsInMetadataWithJournalView:(CDUnknownBlockType)arg1;
- (void)clearAllDeltaSyncCursors:(CDUnknownBlockType)arg1;
- (void)deleteMetadataUnderPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)processDeltaWithParentPath:(id)arg1 withAddsOrUpdatesFull:(id)arg2 pathsToRemove:(id)arg3 oldDeltaSyncCursor:(id)arg4 newDeltaSyncCursor:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)finishDeltaWithParentMetadata:(id)arg1 updatedPaths:(id)arg2 removedPaths:(id)arg3 deltaSyncCursor:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)locallyDeleteMetadataForPath:(id)arg1 andAddMetadata:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)locallyDeleteMetadataForPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)locallyDeleteMetadataForPaths:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)db_invokeObserversForAddMetadata:(id)arg1 path:(id)arg2 oldMetadata:(id)arg3;
- (void)locallyAddMetadata:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (unsigned long long)localChildItemCountWithPath:(id)arg1;
- (id)currentDirectoryContentsForPath:(id)arg1;
- (id)currentMetadataAndDeltaSyncCursorForPath:(id)arg1;
- (id)currentMetadataForPath:(id)arg1;
- (void)getDirectoryContentsForPath:(id)arg1 page:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getDirectoryContentsForPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getMetadataForPaths:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getMetadataAndDeltaSyncCursorForPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getMetadataForPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithDatabaseQueue:(id)arg1 analyticsLogger:(id)arg2;

@end

