//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PSPDFKitUI/PSPDFAnnotationCreator.h>

#import <PSPDFKitUI/PSPDFSignatureSelectorViewControllerDelegate-Protocol.h>
#import <PSPDFKitUI/PSPDFSignatureViewControllerDelegate-Protocol.h>

@class NSString, PSPDFConfiguration, PSPDFDigitalSignatureCoordinator, PSPDFSignatureFormElement;
@protocol PSPDFPresentationContext;

@interface PSPDFSignatureAnnotationCreator : PSPDFAnnotationCreator <PSPDFSignatureViewControllerDelegate, PSPDFSignatureSelectorViewControllerDelegate>
{
    id <PSPDFPresentationContext> _presentationContext;
    PSPDFSignatureFormElement *_signatureFormElement;
    PSPDFConfiguration *_configuration;
    PSPDFDigitalSignatureCoordinator *_signatureCoordinator;
}

+ (void)removeDidDismissCancellationHandlerOnViewController:(id)arg1;
@property(readonly, nonatomic) PSPDFDigitalSignatureCoordinator *signatureCoordinator; // @synthesize signatureCoordinator=_signatureCoordinator;
@property(readonly, nonatomic) PSPDFConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) __weak PSPDFSignatureFormElement *signatureFormElement; // @synthesize signatureFormElement=_signatureFormElement;
@property(readonly, nonatomic) __weak id <PSPDFPresentationContext> presentationContext; // @synthesize presentationContext=_presentationContext;
- (void).cxx_destruct;
- (void)insertSignatureAndRunPostJSActions:(id)arg1 formElement:(id)arg2;
- (id)signatureAnnotationWithLines:(id)arg1 lineWidth:(double)arg2 color:(id)arg3 sizeReductionFactor:(double)arg4 naturalDrawingEnabled:(_Bool)arg5;
- (void)startSignatureFormElementAreaDrawingForViewController:(id)arg1;
- (void)signDocumentWithSignature:(id)arg1 withViewController:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)signatureSelectorViewControllerWillCreateNewSignature:(id)arg1;
- (void)signatureSelectorViewController:(id)arg1 didSelectSignature:(id)arg2;
- (void)signatureViewControllerDidFinish:(id)arg1 withSigner:(id)arg2 shouldSaveSignature:(_Bool)arg3;
- (void)signatureViewControllerDidCancel:(id)arg1;
- (id)presentSignatureSelectionControllerIfPossible:(id)arg1 presentationOptions:(id)arg2;
- (id)presentSignatureCreationController:(id)arg1 presentationOptions:(id)arg2;
- (void)removeDismissalHandlerAndDismissViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)installDidDismissCancellationHandlerOnViewController:(id)arg1;
- (id)presentAppropriateSignatureController:(id)arg1 presentationOptions:(id)arg2;
- (_Bool)automaticallyTransitionToCompletedAfterControllersAreDismissed;
- (id)initWithPageView:(id)arg1 signatureFormElement:(id)arg2 presentationContext:(id)arg3;
- (id)initWithPage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

