//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Module_Framework/NSObject-Protocol.h>

@class MDXScreenDiscoveryManager, NSArray;
@protocol MDXScreen;

@protocol MDXScreenDiscoveryManagerObserver <NSObject>

@optional
- (void)screenDiscoveryManager:(MDXScreenDiscoveryManager *)arg1 existingSessionDiscoveredForScreen:(id <MDXScreen>)arg2;
- (void)screenDiscoveryManager:(MDXScreenDiscoveryManager *)arg1 remoteScreenNameDidChange:(id <MDXScreen>)arg2;
- (void)screenDiscoveryManager:(MDXScreenDiscoveryManager *)arg1 onlineScreensDidChange:(NSArray *)arg2;
- (void)discoveryWarmUpDidCompleteForScreenDiscoveryManager:(MDXScreenDiscoveryManager *)arg1;
@end

