//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Module_Framework/GPBMessage.h>

@interface YTIEmbeddedPlayerHotConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool deprecateClientScreen; // @dynamic deprecateClientScreen;
@property(nonatomic) _Bool disableAdChoicesDialog; // @dynamic disableAdChoicesDialog;
@property(nonatomic) _Bool disablePlayerOverlayLazyViewInflation; // @dynamic disablePlayerOverlayLazyViewInflation;
@property(nonatomic) _Bool embedsIosCrashReportingKillSwitch; // @dynamic embedsIosCrashReportingKillSwitch;
@property(nonatomic) _Bool enableActiveViewMonitoring; // @dynamic enableActiveViewMonitoring;
@property(nonatomic) _Bool enableAndroidAdEventLogging; // @dynamic enableAndroidAdEventLogging;
@property(nonatomic) _Bool enableBottomSheetOverflow; // @dynamic enableBottomSheetOverflow;
@property(nonatomic) _Bool enableDttsFlag; // @dynamic enableDttsFlag;
@property(nonatomic) _Bool enableIosDeeplinkInTitleWithAnimation; // @dynamic enableIosDeeplinkInTitleWithAnimation;
@property(nonatomic) _Bool enableLandscapeFullscreen; // @dynamic enableLandscapeFullscreen;
@property(nonatomic) _Bool enablePlayerErrorMessageRenderer; // @dynamic enablePlayerErrorMessageRenderer;
@property(nonatomic) _Bool enableRelatedScrollerAtEndOfVideo; // @dynamic enableRelatedScrollerAtEndOfVideo;
@property(nonatomic) _Bool enableRelaxedModeFirstParty; // @dynamic enableRelaxedModeFirstParty;
@property(nonatomic) _Bool enableUserPresenceTracking; // @dynamic enableUserPresenceTracking;
@property(nonatomic) _Bool enableWindowFocusCheck; // @dynamic enableWindowFocusCheck;
@property(nonatomic) _Bool endToEndTestFlag; // @dynamic endToEndTestFlag;
@property(nonatomic) _Bool hasDeprecateClientScreen; // @dynamic hasDeprecateClientScreen;
@property(nonatomic) _Bool hasDisableAdChoicesDialog; // @dynamic hasDisableAdChoicesDialog;
@property(nonatomic) _Bool hasDisablePlayerOverlayLazyViewInflation; // @dynamic hasDisablePlayerOverlayLazyViewInflation;
@property(nonatomic) _Bool hasEmbedsIosCrashReportingKillSwitch; // @dynamic hasEmbedsIosCrashReportingKillSwitch;
@property(nonatomic) _Bool hasEnableActiveViewMonitoring; // @dynamic hasEnableActiveViewMonitoring;
@property(nonatomic) _Bool hasEnableAndroidAdEventLogging; // @dynamic hasEnableAndroidAdEventLogging;
@property(nonatomic) _Bool hasEnableBottomSheetOverflow; // @dynamic hasEnableBottomSheetOverflow;
@property(nonatomic) _Bool hasEnableDttsFlag; // @dynamic hasEnableDttsFlag;
@property(nonatomic) _Bool hasEnableIosDeeplinkInTitleWithAnimation; // @dynamic hasEnableIosDeeplinkInTitleWithAnimation;
@property(nonatomic) _Bool hasEnableLandscapeFullscreen; // @dynamic hasEnableLandscapeFullscreen;
@property(nonatomic) _Bool hasEnablePlayerErrorMessageRenderer; // @dynamic hasEnablePlayerErrorMessageRenderer;
@property(nonatomic) _Bool hasEnableRelatedScrollerAtEndOfVideo; // @dynamic hasEnableRelatedScrollerAtEndOfVideo;
@property(nonatomic) _Bool hasEnableRelaxedModeFirstParty; // @dynamic hasEnableRelaxedModeFirstParty;
@property(nonatomic) _Bool hasEnableUserPresenceTracking; // @dynamic hasEnableUserPresenceTracking;
@property(nonatomic) _Bool hasEnableWindowFocusCheck; // @dynamic hasEnableWindowFocusCheck;
@property(nonatomic) _Bool hasEndToEndTestFlag; // @dynamic hasEndToEndTestFlag;
@property(nonatomic) _Bool hasIntentToPlayTimeLimit; // @dynamic hasIntentToPlayTimeLimit;
@property(nonatomic) _Bool hasSetAutoplayFlagInPlayerRequest; // @dynamic hasSetAutoplayFlagInPlayerRequest;
@property(nonatomic) _Bool hasShowNerdStats; // @dynamic hasShowNerdStats;
@property(nonatomic) float intentToPlayTimeLimit; // @dynamic intentToPlayTimeLimit;
@property(nonatomic) _Bool setAutoplayFlagInPlayerRequest; // @dynamic setAutoplayFlagInPlayerRequest;
@property(nonatomic) _Bool showNerdStats; // @dynamic showNerdStats;

@end

