//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Module_Framework/GPBMessage.h>

@class YTIMealbarPromoRenderer, YTIUnpluggedAlertRenderer, YTIUnpluggedLocationResolutionRenderer, YTIUnpluggedMultiselectPopupRenderer, YTIUnpluggedOverflowMenuPopupRenderer, YTIUnpluggedPromoRenderer, YTIUnpluggedSelectionMenuDialogRenderer;

@interface YTIUnpluggedPopupSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) YTIMealbarPromoRenderer *mealbarPromoRenderer; // @dynamic mealbarPromoRenderer;
@property(readonly, nonatomic) int rendererOneOfCase; // @dynamic rendererOneOfCase;
@property(retain, nonatomic) YTIUnpluggedAlertRenderer *unpluggedAlertRenderer; // @dynamic unpluggedAlertRenderer;
@property(retain, nonatomic) YTIUnpluggedLocationResolutionRenderer *unpluggedLocationResolutionRenderer; // @dynamic unpluggedLocationResolutionRenderer;
@property(retain, nonatomic) YTIUnpluggedMultiselectPopupRenderer *unpluggedMultiselectPopupRenderer; // @dynamic unpluggedMultiselectPopupRenderer;
@property(retain, nonatomic) YTIUnpluggedOverflowMenuPopupRenderer *unpluggedOverflowMenuPopupRenderer; // @dynamic unpluggedOverflowMenuPopupRenderer;
@property(retain, nonatomic) YTIUnpluggedPromoRenderer *unpluggedPromoRenderer; // @dynamic unpluggedPromoRenderer;
@property(retain, nonatomic) YTIUnpluggedSelectionMenuDialogRenderer *unpluggedSelectionMenuDialogRenderer; // @dynamic unpluggedSelectionMenuDialogRenderer;

@end

