//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class YTEditOverlayButtonModel;

@interface YTShortsEditorToolbeltButtonModel : NSObject
{
    long long _viewAction;
    YTEditOverlayButtonModel *_overlayButtonModel;
}

+ (id)modelFromOverlayButtonModel:(id)arg1 viewAction:(long long)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) YTEditOverlayButtonModel *overlayButtonModel; // @synthesize overlayButtonModel=_overlayButtonModel;
@property(readonly, nonatomic) long long viewAction; // @synthesize viewAction=_viewAction;
- (id)initWithOverlayButtonModel:(id)arg1 viewAction:(long long)arg2;

@end

