//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/FNFMp4StreamingReader-Protocol.h>

@class NSData, NSString;

@interface FNFDashMp4StreamReader : NSObject <FNFMp4StreamingReader>
{
    NSData *_data;
    unsigned long long _offset;
}

- (void).cxx_destruct;
- (void)setOffset:(unsigned long long)arg1;
- (unsigned long long)offset;
- (_Bool)hasEnoughDataForBytes:(unsigned long long)arg1;
- (void)moveHead:(unsigned long long)arg1;
- (const char *)bytesAtHead:(long long)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

