//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InstagramAppCoreFramework/NSObject-Protocol.h>

@class IGChangePhoneNumberViewController, IGCountryCodeViewController, NSString;

@protocol IGChangePhoneNumberViewControllerDelegate <NSObject>
- (void)changePhonenumberViewController:(IGChangePhoneNumberViewController *)arg1 didSelectCountryCode:(NSString *)arg2;
- (void)changePhonenumberViewController:(IGChangePhoneNumberViewController *)arg1 willPresentCountryCodeViewController:(IGCountryCodeViewController *)arg2;
- (void)changePhoneNumberViewController:(IGChangePhoneNumberViewController *)arg1 doneEditingWithCountryNumber:(NSString *)arg2 phoneNumber:(NSString *)arg3 contactPreference:(unsigned long long)arg4;
@end

