//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGCookieTransferring-Protocol.h>

@class IGUserCookieStorage, NSString;
@protocol IGAPIClient, IGWebViewDataStoreManaging;

@interface IGCookieTransferrer : NSObject <IGCookieTransferring>
{
    id <IGAPIClient> _apiClient;
    NSString *_userPK;
    IGUserCookieStorage *_userCookieStorage;
    id <IGWebViewDataStoreManaging> _webviewDataStoreContainer;
}

- (void).cxx_destruct;
- (void)transferCookiesIntoSharedStore;
- (id)initWithAPIClient:(id)arg1 userPK:(id)arg2 userCookieStorage:(id)arg3 webviewDataStoreContainer:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

