//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InstagramAppCoreFramework/NSObject-Protocol.h>

@class IGEditorTabBar, UIView;
@protocol IGEditorTabView;

@protocol IGEditorTabBarDelegate <NSObject>
- (_Bool)tabBar:(IGEditorTabBar *)arg1 shouldSelectTabView:(UIView<IGEditorTabView> *)arg2;
- (void)tabBar:(IGEditorTabBar *)arg1 didSelectTabView:(UIView<IGEditorTabView> *)arg2 previousTabView:(UIView<IGEditorTabView> *)arg3;
@end

