//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <InstagramAppCoreFramework/UITextFieldDelegate-Protocol.h>

@class IGLiveRealtimeSubmitQuestionBroadcasterView, IGTapButton, NSString, UITextField;
@protocol IGLiveRealtimeSubmitQuestionComposerDelegate;

@interface IGLiveRealtimeSubmitQuestionComposer : UIView <UITextFieldDelegate>
{
    IGLiveRealtimeSubmitQuestionBroadcasterView *_broadcasterView;
    UIView *_ovalContainer;
    UITextField *_textField;
    IGTapButton *_sendButton;
    id <IGLiveRealtimeSubmitQuestionComposerDelegate> _delegate;
}

@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) __weak id <IGLiveRealtimeSubmitQuestionComposerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_attributedTypeInYourQuestionPlaceholder;
- (void)_installAndConfigureSendButton;
- (void)_installAndConfigureTextField;
- (void)_installAndConfigureOvalContainer;
- (void)_installAndConfigureBroadcasterViewWithBroadcaster:(id)arg1 analyticsModule:(id)arg2;
- (void)_send;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)_textFieldTextDidChangeNotification:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithBroadcaster:(id)arg1 analyticsModule:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

