//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import <InstagramAppCoreFramework/IGMutedListNetworkDataSourceDelegate-Protocol.h>
#import <InstagramAppCoreFramework/UITableViewDataSource-Protocol.h>
#import <InstagramAppCoreFramework/UITableViewDelegate-Protocol.h>

@class IGListItemView, IGMutedListNetworkDataSource, IGTableLayoutSpec, IGUserSession, NSString, UITableView;

@interface IGMutedListViewController : IGViewController <IGMutedListNetworkDataSourceDelegate, UITableViewDataSource, UITableViewDelegate>
{
    IGMutedListNetworkDataSource *_networkDataSource;
    IGUserSession *_userSession;
    UITableView *_tableView;
    IGTableLayoutSpec *_layoutSpec;
    IGListItemView *_sizingView;
    double _tailLoadDistance;
}

- (void).cxx_destruct;
- (id)_viewModelForUser:(id)arg1;
- (void)_loadMoreUsers;
- (void)scrollViewDidScroll:(id)arg1;
- (void)dataSourceDidFailLoad:(id)arg1;
- (void)dataSourceDidFinishLoading:(id)arg1;
- (void)dataSourceDidStartLoading:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 title:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

