//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InstagramAppCoreFramework/NSObject-Protocol.h>

@class IGRegistrationAccountLinkingView;

@protocol IGRegistrationAccountLinkingViewDelegate <NSObject>
- (void)registrationAccountLinkingViewDidTapCreateNewPasswordInsteadButton:(IGRegistrationAccountLinkingView *)arg1;
- (void)registrationAccountLinkingViewDidTapNextButton:(IGRegistrationAccountLinkingView *)arg1;
- (void)registrationAccountLinkingView:(IGRegistrationAccountLinkingView *)arg1 didTapLearnMoreLabelWithEntryPoint:(long long)arg2;
- (void)registrationAccountLinkingViewDidTapBackButton:(IGRegistrationAccountLinkingView *)arg1;
@end

