//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import <InstagramAppCoreFramework/IGAdsBottomCTAControllerDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGContextualFeedBottomNuxControllerDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGDirectPivotSUDataSourceDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGFeedItemPreviewProviding-Protocol.h>
#import <InstagramAppCoreFramework/IGFeedItemVisibilityChangeListener-Protocol.h>
#import <InstagramAppCoreFramework/IGFeedNetworkSourceDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGFeedPreviewingType-Protocol.h>
#import <InstagramAppCoreFramework/IGFeedScrollViewListener-Protocol.h>
#import <InstagramAppCoreFramework/IGFeedStatusViewDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGListAdapterCompletionListener-Protocol.h>
#import <InstagramAppCoreFramework/IGListAdapterDataSource-Protocol.h>
#import <InstagramAppCoreFramework/IGListAdapterDelegate-Protocol.h>
#import <InstagramAppCoreFramework/IGMediaHiddenListener-Protocol.h>
#import <InstagramAppCoreFramework/IGSingleFeedViewControllerType-Protocol.h>
#import <InstagramAppCoreFramework/IGTombstoneManagerDelegate-Protocol.h>

@class IGAdsBottomCTAController, IGCTAPresenterContext, IGContextualFeedBottomNuxController, IGDirectPivotSUDataSource, IGDiscoverPeopleItemConfiguration, IGFeedItem, IGFeedNetworkSource, IGFeedPreviewingHandler, IGFeedStarterKit, IGProfileChainingLogger, IGProfilePictureHelper, IGSingleFeedTitleHelper, IGSingleFeedViewControllerConfiguration, IGTableLayoutSpec, IGTombstoneManager, IGTombstoneView, IGUserSession, NSArray, NSString;
@protocol IGFeedConfigurationType, IGFeedItemConfigurationType, IGFeedSectionControllerComponentsType;

@interface IGSingleFeedViewController : IGViewController <IGContextualFeedBottomNuxControllerDelegate, IGDirectPivotSUDataSourceDelegate, IGFeedNetworkSourceDelegate, IGFeedPreviewingType, IGFeedScrollViewListener, IGFeedStatusViewDelegate, IGListAdapterCompletionListener, IGListAdapterDataSource, IGListAdapterDelegate, IGTombstoneManagerDelegate, IGAdsBottomCTAControllerDelegate, IGMediaHiddenListener, IGFeedItemVisibilityChangeListener, IGSingleFeedViewControllerType, IGFeedItemPreviewProviding>
{
    IGSingleFeedTitleHelper *_singleFeedTitleHelper;
    IGCTAPresenterContext *_ctaPresenterContext;
    IGAdsBottomCTAController *_ctaController;
    double _additionalBottomInsetForCTA;
    _Bool _showPill;
    IGFeedNetworkSource *_feedNetworkSource;
    IGSingleFeedViewControllerConfiguration *_configuration;
    id <IGFeedConfigurationType> _feedConfiguration;
    id <IGFeedItemConfigurationType> _itemConfiguration;
    NSString *_previewCommentID;
    IGFeedStarterKit *_feed;
    id <IGFeedSectionControllerComponentsType> _feedSectionControllerComponents;
    IGUserSession *_userSession;
    IGFeedPreviewingHandler *_previewingHandler;
    IGProfilePictureHelper *_profilePictureHelper;
    IGTombstoneManager *_tombstoneManager;
    IGTombstoneView *_tombstoneView;
    IGFeedItem *_feedItem;
    NSArray *_suggestions;
    IGDirectPivotSUDataSource *_dataSource;
    IGProfileChainingLogger *_chainingLogger;
    IGContextualFeedBottomNuxController *_nuxController;
    IGDiscoverPeopleItemConfiguration *_firstDiscoverPeopleItemConfiguration;
    IGTableLayoutSpec *_tableInterface;
}

@property(readonly, nonatomic) IGTableLayoutSpec *tableInterface; // @synthesize tableInterface=_tableInterface;
@property(readonly, nonatomic) IGDiscoverPeopleItemConfiguration *firstDiscoverPeopleItemConfiguration; // @synthesize firstDiscoverPeopleItemConfiguration=_firstDiscoverPeopleItemConfiguration;
@property(readonly, nonatomic) IGContextualFeedBottomNuxController *nuxController; // @synthesize nuxController=_nuxController;
@property(readonly, nonatomic) IGProfileChainingLogger *chainingLogger; // @synthesize chainingLogger=_chainingLogger;
@property(readonly, nonatomic) IGDirectPivotSUDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) NSArray *suggestions; // @synthesize suggestions=_suggestions;
@property(readonly, nonatomic) _Bool showPill; // @synthesize showPill=_showPill;
@property(retain, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
@property(readonly, nonatomic) IGTombstoneView *tombstoneView; // @synthesize tombstoneView=_tombstoneView;
@property(readonly, nonatomic) IGTombstoneManager *tombstoneManager; // @synthesize tombstoneManager=_tombstoneManager;
@property(readonly, nonatomic) IGProfilePictureHelper *profilePictureHelper; // @synthesize profilePictureHelper=_profilePictureHelper;
@property(readonly, nonatomic) IGFeedPreviewingHandler *previewingHandler; // @synthesize previewingHandler=_previewingHandler;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) id <IGFeedSectionControllerComponentsType> feedSectionControllerComponents; // @synthesize feedSectionControllerComponents=_feedSectionControllerComponents;
@property(readonly, nonatomic) IGFeedStarterKit *feed; // @synthesize feed=_feed;
@property(copy, nonatomic) NSString *previewCommentID; // @synthesize previewCommentID=_previewCommentID;
@property(readonly, nonatomic) id <IGFeedItemConfigurationType> itemConfiguration; // @synthesize itemConfiguration=_itemConfiguration;
@property(readonly, nonatomic) id <IGFeedConfigurationType> feedConfiguration; // @synthesize feedConfiguration=_feedConfiguration;
@property(readonly, nonatomic) IGSingleFeedViewControllerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) IGFeedNetworkSource *feedNetworkSource; // @synthesize feedNetworkSource=_feedNetworkSource;
- (void).cxx_destruct;
- (void)bottomCTAControllerDidShowCTA:(_Bool)arg1 withBottomOffset:(double)arg2;
- (void)bottomCTAControllerDidAddCTAView:(id)arg1 toScrollView:(id)arg2;
- (_Bool)shouldLogScreenshots;
- (id)getViewerUser;
- (id)getTargetUser;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillScrollNearTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillScrollNearBottom:(id)arg1;
- (void)contextualFeedBottomNuxWasTapped:(id)arg1;
- (id)analyticsExtras;
- (id)analyticsModule;
- (id)collectionView;
- (void)feedStatusEmptyStateButtonWasTapped:(id)arg1;
- (void)feedStatusViewDidTap:(id)arg1;
- (void)directPivotSUDataSource:(id)arg1 didLoadData:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didChangeToObjects:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didFailToLoadWithConfig:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didFinishLoadingObjects:(id)arg2 withConfig:(id)arg3;
- (void)feedNetworkSource:(id)arg1 didStartLoadingWithConfig:(id)arg2;
- (void)listAdapter:(id)arg1 didCompleteReloadAndRefreshHidden:(_Bool)arg2;
- (void)listAdapter:(id)arg1 didCompleteUpdateAnimated:(_Bool)arg2 refreshHidden:(_Bool)arg3;
- (void)listAdapter:(id)arg1 didEndDisplayingObject:(id)arg2 atIndex:(long long)arg3;
- (void)listAdapter:(id)arg1 willDisplayObject:(id)arg2 atIndex:(long long)arg3;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)tombstoneManager:(id)arg1 didTapShowButtonForTombstoneView:(id)arg2;
- (void)_showAggregatePromoteEngagementNUX;
- (void)_showAggregatePromoteEngagementNUXIfNeeded;
- (void)mediaHiddenFeedItem:(id)arg1 sourceModule:(id)arg2 storyReelPK:(id)arg3;
- (void)feedItemVisibilityChange:(id)arg1 withOldVisibility:(long long)arg2;
- (void)_updateFeedState;
- (void)_updateTombstoneView;
- (id)_indexPathForPoint:(struct CGPoint)arg1;
- (void)_scrollToItem:(id)arg1 animated:(_Bool)arg2;
- (id)_refreshButton;
- (void)_updateNavigationBarButtonItem;
- (id)_displayTitle;
- (void)_updateTitle;
- (void)_refresh;
- (long long)getCurrentPage;
- (id)objectForPreviewAtPoint:(struct CGPoint)arg1;
- (id)cellForPreviewAtPoint:(struct CGPoint)arg1;
- (struct UIEdgeInsets)preferredContentInsets;
- (void)viewDidAppear:(_Bool)arg1;
- (void)updateUserActivityState:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithFeedNetworkSource:(id)arg1 shouldFetchChainingSuggestions:(_Bool)arg2 configuration:(id)arg3 feedConfiguration:(id)arg4 itemConfiguration:(id)arg5 userSession:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

