//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@protocol IGVideoTranscoderProtocol <NSObject>
- (void)cancel;
- (void)startWithProgress:(void (^)(double))arg1 segmentStart:(void (^)(IGMediaTranscodedSegment *, struct))arg2 segmentCompletion:(void (^)(IGMediaTranscodedSegment *))arg3 completion:(void (^)(NSError *, IGSegmentsCompositionResult *))arg4 imageCompletion:(void (^)(struct opaqueCMSampleBuffer *))arg5;
@end

