//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC24PushMessagingFeatureImpl21PushMessagingListener.h"

#import "SPTThirdPartyUserTracker-Protocol.h"

@class NSString;

@interface _TtC24PushMessagingFeatureImpl21PushMessagingListener (PushMessagingFeatureImpl1) <SPTThirdPartyUserTracker>
- (void)userDidLogout;
- (void)userDidLoginWithProductState:(id)arg1;
- (_Bool)shouldEnableUserTracker;
@property(nonatomic, readonly) NSString *trackerUserID;

// Remaining properties
@property(nonatomic, readonly) _Bool enableUserTracker;
@end

