//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol IBroadcastConnectionManager <NSObject>
@property(nonatomic) unsigned int streamHeight;
@property(nonatomic) unsigned int streamWidth;
@property(nonatomic) unsigned int bitRate;
@property(nonatomic) unsigned int frameRate;
@property(retain, nonatomic) NSString *sessionId;
@property(nonatomic) _Bool isGameStreaming;
@property(readonly, nonatomic) unsigned long long gameStreamState;
@property(nonatomic) _Bool isGameStreamConnected;
@property(nonatomic) _Bool isGameStreamEnabled;
@property(nonatomic) _Bool isBroadcastChannelConnected;
- (void)startNetworkTest;
- (void)changeQuality:(unsigned int)arg1 resolutionIndex:(unsigned int)arg2 frameRateNum:(unsigned int)arg3 frameRateDen:(unsigned int)arg4;
- (void)disconnectFromStream;
- (void)connectToStream:(NSString *)arg1;
- (_Bool)sendFeedback;
- (_Bool)stopGameStream;
- (_Bool)startGameStream;
@end

